// questions array (below) is numbered 0-end
// but exam questions are numbered 1 - (end - 1)        
function checkAnswer() {
    
    var numOfQs = 0;
    
    var choices = [];
    var chosen = [];
    
    for (var i = 0; i < pos; i++ ) {
        numOfQs += qNum[i];
    }
    
    firstQ = numOfQs - qNum[pos - 1];
    //document.write(questions[pos].Correct);
    for (var j = firstQ; j < numOfQs; j++) {
    choices.push(document.getElementsByName("choices" + j));
    for (var i=0; i < choices[j -firstQ].length; i++) {
        if (choices[j - firstQ][i].checked) {
            chosen.push(choices[j - firstQ][i].value);
            //document.write("if");
        }
    }
    }
        
    //document.write(questions[pos].Correct);
    //document.write(choices.length);
    //document.write("Holass");
    for (var i=0; i < chosen.length; i++) {

        if (chosen[i] == questions[pos].Correct) {
            score++;
        }
    }
    
    //document.write("Hola");
    if (pos == test.length) {
        document.write("<h1>Te sacaste " + score + " de " + numOfQs + " preguntas</h1><br>");
        document.write(qNum);
    } else {
    renderQuestion();
    }
}


// will create array of htmls that make up
// ONE/SINGLE test
function testIntegrator() {
    var len = questions.length;
    var num = 0;
    var test = [];
    while (num < len) {
        
        var text = '<html lang="en">\
        <head></head>\
        <body>';
        if (questions[num].name.includes("-")) {
            var index = questions[num].name.indexOf("-");
            var z = parseInt(questions[num].name.substring(index+1));
            qNum.push(parseInt(z - num));
            for (; num < z; num++) {
                text += display(num+1);
            }
            text += '</body>\
            </html>'
            test.push(text);
        } else {
            text += '</body>\
            </html>'
            test.push(display(num+1));
            qNum.push(1);
            num++;
        }
    }
    
    return test;
}

// Like distill but w/ a test
function testtill(num) {
    num = num - 1;
    if (questions[num].name.includes("-")) {
        var i = questions[num].name.indexOf("-");
        document.write(i);
        var a = parseInt(questions[num].name[i-1]);
        document.write("<br>" +a);
        var z = parseInt(questions[num].name.substring(i+1));
        var text = "";
        for (j = a; j <= z; j++) {
            text += display(j);
        }
        return text;
    }
    else {
        return display(num + 1);
    }
}

//displays individual question (from array object below)
// display INPUT: # of Question
function display(num) {
    num = num - 1;
    choices = "'choices" + num + "'";
    var text = "";
    if (questions[num].prompt && questions[num].prompt.includes(" ")) {
        text += "<p>" + questions[num].prompt + "</p>";
    }
    text += "<p>" + questions[num].question +"</p>";
    text += "<input type='radio' name=" + choices + " value='A'> " + questions[num].A + "<br>";
    text += "<input type='radio' name=" + choices + " value='B'> " + questions[num].B + "<br>";
    text += "<input type='radio' name=" + choices + " value='C'> " + questions[num].C + "<br>";
    text += "<input type='radio' name=" + choices + " value='D'> " + questions[num].D + "<br>";
    text += "<input type='radio' name=" + choices + " value='E'> " + questions[num].E + "<br>";
    /*
    text += "<input type='radio' name='choices1' value='A'>" + questions[num].A + "<br>";
    text += "<input type='radio' name='choices' value='B'>" + questions[num].B + "<br>";
    text += "<input type='radio' name='choices' value='C'>" + questions[num].C + "<br>";
    text += "<input type='radio' name='choices' value='D'>" + questions[num].D + "<br>";
    text += "<input type='radio' name='choices' value='E'>" + questions[num].E + "<br>";
    */
    return text;  
}

var questions = [
	{
		name: "2016iiCE1-2",
		subject: "Literature",
		sub_subject: "Series",
		prompt: "Después de identificar y analizar la relación semántica de la serie de cada ítem, seleccione la respuesta más adecuada.",
		image: false,
		question: "Incuria, abandono, dejadez,",
		A: "soledad",
		B: "acritud",
		C: "cansancio",
		D: "encono",
		E: "desidia",
		Correct: "E"
	},
	{
		name: "2016iiCE2",
		subject: "Literature",
		sub_subject: "Series",
		prompt: "2016iiCE1-2",
		image: false,
		question: "Pródigo, cicatero; audaz, medroso;",
		A: "excesivo, rebosante",
		B: "insigne, sensible",
		C: "robusto, enteco",
		D: "forzoso, liberal",
		E: "templado, sereno",
		Correct: "C"
	},
	{
		name: "2016iiCE3-5",
		subject: "Literature",
		sub_subject: "Sentence Elimination",
		prompt: "Lea atentamente cada conjunto oracional y determine el enunciado que debe eliminarse por no corresponder al tema o por ser de índole tangencial.",
		image: false,
		question: "(I) La sabana es una gran llanura de suelo arcilloso e impermeable con temperaturas altas durante todo el año. (II) En la sabana no hay gran variedad de árboles, pues su enorme llanura está cubierta de hierbas. (III) Los árboles tienen una enorme importancia porque aportan materia orgánica y nutrientes a los suelos de estructura arcillosa. (IV) Debido a la exuberante vegetación herbácea que hay en la sabana, muchos animales herbívoros viven en este ecosistema. (V) Las lluvias que se dan en ese ecosistema se concentran en el tiempo de la estación húmeda.",
		A: "IV",
		B: "I",
		C: "V",
		D: "III",
		E: "II",
		Correct: "D"
	},
	{
		name: "2016iiCE4",
		subject: "Literature",
		sub_subject: "Sentence Elimination",
		prompt: "2016iiCE3-5",
		image: false,
		question: "(I) La pintura del Barroco mostró un naturalismo que la alejaba de la perfección clásica (II) El arte barroco se ha identificado tradicionalmente con el absolutismo que realzó el poder de los monarcas a través de la magnificencia. (III) El arte pictórico barroco se caracterizaba por la expresividad que reflejaba a veces apasionados estados de ánimo. (IV) La temática de la pintura barroca fue muy diversa y abarcó escenas mitológicas, religiosas, etc. (V) Igualmente, este arte jugaba con el contraste entre luces y sombras, conocido como técnica del claroscuro.",
		A: "V",
		B: "II",
		C: "I",
		D: "IV",
		E: "III",
		Correct: "B"
	},
	{
		name: "2016iiCE5",
		subject: "Literature",
		sub_subject: "Sentence Elimination",
		prompt: "2016iiCE3-5",
		image: false,
		question: "(I) La desertificación en África se produce principalmente dentro de las áreas circundantes al desierto del Sahara. (II) La economía africana no se ha desarrollado a causa de la inestabilidad política y la dependencia financiera. (III) La producción africana se dirige hacia el mercado externo, por lo que no se orienta a satisfacer las necesidades de su población. (IV) En África predominan las actividades económicas extractivas, lo que acarrea, con frecuencia, una depredación del medio. (V) En el continente africano, conviven dos tipos de economía: una de subsistencia y otra dirigida al comercio internacional.",
		A: "V",
		B: "IV",
		C: "I",
		D: "III",
		E: "II",
		Correct: "C"
	},
	{
		name: "2016iiCE6-10",
		subject: "Literature",
		sub_subject: "Reading Comprehension",
		prompt: 'Lo que llegó a conocerse como, frenología fue fundada por Franz Joseph Gall a finales del siglo XVIII en Europa, donde gozó de un gran éxito en los círculos intelectuales de Viena/ Weimar y París. La frenología surgió como una curiosa mezcolanza de psicología temprana, neurociencia temprana y filosofía práctica. Tuvo una notable influencia en la ciencia y en las humanidades, a lo largo de la mayor parte del siglo XIX.<br> Algunas de las ideas de Gall fueron en realidad muy sorprendentes para la época. En términos que no eran nada dudosos, afirmó que el cerebro era el órgano del espíritu. Con no menos seguridad, aseveró que el cerebro era un agregado de muchos órganos, cada uno de los cuales poseía una facultad psicológica específica. No solo se distanció del pensamiento dualista preferido, que separaba completamente la biología de la mente, sino que intuyó, correctamente, que había muchas partes en esta cosa llamada cerebro, y que existía especialización en términos de las funciones que dichas partes desempeñaban. Sin embargo, no se dio cuenta de que la función de cada parte diferenciada del cerebro no es independiente y que, en cambio, es una contribución a la función de sistemas mayores compuestos por estas partes separadas. La neurociencia contemporánea puede decir con seguridad que no existen “centros” únicos para la visión o el lenguaje.<br>Aunque hemos de conceder a Gall el mérito del concepto de la especialización cerebral, debemos reprocharle la noción de “centros” cerebrales que inspiró. También hemos de ser críticos con varias afirmaciones absurdas de la frenología, por ejemplo la idea de que cada “órgano” cerebral separado generaba facultades mentales que eran proporcionales al tamaño del órgano, o que todos los órganos y facultades eran innatos.<br>La noción del tamaño como índice del “poder” o de la “energía” de una determinada facultad mental es graciosamente errónea. La extensión de esta afirmación, la que en mayor medida contribuyó a arruinar la frenología (y en la que mucha gente piensa cuando oye el término), era que los órganos podían identificarse desde el exterior por protuberancias reveladoras en el cráneo.<br><font size="2">Damasio, A. (2011). <i>El error de Descartes</i>. Barcelona: Ediciones Destino.</font>',
		image: false,
		question: "El sentido del adjetivo PREFERIDO es",
		A: "querido.",
		B: "privilegiado.",
		C: "mayoritario.",
		D: "predominante.",
		E: "estimado.",
		Correct: "D"
	},
	{
		name: "2016iiCE7",
		subject: "Literature",
		sub_subject: "Reading Comprehension",
		prompt: "2016iiCE6-10",
		image: false,
		question: "El autor se refiere, principalmente,",
		A: "a las intuiciones acertadas y los errores de la frenología de Gall.",
		B: "a la influencia de la frenología en la neurociencia del siglo XX.",
		C: "al fracaso de la frenología como una nueva ciencia del cerebro.",
		D: "a la crítica de la frenología al pensamiento psicológico dualista.",
		E: "al mérito del concepto frenológico de especialización cerebral.",
		Correct: "C"
	},
	{
		name: "2016iiCE8",
		subject: "Literature",
		sub_subject: "Reading Comprehension",
		prompt: "2016iiCE6-10",
		image: false,
		question: "¿Cuál de los siguientes enunciados es incompatible con lo aseverado en el texto?",
		A: "La frenología tuvo una influencia intelectual significativa a lo largo del siglo XIX.",
		B: "El enfoque dualista de la frenología sostuvo la separación del cerebro y la mente.",
		C: "Gall afirmaba que las facultades mentales dependían del tamaño de los órganos.",
		D: "Para la frenología, el cerebro es un agregado de órganos con distintas facultades.",
		E: "Gall sostuvo que los órganos eran identificables por protuberancias en el cráneo.",
		Correct: "A"
	},
	{
		name: "2016iiCE9",
		subject: "Literature",
		sub_subject: "Reading Comprehension",
		prompt: "2016iiCE6-10",
		image: false,
		question: "De acuerdo con la frenología de Gall, se infiere que habría proporcionalidad entre cerebro y mente, pues",
		A: "las protuberancias en el cráneo mostraban una carencia de inteligencia.",
		B: "los órganos cerebrales diferenciados tenían dimensiones diferentes.",
		C: "el tamaño del órgano cerebral indicaba el poder de una facultad mental.",
		D: "la creencia metafísico-religiosa en un espíritu había sido abandonada.",
		E: "las funciones mentales de cada órgano cerebral separado eran innatas.",
		Correct: "C"
	},
	{
		name: "2016iiCE10",
		subject: "Literature",
		sub_subject: "Reading Comprehension",
		prompt: "2016iiCE6-10",
		image: false,
		question: "Si Gell hubiera rechazado la idea de la independencia de las funciones de cada órgano cerebral, entonces",
		A: "la frenología habría sido reemplazada por la parapsicología.",
		B: "la frenología habría sido reemplazada por la parapsicología.",
		C: "la influencia de la frenología en el siglo XIX habría sido menor.",
		D: "habría inventado un nuevo método de medición del cráneo.",
		E: "podría haber sentado las bases de la neurociencia del siglo XX.",
		Correct: "E"
	},
	{
		name: "2016iiCE11-15",
		subject: "Literature",
		sub_subject: "Reading Comprehension",
		prompt: 'El gobierno del presidente Ollanta Humala, un militar en retiro, ha multiplicado hasta por doce veces el gasto en defensa en los casi cinco años de su gestión, y este 2016 el presupuesto que deja para el sector es igual de significativo.<br>La inversión pública en el sector Defensa, que además de desarrollo de infraestructura comprende equipamiento (armas), Pasó de casi S/ 1500 millones en el 2014 a poco más de S/ 3000 millones en el 2015, es decir, se duplicó en tan solo un año.<br>Pero al observar las cifras de los últimos cinco años, se puede ver que el gasto en inversión militar creció exponencialmente en esta gestión, al pasar de S/. 246 millones en el 2011 a más de S/ 3000 millones al 2015.<br>Incluso, el sector Defensa concentró el 20% de la ejecución de inversión pública durante el 2015, solo por debajo de Transportes y Comunicaciones (39%), que justifica su gasto en proyectos viales, según cifras del Ministerio de Economía y Finanzas.<br>Y para este año, la ley de presupuesto incrementa en 10% el gasto fiscal en acciones relacionadas a la seguridad nacional, “con el fin de que las fuerzas armadas colaboren con los planes de emergencia durante el fenómeno de El Niño”.<br>Dadas las características del sector Defensa (seguridad nacional), se conoce muy poco sobre el detalle de las adquisiciones del Gobierno en materia militar, pero el presidente del Consejo de Ministros, Pedro Cateriano, emplazó a los críticos a mostrar pruebas de presuntas irregularidades en la compra de armamento.<br><font size="2">Omar, M. (7 de enero del 2016) Gasto militar se multiplicó por doce en últimos cinco años. Gestión. Recuperado de http://gestion.peteconomiatgasto-militar-se-multiplico-12-ultimos-cinco- anos-2152203.</font>',
		image: false,
		question: "El texto tiene como finalidad",
		A: "hacer una crítica al Gobierno con la intención de que este justifique por qué hay incremento en Defensa.",
		B: "emplazar al gobierno de Ollanta Humala sobre el incremento injustificado y exorbitante en el sector Defensa.",
		C: "informar sobre el aumento desproporcionado del gasto en el sector Defensa durante el presente Gobierno.",
		D: "cuestionar el incremento del sector Defensa apelando a los vínculos castrenses del jefe de gobierno.",
		E: "presentar un incremento en el presupuesto del sector Defensa y plantear las necesidades que lo justifican.",
		Correct: "C"
	},
	{
		name: "2016iiCE12",
		subject: "Literature",
		sub_subject: "Reading Comprehension",
		prompt: "2016iiCE11-15",
		image: false,
		question: "A partir de las cifras de los porcentajes de los incrementos interanuales en el sector Defensa, se puede señalar que",
		A: "el incremento del quinquenio pasado fue del 398%.",
		B: "los pertrechos de guerra se han renovado en su totalidad.",
		C: "los contratos firmados no parecen muy convenientes.",
		D: "su variación no ha mantenido una proporción constante.",
		E: "el incremento en soles fue mayor entre el 2011 y el 2012.",
		Correct: "D"
	},
	{
		name: "2016iiCE13",
		subject: "Literature",
		sub_subject: "Reading Comprehension",
		prompt: "2016iiCE11-15",
		image: false,
		question: "En virtud de la información proporcionada en ambos cuadros, y a pesar de no estar viviendo una posibilidad de enfrentamiento bélico, se puede sostener que",
		A: "nuestros países vecinos han incrementado sus gastos en Defensa.",
		B: "los contratos con los abastecedores del sector son millonarios.",
		C: "el Gobierno está muy interesado en potenciar el sector Defensa.",
		D: "el Gobierno es inocente hasta que se pruebe lo contrario.",
		E: "Defensa posee un valor intrínseco mayor que Educación.",
		Correct: "C"
	},
	{
		name: "2016iiCE14",
		subject: "Literature",
		sub_subject: "Reading Comprehension",
		prompt: "2016iiCE11-15",
		image: false,
		question: "A partir de la ejecución de la inversión pública en el 2015 y de la justificación que proporciona el Estado sobre su distribución, se puede concluir que",
		A: "existe una evidente voluntad de favorecer al sector Defensa tomando como excusa el fenómeno de El Niño.",
		B: "la inversión en Transportes y Comunicaciones se justifica en virtud de la llegada del fenómeno de El Niño.",
		C: "la necesidad de interconectar las diferentes zonas de nuestro país es una tarea prioritaria para vivir bien.",
		D: "en la planificación de los presupuestos sectoriales se toma en consideración una serie de eventualidades.",
		E: "por seguridad nacional se debe considerar tanto la amenaza de un agente externo como la de uno interno.",
		Correct: "D"
	},
	{
		name: "2016iiCE15",
		subject: "Literature",
		sub_subject: "Reading Comprehension",
		prompt: "2016iiCE11-15",
		image: false,
		question: "Para llegar a la respuesta de la pregunta anterior, fue necesario considerar",
		A: "el pasado militar del actual presidente.",
		B: "que las carreteras pueden verse afectadas.",
		C: "que los peruanos tenemos iguales derechos.",
		D: "que el fenómeno de El Niño es recurrente.",
		E: "el dato sobre el fenómeno de El Niño.",
		Correct: "E"
	},
	{
		name: "2016iiCE16-20",
		subject: "Literature",
		sub_subject: "Reading",
		prompt: '<b>TEXTO A</b><br>Todo lo que hasta ahora he admitido como lo más verdadero, lo he recibido de los sentidos o por lo sentidos; sin embargo, me he dado cuenta de que estos se equivocan, y es propio de la prudencia no confiar nunca plenamente en quienes, aunque sea una vez, nos han engañado. Por esto me veo obligado a confesar que no hay nada de lo que antes juzgaba como verdadero, de lo que no sea lícito dudar, y esto no por falta de consideración o ligereza, sino por razones válidas y meditadas; y por lo tanto, si quiero encontrar algo cierto, debo en adelante negarles mi asentimiento también a estas cosas, no menos que a las abiertamente falsas (...) De tal manera me he acostumbrado así a desprender mi espíritu de los sentidos, y he notado con tanta exactitud que hay muy pocas cosas que se conozcan con certeza en lo tocante a las cosas corporales (...) por lo que ahora apartaré sin dificultad alguna mis pensamientos de la consideración de las cosas sensibles o imaginables, para dirigirlos hacia aquellas que, estando desprovistas de toda materia, son puramente inteligibles.<br><font size="2">(DESCARTES, R., <i>Meditaciones metafísicas</i>, adaptado)</font><br><b>TEXTO B</b><br>Al principio, los sentidos aprehenden ideas particulares y abastecen el depósito todavía vacío de nuestra mente con algunas de ellas a las que nombra y conserva en la memoria. Después, la mente las abstrae y, mediante un modo gradual, aprende el uso de los nombres generales. De esta manera, la mente se surte de ideas y de lenguaje (nombres), materiales sobre los que ejerce su facultad discursiva; y el uso de la razón se hace más visible a medida que aumentan estos materiales que permiten su empleo. Si bien las ideas generales y el uso de las palabras generales y de la razón crecen juntamente, sin embargo, esto no indica que tales ideas sean innatas. Admito que el conocimiento de algunas verdades aparece en la mente en una edad muy temprana, pero se trata de ideas no innatas sino adquiridas, ya que se refieren a esas primeras ideas impresas por aquellas cosas externas en las que primero se ocupan los niños, y que se imprimen en sus sentidos más fuertemente.<br><font size="2">(LOCKE, J., <i>Ensayo sobre el entendimiento humano</i>, adaptado)</font>',
		image: false,
		question: "En el texto A, el adverbio ABIERTAMENTE se puede reemplazar por",
		A: "notoriamente.",
		B: "ampliamente.",
		C: "extensamente.",
		D: "francamente.",
		E: "sinceramente.",
		Correct: "A"
	},
	{
		name: "2016iiCE17",
		subject: "Literature",
		sub_subject: "Reading Comprehension",
		prompt: "2016iiCE16-20",
		image: false,
		question: "John Locke se refiere, principalmente,",
		A: "a la imposibilidad de un conocimiento indudable por los límites de la naturaleza humana.",
		B: "a la fuente original de donde proceden las verdades indiscutibles obtenidas por los sentidos.",
		C: "al modo como la razón se desarrolla a partir de ideas y nombres que adquiere por los sentidos.",
		D: "al cuestionamiento de todo el saber anterior surgido por medio de los sentidos y la memoria.",
		E: "al malentendido que sostiene que las ideas innatas son verdades impresas en la mente.",
		Correct: "C"
	},
	{
		name: "2016iiCE18",
		subject: "Literature",
		sub_subject: "Reading Comprehension",
		prompt: "2016iiCE16-20",
		image: false,
		question: "Uno de los siguientes enunciados es incompatible con lo aseverado por Descartes.",
		A: "Las cosas materiales propias del mundo externo son las más fáciles de conocer.",
		B: "La prudencia aconseja desconfiar de aquello que nos ha engañado anteriormente.",
		C: "Todo lo que hemos admitido hasta hoy como verdadero proviene de los sentidos.",
		D: "Existen razones válidas para dudar de todo lo que anteriormente hemos conocido.",
		E: "Debemos dirigir nuestro pensamiento hacia las cosas puramente inteligibles.",
		Correct: "A"
	},
	{
		name: "2016iiCE19",
		subject: "Literature",
		sub_subject: "Reading Comprehension",
		prompt: "2016iiCE16-20",
		image: false,
		question: "Sobre la propuesta de Locke de que la razón surge a partir de las aprehensiones sensibles tempranas, Descartes la objetaría con su tesis de que",
		A: "todo lo que usualmente admitimos como verdadero lo recibimos vía los sentidos.",
		B: "la certeza del conocimiento radica en lo inteligible antes que en las sensaciones.",
		C: "es prudente y conveniente desconfiar de las personas que dudan o nos engañan.",
		D: "la duda no debe ser resultado de ligereza o descuido, sino de cautelosa reflexión.",
		E: "conviene desprender el espíritu de los sentidos con el fin de dudar cada vez menos.",
		Correct: "B"
	},
	{
		name: "2016iiCE20",
		subject: "Literature",
		sub_subject: "Reading Comprehension",
		prompt: "2016iiCE16-20",
		image: false,
		question: "En lo que al papel de las sensaciones en el conocimiento se refiere, Descartes y Locke difieren en que para el primero ellas son ________ y para el segundo son __________",
		A: "primarias — prescindibles",
		B: "fundamentales — irrelevantes",
		C: "primarias — relevantes",
		D: "secundarias — imprescindibles",
		E: "derivadas — secundarias",
		Correct: "D"
	},
	{
		name: "2016iiCE21",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "Sabiendo que:<br>Halle:",
		A: "94",
		B: "82",
		C: "74",
		D: "92",
		E: "84",
		Correct: "E"
	},
	{
		name: "2016iiCE22",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "Un empleado minero trabaja 5 días seguidos y descansa los 3 días siguientes. Si inicia su trabajo un martes, ¿cuántos días tendrá que trabajar para que pueda descansar por primera vez viernes, sábado y domingo, consecutivamente?",
		A: "40",
		B: "30",
		C: "25",
		D: "45",
		E: "35",
		Correct: "B"
	},
	{
		name: "2016iiCE23",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "Cercar un área de 1 \\(\\mathrm{x^2}\\) cuesta 40 soles. Hacer lo mismo con un área de 4 \\(\\mathrm{m^2}\\) requiere de 120 soles; con un área de 9 \\(\\mathrm{x^2}\\), 240 soles; y con un área de 16 \\(\\mathrm{x^2}\\) , 400 soles. ¿Cuánto costará cercar 36 \\(\\mathrm{x^2}\\)?",
		A: "640 soles",
		B: "600 soles",
		C: "740 soles",
		D: "880 soles",
		E: "840 soles",
		Correct: "E"
	},
	{
		name: "2016iiCE24",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "La suma de 6 números enteros es un número par. De estos números, el producto de los 4 primeros es impar y el sexto es par. De acuerdo con estos datos, elija la alternativa que contenga enunciados verdaderos.<br>I. El quinto número es par.<br>II. El quinto número es impar.<br>III. El producto de los 6 números es par.<br>IV. El tercer número es impar.",
		A: "II y IV",
		B: "Solo III",
		C: "Solo I",
		D: "I, III y IV",
		E: "I, III y IV",
		Correct: "E"
	},
	{
		name: "2016iiCE25",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: true,
		question: "Halle el valor numérico de x en la siguiente secuencia.",
		A: "42",
		B: "52",
		C: "48",
		D: "56",
		E: "54",
		Correct: "B"
	},
	{
		name: "2016iiCE26",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "Si un bloque de concreto se equilibra con 3/4 del mismo bloque más una pesa de \\(3\\frac{1}{4}\\) de kilo, y el costo por kilo de un bloque de concreto es de S/ 0,50, ¿cuánto cuesta cada bloque?",
		A: "S/ 6,00",
		B: "S/ 5,50",
		C: "S/ 6,50",
		D: "S/ 7,50",
		E: "S/ 7,00",
		Correct: "C"
	},
	{
		name: "2016iiCE27",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "En un poblado con 120 familias, se observó que 57 de ellas tienen agua, 52 cuentan con luz y 25 no poseen ninguno de estos servicios básicos. ¿Cuántas familias poseen ambos servicios?",
		A: "14",
		B: "15",
		C: "10",
		D: "16",
		E: "13",
		Correct: "A"
	},
	{
		name: "2016iiCE28",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "En una granja, la reproducción de cuyes es trimestral y cada pareja reproduce 4 cuyes que forman pareja. Si la reproducción comienza con una pareja de cuyes y no muere ninguno, ¿después de cuántos meses se contará con 9 parejas de cuyes en total?",
		A: "3 meses",
		B: "12 meses",
		C: "6 meses",
		D: "15 meses",
		E: "9 meses",
		Correct: "C"
	},
	{
		name: "2016iiCE29",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "Si M es el promedio de 6 números enteros consecutivos y N es el promedio del menor y mayor de estos números, ¿qué relación existe entre M y N?",
		A: "M < N",
		B: "M = 2N",
		C: "M > N",
		D: "M = \\(\\mathrm{\\frac{N}{2}}\\)",
		E: "M = N",
		Correct: "E"
	},
	{
		name: "2016iiCE30",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "Un depósito tiene tres llaves. La llave A puede llenarlo en 3 minutos, la llave B puede hacerlo en 6 minutos y la llave del desagüe puede vaciarlo en 18 minutos.<br>Si el depósito se encuentra vacío y el desagüe abierto, ¿en cuánto tiempo se llenará el depósito si se abren simultáneamente las llaves A y B?",
		A: "\\(\\frac{5}{2}\\) min",
		B: "2 min",
		C: "\\(\\frac{9}{4}\\) min",
		D: "\\(\\frac{11}{4}\\) min",
		E: "3 min",
		Correct: "C"
	},
	{
		name: "2016iiCE31",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "Se realiza dos cortes a un alambre en posición horizontal y resulta que cada trozo mide el cuádruple del anterior. Si la diferencia de las longitudes de los dos trozos menores es 60 cm, ¿cuánto mide el alambre?",
		A: "210 cm",
		B: "480 cm",
		C: "520 cm",
		D: "420 cm",
		E: "400 cm",
		Correct: "D"
	},
	{
		name: "2016iiCE32",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "Halle el área de la región sombreada si (\\(\\mathscr{C}\\) es la circunferencia de centro en el punto C (0,1) y es tangente al eje x.",
		A: "\\(\\mathrm{(4-\\frac{\\pi}{2})u^2}\\)",
		B: "\\(\\mathrm{(2-\\frac{\\pi}{2})u^2}\\)",
		C: "\\(\\mathrm{(1-\\frac{\\pi}{4})u^2}\\)",
		D: "\\(\\mathrm{(3-\\frac{\\pi}{4})u^2}\\)",
		E: "\\(\\mathrm{(1-\\frac{\\pi}{2})u^2}\\)",
		Correct: "C"
	},
	{
		name: "2016iiCE33",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "En el triángulo ABC se tiene que AB = BC y la longitud de la base AC es igual a la altura que parte del vértice B. Si las coordenadas de los puntos A y C son (3, 2) y (7, 2), respectivamente, ¿cuáles son las coordenadas del punto medio de BC?",
		A: "(7,4)",
		B: "(6,3)",
		C: "(5,5)",
		D: "(6,4)",
		E: "(6,5)",
		Correct: "D"
	},
	{
		name: "2016iiCE34",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "En determinado transporte público, solo existe el pasaje adulto y el medio pasaje. El pasaje adulto vale S/ 1,50 y el medio pasaje S/ 0,80. Si durante un tiempo t de recorrido se recaudó S/ 23,50 y, además, se cobró más pasajes adultos que medios pasajes, ¿cuántos pasajeros pagantes subieron durante el tiempo t?",
		A: "25",
		B: "22",
		C: "17",
		D: "19",
		E: "18",
		Correct: "E"
	},
	{
		name: "2016iiCE35",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "Miguel dibujó la gráfica de una función f, la cual está formada (de izquierda a derecha) por la recta y = x + 3 con x < -1 y los segmentos AB y BC. Halle la suma de las soluciones que tiene la ecuación f(f(x)) = 0",
		A: "10",
		B: "-8",
		C: "12",
		D: "-6",
		E: "-16",
		Correct: "D"
	},
	{
		name: "2016iiCE36",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura se tiene un envase cúbico de arista \\(\\mathscr{l}\\) = \\(\\mathrm{3\\sqrt{2}}\\) cm. Halle la distancia del vértice E a la diagonal \\(\\mathrm{\\overline{AC}}\\) de la tapa ABCD.",
		A: "\\(4\\sqrt{3}\\) cm",
		B: "\\(5\\sqrt{2}\\) cm",
		C: "\\(3\\sqrt{3}\\) cm",
		D: "3 cm",
		E: "10 cm",
		Correct: "C"
	},
	{
		name: "2016iiCE37",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "Una tubería debe atravesar diagonalmente un terreno rectangular de 50 m2 de área, cuyo largo es el doble de su ancho. Determine la longitud de la tubería.",
		A: "\\(3\\sqrt{3}\\) m",
		B: "\\(3\\sqrt{5}\\) c",
		C: "\\(5\\sqrt{3}\\) m",
		D: "6 m",
		E: "\\(5\\sqrt{5}\\) m",
		Correct: "E"
	},
	{
		name: "2016iiCE38",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "Un hombre, un árbol y un faro se encuentran ubicados como se muestra en la figura. Si el hombre mide 1,82 m y el árbol mide 3,32 m, ¿cuál es la altura del faro?",
		A: "90 m",
		B: "91,82 m",
		C: "91,25 m",
		D: "91,89 m",
		E: "92,82 m",
		Correct: "B"
	},
	{
		name: "2016iiCE39",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "aneth tiene un terreno como se muestra en la figura, el cual está conformado por una semicircunferencia y cuatro rectángulos congruentes situados alrededor del cuadrado ABCD. Si la región ABCD tiene un área de 144 \\(\\mathrm{m^2}\\) y cada rectángulo y el cuadrado ABCD tienen igual perímetro, halle el área del semicírculo.",
		A: "\\(62\\pi\\) \\(\\mathrm{m^2}\\)",
		B: "\\(68\\pi\\) \\(\\mathrm{m^2}\\)",
		C: "\\(64\\pi\\) \\(\\mathrm{m^2}\\)",
		D: "\\(84\\pi\\) \\(\\mathrm{m^2}\\)",
		E: "\\(72\\pi\\) \\(\\mathrm{m^2}\\)",
		Correct: "E"
	},
	{
		name: "2016iiCE40",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "Un rectángulo de papel de vértices ABCD de 24 cm de largo por 8 cm de ancho se dobla de tal manera que, al unir el vértice C con el vértice A, forma la figura que se muestra. A partir de esos datos, determine el área de la región sombreada.",
		A: "100 \\(\\mathrm{cm^2}\\)",
		B: "96 \\(\\mathrm{cm^2}\\)",
		C: "48 \\(\\mathrm{cm^2}\\)",
		D: "108 \\(\\mathrm{cm^2}\\)",
		E: "64 \\(\\mathrm{cm^2}\\)",
		Correct: "B"
	},
	{
		name: "2016iiCE41",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "Sea 1, 4, 9, 16, ... la sucesión de los cuadrados de los enteros positivos. Si el número \\(8^10\\) es un término de esta sucesión, ¿cuál es el término de la sucesión que sigue después de \\(8^10\\)?",
		A: "\\((8^{10}+1)^2\\)",
		B: "\\((8^{6})^2\\)",
		C: "\\((8^{10})^3\\)",
		D: "\\((8^{5}+1)^2\\)",
		E: "\\((8^{5})^2+1\\)",
		Correct: "D"
	},
	{
		name: "2016iiCE42",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "Una bolsa contiene 2 bolas negras, 3 bolas blancas, 4 bolas rojas y 5 bolas verdes. Si se extrae al azar una bola de la bolsa, determine la probabilidad de que la bola extraída sea de color negro.",
		A: "\\(\\frac{1}{7}\\)",
		B: "\\(\\frac{1}{6}\\)",
		C: "\\(\\frac{3}{8}\\)",
		D: "\\(\\frac{2}{7}\\)",
		E: "\\(\\frac{1}{9}\\)",
		Correct: "A"
	},
	{
		name: "2016iiCE43",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "Julio debe multiplicar un número por 40, pero cometió un error y lo multiplicó por 4, por lo que su resultado difiere del valor correcto en 7740. Halle dicho número.",
		A: "220",
		B: "215",
		C: "180",
		D: "200",
		E: "195",
		Correct: "B"
	},
	{
		name: "2016iiCE44",
		subject: "Mathematics",
		sub_subject: "Logic",
		prompt: false,
		image: false,
		question: "¿Cuáles de las siguientes afirmaciones son verdaderas para todo a \\(\\in\\Re\\), a \\(\\neq\\) 0?<br>I. \\(\\mathrm{a^2 + \\frac{1}{a^2}\\ge2}\\)<br>II. \\(\\mathrm{a^2 + \\frac{1}{a^2}\\lt2}\\)<br>III. \\(\\mathrm{a^2 + \\frac{1}{a}\\ge2}\\)<br>IV. \\(\\mathrm{a^2 - a}\\gt2\\)",
		A: "Solo II",
		B: "I y IV",
		C: "Solo I",
		D: "II y III",
		E: "I y III",
		Correct: "C"
	},
	{
		name: "2016iiCE45",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Dado el systema<br>$$\\begin{cases}x+y = 0\\\\2y+x=-5\\\\-x+z=-3\\end{cases}$$<br>Halle el valor de x+y+z. ",
		A: "1",
		B: "0",
		C: "2",
		D: "-1",
		E: "-2",
		Correct: "D"
	},
	{
		name: "2016iiCE46",
		subject: "KM",
		sub_subject: "Algebra",
		prompt: false,
		image: false,
		question: "Si se sabe que el conjunto solución de la inecuación \\(\\frac{3x - 2}{2x -3}\\lt 0\\) es un intervalo de la forma <a,b>, determina el valor de b-a",
		A: "\\(\\frac{13}{6}\\)",
		B: "\\(\\frac{5}{6}\\)",
		C: "\\(\\frac{5}{2}\\)",
		D: "\\(\\frac{3}{2}\\)",
		E: "\\(\\frac{2}{3}\\)",
		Correct: "B"
	},
	{
		name: "2016iiCE47",
		subject: "KM",
		sub_subject: "Algebra",
		prompt: false,
		image: false,
		question: "Sean x e y dos números positivos que satisfacen las condiciones<br> \\(\begin{cases}\\sqrt{xy} = 0\\\\\\sqrt{x} - \\sqrt{y} = 8\end{cases}\\)<br>determina el valor de \\(\\sqrt{x + y}\\)",
		A: "10",
		B: "\\(\\sqrt{8}\\)",
		C: "9",
		D: "\\(\\sqrt{18}\\)",
		E: "\\(\\sqrt{10}\\)",
		Correct: "A"
	},
	{
		name: "2016iiCE48",
		subject: "KM",
		sub_subject: "Algebra",
		prompt: false,
		image: false,
		question: "Dados los polinomios P(x)=\\(\\mathrm{x^5}\\)+c y Q(x)=x+1, donde c es un número real, halle la suma de los coeficientes del polinomio cociente de P(x) entre Q(x).",
		A: "c",
		B: "-1",
		C: "2",
		D: "1",
		E: "-c",
		Correct: ""
	},
	{
		name: "2016iiCE49",
		subject: "KM",
		sub_subject: "Geometry",
		prompt: false,
		image: false,
		question: "En la figura, ABC es un triángulo isósceles cuya áreaesde 12 \\(\\mathrm{m^2}\\) y su altura \\(\\mathrm{\\overline{BM}}\\) mide 4 m. Halle el perímetro de dicho triángulo.",
		A: "14 m",
		B: "12 m",
		C: "16 m",
		D: "18 m",
		E: "20 m",
		Correct: "C"
	},
	{
		name: "2016iiCE50",
		subject: "KM",
		sub_subject: "Geometry",
		prompt: false,
		image: false,
		question: "El número de pulgadas de un televisor indica la longitud de la diagonal de su pantalla. En un modelo de pantalla plana de 20 pulgadas, como el que se muestra en la figura, se sabe que las dimensiones de la pantalla tienen una relación de 3 a 4. Determine sus dimensiones.",
		A: "9 y 12 pulgadas",
		B: "15 y 20 pulgadas",
		C: "12 y 18 pulgadas",
		D: "18 y 24 pulgadas",
		E: "12 y 16 pulgadas",
		Correct: "E"
	},
	{
		name: "2016iiCE51",
		subject: "KM",
		sub_subject: "Geometry",
		prompt: false,
		image: false,
		question: "Halle el área del triángulo que forma la recta \\(\\mathscr{L}\\): 3x–4y=12 con los ejes coordenados.",
		A: "6 \\(\\mathrm{u^2}\\)",
		B: "4 \\(\\mathrm{u^2}\\)",
		C: "4,5 \\(\\mathrm{u^2}\\)",
		D: "8 \\(\\mathrm{u^2}\\)",
		E: "5 \\(\\mathrm{u^2}\\)",
		Correct: "A"
	},
	{
		name: "2016iiCE52",
		subject: "KM",
		sub_subject: "Geometry",
		prompt: false,
		image: false,
		question: "Sea ABC un triángulo rectángulo, recto en B, donde m\\(\\newcommand{arc}[1]{\\stackrel{\\frown}{#1}}\\arc{A}\\) = 30° y el cateto que se le opone mide 12 m. Se traza la mediana \\(\\mathrm{\\overline{BM}}\\) y se consideran las proyecciones \\(\\mathrm{\\overline{RB}}\\) y \\(\\mathrm{\\overline{BT}}\\) de \\(\\mathrm{\\overline{BM}}\\) sobre los catetos. Halle el perímetro del polígono MRBT.",
		A: "10(\\(\\sqrt(3) + 2\\)) m",
		B: "12(\\(\\sqrt(3) + 1\\)) m",
		C: "12(\\(\\sqrt(3) + 3\\)) m",
		D: "10(\\(\\sqrt(3) + 1\\)) m",
		E: "11(\\(\\sqrt(3) + 2\\)) m",
		Correct: "B"
	},
	{
		name: "2016iiCE53",
		subject: "KM",
		sub_subject: "Trigonometry",
		prompt: false,
		image: false,
		question: "Se sabe que ctg(θ) = –0,75 y cos(θ) < 0. Determine el valor de la expresión: 5sen(θ)+3sec(θ)+1",
		A: "\\(\\frac{13}{15}\\)",
		B: "\\(-\\frac{37}{15}\\)",
		C: "1",
		D: "0",
		E: "-1",
		Correct: "D"
	},
	{
		name: "2016iiCE54",
		subject: "KM",
		sub_subject: "Trigonometry",
		prompt: false,
		image: false,
		question: "Sea el triángulo rectángulo ABC, recto en B y \\(a\\) uno de los ángulos agudos del triángulo. Si tg \\(a\\) = \\(\\frac{4}{3}\\), halle el valor de la expresión \\(\\frac{\\cos a - \\textrm{sec }a}{\\csc a - \\sec a}\\)",
		A: "\\(\\frac{12}{25}\\)",
		B: "\\(\\frac{25}{12}\\)",
		C: "\\(\\frac{13}{25}\\)",
		D: "\\(\\frac{25}{13}\\)",
		E: "1",
		Correct: "A"
	},
	{
		name: "2016iiCE55",
		subject: "KM",
		sub_subject: "Trigonometry",
		prompt: false,
		image: false,
		question: "Con un teodolito de 1,5m de altura, se observa la cima de un árbol con un ángulo de elevación de 60°. Si el teodolito se aleja ^ 3 - 1hm del árbol, siguiendo una trayectoria lineal en la dirección descrita por su posición inicial y el pie del árbol, el nuevo ángulo de elevación es 450. Calcule la altura del árbol.",
		A: "\\(\\sqrt{3}\\) m",
		B: "(\\(2\\sqrt{3} + \\textrm{1,5}\\)) m",
		C: "\\(\\sqrt{5}\\) m",
		D: "(\\(\\sqrt{2} + \\textrm{1,5}\\)) m",
		E: "(\\(\\sqrt{3} + \\textrm{1,5}\\)) m",
		Correct: "E"
	},
	{
		name: "2016iiCE56",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "<i>Daniel le dijo a Josué que la reunión había cambiado de fecha, pero este no le entendió porque se encontraba distraído.</i> En el enunciado anterior, la situación comunicativa evidencia un problema en el",
		A: "canal.",
		B: "código.",
		C: "emisor.",
		D: "receptor.",
		E: "referente.",
		Correct: "D"
	},
	{
		name: "2016iiCE57",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Muchas palabras llevan tilde no por las reglas generales de acentuación ortográfica, sino por hiato acentual. Señale la alternativa que presenta más hiatos acentuales.",
		A: "Habíamos leído una nueva teoría.",
		B: "Raúl decidió participar en la reunión.",
		C: "Enviarán los documentos vía aérea.",
		D: "Vestía prendas con cuero muy raído.",
		E: "Creyó que ella estudiaría filosofía",
		Correct: "A"
	},
	{
		name: "2016iiCE58",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Elija la opción que muestra el uso correcto de los dos puntos.",
		A: "Las escuelas vanguardistas son: futurismo y surrealismo.",
		B: "Dos son los ejes de su genial obra: fantasía e individualismo.",
		C: "Perdió el autobús; llegó tarde: a la entrega de su constancia.",
		D: "La letra de canción decía que: Guadalajara era hermosa.",
		E: "La secretaria nos entregó: reglas, clips, grapas y lapiceros.",
		Correct: "B"
	},
	{
		name: "2016iiCE59",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Seleccione la alternativa en la que se aplique correctamente la concordancia.",
		A: "Se reunirá contigo el jefe y también el administrador.",
		B: "Fue innecesario tantos trámites para esta adquisición.",
		C: "Una jauría de perros atacaron a los niños de la escuela.",
		D: "Nos asesoraron en el proyecto el director y el experto.",
		E: "Tanto Roberto como su hermano asistió a la reunión.",
		Correct: "D"
	},
	{
		name: "2016iiCE60",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Elija el enunciado donde el prefijo re- denote repetición.",
		A: "Los estudiantes releían amenamente el libro de poemas.",
		B: "Los niños se remangan la camisa para limpiar el baño.",
		C: "El ayo recogía siempre los juguetes de los párvulos.",
		D: "El abogado reculaba ante los argumen- tos contrarios.",
		E: "Ahora los jóvenes recelaban de las pa- labras melosas.",
		Correct: "A"
	},
	{
		name: "2016iiCE61",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "<i>Tres hombres llegaron a la comisaría y todos dijeron que se habían casado con la misma mujer, razón por la cual esta última fue denunciada por poliandria</i>. De lo anterior se infiere que poliandra es una mujer",
		A: "que se comporta de manera liberal y licenciosa.",
		B: "acusada de ser muy promiscua en la sociedad.",
		C: "casada simultáneamente con varios hombres.",
		D: "censurada por la comunidad en su conjunto.",
		E: "que actúa con felonía en todo momento y lugar.",
		Correct: "C"
	},
	{
		name: "2016iiCE62",
		subject: "Language",
		sub_subject: "Language",
		prompt: false,
		image: false,
		question: "En el enunciado Aprobaste el examen, <b>puesto que</b> estudiaste con rigor; <b>de modo que</b> recibirás un premio sustantivo, los conectores subrayados son, respectivamente, de índole",
		A: "concesiva e ilativa.",
		B: "causal y consecutiva.",
		C: "rectificativa y aditiva.",
		D: "ejemplificativa y final.",
		E: "argumentativa y explicativa.",
		Correct: "B"
	},
	{
		name: "2016iiCE63",
		subject: "Literature",
		sub_subject: "Literature",
		prompt: false,
		image: false,
		question: "El __________ es un estilo de la novela latinoamericana que se caracteriza por presentar lo ordinario como extraordinario y lo prodigioso como cotidiano. Su mayor representante es __________.",
		A: "realismo mágico — Gabriel García Márquez",
		B: "real maravilloso — Mario Vargas Llosa",
		C: "regionalismo — Rómulo Gallegos",
		D: "realismo mágico — Julio Cortázar",
		E: "indigenismo — Ciro Alegría",
		Correct: "A"
	},
	{
		name: "2016iiCE64",
		subject: "Literature",
		sub_subject: "Literature",
		prompt: false,
		image: false,
		question: "Determine el valor de verdad (V) o falsedad (F) de los siguientes enunciados relativos a la llíada y a la Odisea.<br>I. Tras perder a Briseida por culpa de Agamenón, Aquiles se retira de la batalla y esto produce la derrota parcial de los aqueos.<br>II. Luego de la muerte de Patroclo, Menelao ataca la ciudad de Troya con el fin de vengar la terrible afrenta.<br>III. Gracias a su ingenio, fortaleza y audacia, Odiseo supera numerosos escollos en su viaje de regreso a Ítaca.",
		A: "FFV",
		B: "VVV",
		C: "VFV",
		D: "FVV",
		E: "VFF",
		Correct: "C"
	},
	{
		name: "2016iiCE65",
		subject: "Literature",
		sub_subject: "Literature",
		prompt: false,
		image: false,
		question: "Sus novelas emplean un español quechuizado, representan los conflictos de la cultura andina y manifiestan un lenguaje lírico intenso. ¿A qué escritor corresponde esta caracterización?",
		A: "Ciro Alegría",
		B: "Mario Vargas Llosa",
		C: "Abraham Valdelomar",
		D: "José María Arguedas",
		E: "Inca Garcilaso de la Vega",
		Correct: "D"
	},
	{
		name: "2016iiCE66",
		subject: "Social Sciences",
		sub_subject: "Psychology",
		prompt: false,
		image: false,
		question: "Para incrementar el consumo de llamadas de teléfonos celulares, una empresa de telefonía móvil ha decidido regalar minutos libres a los clientes que llegan a consumir un monto determinado en su línea. La empresa está aplicando el principio conductual denominado",
		A: "reforzamiento positivo.",
		B: "reforzamiento negativo",
		C: "castigo negativo",
		D: "castigo positivo",
		E: "coste de respuesta",
		Correct: "A"
	},
	{
		name: "2016iiCE67",
		subject: "Social Sciences",
		sub_subject: "Psychology",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE68",
		subject: "Social Sciences",
		sub_subject: "Psychology",
		prompt: false,
		image: false,
		question: "La relación de apego que surge entre una madre y su hijo sirve para regular la proximidad entre ambos, de tal forma que ante la sensación de peligro, de daño por una caída o simplemente ante el cansancio del niño se producen determinados comportamientos maternos como acoger al niño, abrazarlo o hablarle con tono de apaciguamiento. Todo esto permite que el niño",
		A: "incremente su inteligencia emocional.",
		B: "desarrolle sus sistemas de alarma.",
		C: "adquiera autoconciencia.",
		D: "forme su personalidad autónoma.",
		E: "recobre su seguridad personal.",
		Correct: "D"
	},
	{
		name: "2016iiCE69",
		subject: "Social Sciences",
		sub_subject: "Civic Education",
		prompt: false,
		image: false,
		question: "Señale cuál de los siguientes enunciados expresa un estado de enamoramiento real de una persona hacia otra.",
		A: "Me lo presentó mi hermana mayor, a simple vista no me pareció atractivo y realmente no lo es, pero cuando conversamos me sentí muy conmovida por su historia de vida. Él era huérfano y salió adelante trabajando desde pequeño. Eso me atrajo.",
		B: "Estoy enamorada de él. Es verdad que no es muy culto, no le gusta el estudio como a mí y se emborracha con sus amigos, pero canta tan bonito y es tan guapo que varias chicas lo tratan de seducir.",
		C: "Cuando lo conocí me hizo recordar a un actor de cine. Siempre me han gustado los chicos altos y delgados, y él lo es. Al conversar, descubrirnos que teníamos gustos y proyecciones de vida algo diferentes, pero creo que eso se puede superar.",
		D: "Lo conocí en una fiesta, estaba conversando con sus amigos y me pareció el más guapo de todos. Cuando me sacó a bailar, me contó sus logros en la universidad y que le gustaba el teatro como a mí. Me enamoré inmediatamente.",
		E: "Al verlo por primera vez no sentí nada por él, pero conforme lo fui conociendo me acostumbré a su presencia y a sus halagos. Es una buena persona y me quiere mucho. Sé que lo llegaré a amar.",
		Correct: "D"
	},
	{
		name: "2016iiCE70",
		subject: "Social Sciences",
		sub_subject: "Civic Education",
		prompt: false,
		image: false,
		question: "Frente a los muy elevados índices de criminalidad registrados en la ciudad de Chiclayo, el gobierno regional de Lambayeque y un gran número de organizaciones políticas y de la sociedad civil proponen llevar adelante una consulta popular por referéndum con el fin de recortar sustantivamente el derecho al debido proceso y a la protección jurisdiccional efectiva de todos aquellos detenidos y procesados por delitos contra el patrimonio.<br>¿El referéndum planteado está permitido por la normatividad constitucional?",
		A: "No, no puede someterse a referéndum la supresión o disminución de derechos constitucionales.",
		B: "Sí, en caso de estado de emergencia se pueden suspender determinados derechos fundamentales.",
		C: "Si, en tanto que el referéndum sea autorizado por la totalidad de los miembros del Tribunal Constitucional.",
		D: "No, la restricción de los derechos no puede realizarse por medio de un referéndum sino a través de un plebiscito.",
		E: "Sí, siempre y cuando dicho referéndum cuente con la aprobación de la Corte Suprema de Justicia.",
		Correct: "A"
	},
	{
		name: "2016iiCE71",
		subject: "Social Sciences",
		sub_subject: "Peruvian History",
		prompt: false,
		image: false,
		question: "La cultura Chanca, desarrollada durante el Segundo Intermedio y finalmente conquistada por los Incas, se ubicó en los territorios que hoy ocupan los actuales departamentos o regiones de",
		A: "Junín, Pasco y Ayacucho.",
		B: "Pasco, Cajamarca y Huancavelica.",
		C: "Arequipa, Ayacucho y Apurímac.",
		D: "Junín, Huancavelica y Ayacucho.",
		E: "Ayacucho, Apurímac y Huancavelica.",
		Correct: "E"
	},
	{
		name: "2016iiCE72",
		subject: "Social Sciences",
		sub_subject: "Peruvian History",
		prompt: false,
		image: false,
		question: "El fortalecimiento de la administración del virreinato peruano requería un minucioso conocimiento de la realidad local y regional. Esa información fue posible obtenerla mediante la institución conocida como",
		A: "visita.",
		B: "encomienda.",
		C: "probanza.",
		D: "requerimiento.",
		E: "reducción.",
		Correct: "A"
	},
	{
		name: "2016iiCE73",
		subject: "Social Sciences",
		sub_subject: "Peruvian History",
		prompt: false,
		image: false,
		question: "La Independencia, además de un enfrentamiento militar, fue también un escenario para propuestas políticas diversas. Así, en la Conferencia de Miraflores de 1820, los representantes de José de San Martín plantearon a los delegados del virrey Pezuela",
		A: "el retiro del ejército español de América del Sur.",
		B: "la implementación de la monarquía constitucional.",
		C: "la sujeción a la Constitución liberal de 1812.",
		D: "la creación de un Triunvirato de Regencia.",
		E: "el reconocimiento de la Independencia americana.",
		Correct: "B"
	},
	{
		name: "2016iiCE74",
		subject: "Social Sciences",
		sub_subject: "Peruvian History",
		prompt: false,
		image: false,
		question: "Durante el segundo gobierno de Augusto B. Leguía (1919-1930), se dio la Ley de Conscripción Vial de 1920, que obligaba a los indígenas varones de 18 a 60 años a trabajar en la __________ y de esta forma contribuir al desarrollo e integración del país. Sin embargo, esta medida se convirtió en la práctica en un mecanismo de __________.",
		A: "implementación de trochas - sometimiento",
		B: "reparación de ferrocarriles - marginación",
		C: "construcción de carreteras - explotación",
		D: "ampliación de cárceles - expoliación",
		E: "fabricación de vehículos - empobrecimiento",
		Correct: "C"
	},
	{
		name: "2016iiCE75",
		subject: "Social Sciences",
		sub_subject: "Universal History",
		prompt: false,
		image: false,
		question: "La prehistoria se divide en dos grandes épocas: la Edad de Piedra y, la Edad de los Metales. La primera se subdivide en Paleolítico, Mesolítico y Neolítico. Una de las características fundamentales del Mesolítico es",
		A: "la producción de alimentos.",
		B: "la práctica funeraria.",
		C: "el surgimiento del comercio.",
		D: "la vida sedentaria.",
		E: "la aparición de la cerámica.",
		Correct: "A"
	},
	{
		name: "2016iiCE76",
		subject: "Social Sciences",
		sub_subject: "Universal History",
		prompt: false,
		image: false,
		question: "La cultura egipcia desarrolló diversos aspectos de la ciencia y la cultura. Uno de ellos fue su amplio conocimiento de las matemáticas, cuya aplicación se puede apreciar en",
		A: "la arquitectura y la agricultura.",
		B: "la astronomía y la momificación.",
		C: "la escritura y la astronomía.",
		D: "la anatomía humana y la religión.",
		E: "el calendario y la medicina.",
		Correct: "A"
	},
	{
		name: "2016iiCE77",
		subject: "Social Sciences",
		sub_subject: "Universal History",
		prompt: false,
		image: false,
		question: "Los adelantos técnicos y científicos del siglo XV hicieron posibles los viajes de exploración y descubrimientos de nuevas tierras. Una consecuencia principal de ello fue",
		A: "la consolidación del cristianismo como religión universal.",
		B: "la victoria del Imperio español sobre el Imperio británico.",
		C: "el dominio español de las costas occidentales de África.",
		D: "el predominio europeo sobre territorios en otros continentes.",
		E: "la victoria del Imperio español sobre el Imperio portugués.",
		Correct: "D"
	},
	{
		name: "2016iiCE78",
		subject: "Social Sciences",
		sub_subject: "Universal History",
		prompt: false,
		image: false,
		question: "En el siglo XVIII, en Inglaterra se presentaron ciertas condiciones que favorecieron su desarrollo económico, tales como el aumento de la producción agrícola y el avance del conocimiento científico y tecnológico. De igual forma, otro factor que permitió el despegue de Inglaterra durante la primera Revolución Industrial fue",
		A: "el surgimiento de la clase obrera.",
		B: "la disminución de la industria textil.",
		C: "la inmigración francesa.",
		D: "el aumento del contrabando.",
		E: "el aumento de la población.",
		Correct: "E"
	},
	{
		name: "2016iiCE79",
		subject: "Social Sciences",
		sub_subject: "Geography",
		prompt: false,
		image: false,
		question: "El clima del Perú está condicionado por los siguientes factores: posición intertropical, el anticiclón del Pacífico Sur, la corriente de Humboldt, la cordillera de los Andes, entre otros. ¿Cuál es el factor que desempeña un papel determinante en la ocurrencia de lluvias torrenciales?",
		A: "Los vientos del Este",
		B: "La corriente del Niño",
		C: "La corriente peruana",
		D: "La contracorriente ecuatoriana",
		E: "Las precipitaciones orográficas",
		Correct: "A"
	},
	{
		name: "2016iiCE80",
		subject: "Social Sciences",
		sub_subject: "Geography",
		prompt: false,
		image: false,
		question: "Una de las categorías de las áreas naturales protegidas denominadas __________ tiene por objetivo “la protección del medio ambiente y el fomento del espacio en relación armoniosa con el hombre y la naturaleza”.",
		A: "reserva nacional",
		B: "santuario nacional",
		C: "santuario histórico",
		D: "parque nacional",
		E: "reserva paisajística",
		Correct: "E"
	},
	{
		name: "2016iiCE81",
		subject: "Social Sciences",
		sub_subject: "Geography",
		prompt: false,
		image: false,
		question: "Por efecto del crecimiento demográfico acelerado, el área urbana de Lima viene expandiéndose en forma desordenada, observándose la construcción de viviendas en suelos arenosos, en rellenos sanitarios y en las laderas de los cerros. ¿Qué zona define el grado de daños que sufren las edificaciones construidas deficientemente y sobre suelos inapropiados?",
		A: "Zona de alta amenaza para las construcciones y sus habitantes",
		B: "Zona de alta vulnerabilidad para las construcciones y sus habitantes",
		C: "Zona de alto riesgo para las construcciones y sus habitantes",
		D: "Zona de bajo peligro para las construcciones y sus habitantes",
		E: "Zona de baja vulnerabilidad para las construcciones y sus habitantes",
		Correct: "C"
	},
	{
		name: "2016iiCE82",
		subject: "Social Sciences",
		sub_subject: "Geography",
		prompt: false,
		image: false,
		question: "Cuando se analiza estadísticamente una población, es posible cuantificar diferentes aspectos de la misma. Al respecto, el establecimiento de la relación entre el número total de varones por cada cien mujeres se denomina",
		A: "índice de masculinidad.",
		B: "tasa de crecimiento.",
		C: "índice de natalidad.",
		D: "tasa de fecundidad.",
		E: "índice de femineidad.",
		Correct: "A"
	},
	{
		name: "2016iiCE83",
		subject: "Social Sciences",
		sub_subject: "Economy",
		prompt: false,
		image: false,
		question: "El Organismo Supervisor de Inversión en Energía y Minas del Perú (OSINERGMIN) ha desarrollado una herramienta informática que permite identificar el precio del gas natural vehicular (GNV) de todos los grifos registrados. Su uso ayudará al   a ubicar la oferta más conveniente.",
		A: "productor",
		B: "inversionista",
		C: "consumidor",
		D: "sector público",
		E: "grifero",
		Correct: "C"
	},
	{
		name: "2016iiCE84",
		subject: "Social Sciences",
		sub_subject: "Economy",
		prompt: false,
		image: false,
		question: "El turismo es una actividad económica creciente en el Perú. Al ser promovidos los numerosos lugares turísticos por las agencias operadoras, los impuestos generados por dicha actividad en el país contribuirían a generar una economía",
		A: "centralizada",
		B: "globalizada",
		C: "internacional",
		D: "subregional",
		E: "descentralizada",
		Correct: "E"
	},
	{
		name: "2016iiCE85",
		subject: "Social Sciences",
		sub_subject: "Economy",
		prompt: false,
		image: false,
		question: "En el mes de marzo, el calendario de pagos de la Sunat exige al contribuyente declarar el impuesto a la renta. Este tributo se conoce como impuesto",
		A: "a la venta.",
		B: "directo.",
		C: "al consumo.",
		D: "indirecto.",
		E: "al producto.",
		Correct: "B"
	},
	{
		name: "2016iiCE86",
		subject: "Social Sciences",
		sub_subject: "Economy",
		prompt: false,
		image: false,
		question: "La inversión es un componente de la producción y, si existe, desencadena un conjunto de beneficios para la sociedad. Dependiendo del monto, su efecto es de corto o largo plazo. En ese sentido, cuando el inversionista destina dinero a un proyecto, busca aumentar",
		A: "el consumo.",
		B: "la depreciación.",
		C: "el ingreso.",
		D: "el impuesto.",
		E: "la ganancia.",
		Correct: "A"
	},
	{
		name: "2016iiCE87-88",
		subject: "Social Sciences",
		sub_subject: "Philosophy",
		prompt: 'La verdad, no es una cosa que exista y haya que encontrar ni descubrir, sino una cosa que hay que crear y que proporciona un nombre a cierto proceso y, más aún, a una voluntad de violentar los hechos hasta el infinito; introducir la verdad en los hechos por un proceso in infinitum, una determinación activa, no es la llegada a la conciencia de una realidad firme y definida por sí misma. Es uno de los nombres de la “voluntad de poderío”.<br><font size="2">NIETZSCHE, F. Voluntad de poderío, Vol. 1., Libro II, 291.</font>',
		image: false,
		question: "De acuerdo con la crítica nietzscheana a la concepción tradicional del conocimiento, se puede inferir que",
		A: "su planteamiento pretende revalidar el uso de la razón.",
		B: "el proceso del conocimiento científico resulta infinito.",
		C: "la voluntad es el origen y la razón de ser de la verdad.",
		D: "su concepción de la verdad se asemeja al desocultamiento.",
		E: "ningún método filosófico ha logrado falsear la conciencia.",
		Correct: "C"
	},
	{
		name: "2016iiCE88",
		subject: "Social Sciences",
		sub_subject: "Philosophy",
		prompt: "2016iiCE87-88",
		image: false,
		question: "Cuando Nietzsche se refiere al carácter arbitrario de la verdad de los hechos, pretende advertir que",
		A: "la verdad es una invención y una tergiversación.",
		B: "el mundo objetivo obedece a un conjunto de leyes.",
		C: "es preciso descifrar el sentido oculto de la verdad.",
		D: "la verdad carece de cualquier determinación histórica.",
		E: "es necesario implementar un proceso de simplificación.",
		Correct: "A"
	},
	{
		name: "2016iiCE89",
		subject: "Social Sciences",
		sub_subject: "Philosophy",
		prompt: false,
		image: false,
		question: "¿Cuál de las siguientes situaciones es una aplicación del imperativo categórico kantiano: “Obra de tal manera que la máxima de tu acción pueda valer al mismo tiempo como el principio de una legislación universal”?",
		A: "La música clásica es valiosa, por eso, la escucho a toda hora en alto volumen para que muchos más la aprecien y así se convierta en preferencia general.",
		B: "En la cola para ingresar a la sala del cine, suelo quedarme hasta el final para cuidar que nadie se meta indebidamente y vaya contra el derecho del resto.",
		C: "Un amigo me pidió prestado dinero y, como tenía, preferí regalárselo para evitar que piense que nuestra amistad depende del dinero.",
		D: "Al estudiar, repaso con todos los compañeros las lecciones de inglés en el laboratorio. Así todos podemos aprender efectivamente una segunda lengua.",
		E: "Yo no permito que me maltraten y tampoco trato mal a nadie en mis labores diarias para que sea norma a seguir en la comunidad.",
		Correct: "E"
	},
	{
		name: "2016iiCE90",
		subject: "Social Sciences",
		sub_subject: "Philosophy",
		prompt: false,
		image: false,
		question: "Los filósofos estoicos consideraron tres aspectos como los más importantes en la filosofía: la lógica, la física y la ética. En el campo ético, asumieron que la libertad consistía en aceptar nuestro destino y que la finalidad era conseguir la vida feliz del sabio partiendo de la idea según la cual existe una conformidad entre",
		A: "el intelecto y la experiencia.",
		B: "los sentidos y la educación.",
		C: "la naturaleza y la razón.",
		D: "la teoría y la vida pública.",
		E: "la felicidad y el deber.",
		Correct: "C"
	},
	{
		name: "2016iiCE91",
		subject: "Science",
		sub_subject: "Physics",
		prompt: false,
		image: false,
		question: "Hablar por celular mientras se conduce un auto está prohibido debido a que el tiempo de reacción de una persona normal puede reducirse por un factor de dos. Por lo tanto, si el tiempo de reacción de una persona normal es 0,20 s, ¿cuál será la distancia recorrida antes que una persona, que habla por celular y conduce a 65,0 km/h, pueda frenar el vehículo?",
		A: "5,0 m",
		B: "7,0 m",
		C: "3,0 m",
		D: "6,0 m",
		E: "4,0 m",
		Correct: "E"
	},
	{
		name: "2016iiCE92",
		subject: "Science",
		sub_subject: "Physics",
		prompt: false,
		image: false,
		question: "Los trenes de levitación magnética (MAGLEV) están entre los medios más seguros y rápidos de la Tierra, una proeza de la tecnología y la física modernas. Tienen como principio la suspensión electromagnética y entrarán a funcionar comercialmente en Japón con velocidades mayores a 550 km/h en los próximos años. Si, partiendo del reposo, un tren MAGLEV es acelerado uniformemente durante 2,5 minutos hasta alcanzar los 540 km/h, ¿cuál sería su aceleración alcanzada?",
		A: "1,00 m/\\(\\mathrm{s^2}\\)",
		B: "0,10 m/\\(\\mathrm{s^2}\\)",
		C: "10,0 m/\\(\\mathrm{s^2}\\)",
		D: "15,0 m/\\(\\mathrm{s^2}\\)",
		E: "1,50 m/\\(\\mathrm{s^2}\\)",
		Correct: "A"
	},
	{
		name: "2016iiCE93",
		subject: "Science",
		sub_subject: "Physics",
		prompt: false,
		image: false,
		question: "En una instalación típica, la compañía eléctrica distribuye la electricidad a hogares individuales con un par de alambres o líneas de transmisión. Entonces, en una instalación eléctrica doméstica, los tomacorrientes deben ser conectados en __________ a estas líneas para que la misma __________ en todos los electrodomésticos conectados a esta instalación.",
		A: "paralelo — corriente eléctrica circule",
		B: "paralelo — tensión eléctrica sea aplicada",
		C: "paralelo — potencia eléctrica actúe",
		D: "serie — tensión eléctrica sea aplicada",
		E: "serie — corriente eléctrica circule",
		Correct: "B"
	},
	{
		name: "2016iiCE94",
		subject: "Science",
		sub_subject: "Chemistry",
		prompt: false,
		image: false,
		question: "El petróleo es un líquido natural oleaginoso e inflamable, constituido por una mezcla de hidrocarburos, que se extrae de lechos geológicos continentales o marítimos, y del que se obtienen productos utilizables con fines energéticos o industriales, como la gasolina, el querosene o el gasóleo. Los elementos químicos fundamentales presentes en mayor cantidad en el petróleo son",
		A: "hidrógeno y oxigeno.",
		B: "hidrógeno y nitrógeno.",
		C: "carbono y oxígeno.",
		D: "carbono y nitrógeno.",
		E: "hidrógeno y carbono.",
		Correct: "E"
	},
	{
		name: "2016iiCE95",
		subject: "Science",
		sub_subject: "Chemistry",
		prompt: false,
		image: false,
		question: "El pentacloruro de fósforo (PC,5) es una sustancia peligrosa que reacciona violentamente con el agua y es una fuente tanto de cloruro de hidrógeno como de cloro. Además, es utilizado en la fabricación de otros productos químicos, en la industria metalúrgica y en la industria farmacéutica.<br>En la formación del \\(P\\mathscr{l}_5\\) según la reacción \\(P_4+C\\mathscr{l}_2\\rightarrow PC\\mathscr{l}_5\\), balancee e indique el coeficiente estequiométrico del cloro.",
		A: "5",
		B: "6",
		C: "4",
		D: "10",
		E: "12",
		Correct: "D"
	},
	{
		name: "2016iiCE96",
		subject: "Science",
		sub_subject: "Chemistry",
		prompt: false,
		image: false,
		question: "La velocidad de una reacción es la rapidez con la cual los reactantes se transforman en productos. Esta velocidad determina el número de átomos, iones o moléculas de los reactantes o productos consumidos o formados por unidad de tiempo. Al respecto, para una reacción endotérmica, marque con V (verdadero) o F (falso), cada una de las siguientes proposiciones y luego señale la secuencia correcta.<br>I. La velocidad de la reacción solo depende de la naturaleza de los reactantes.<br>II. El incremento de la temperatura facilitará la formación de los productos.<br>III. El contenido de energía de los productos es menor que la de los reactantes.",
		A: "VVF",
		B: "FVF",
		C: "FFV",
		D: "FFF",
		E: "VVV",
		Correct: "B"
	},
	{
		name: "2016iiCE97",
		subject: "Science",
		sub_subject: "Biology",
		prompt: false,
		image: false,
		question: "Existe mucha discusión respecto a considerar los virus corno seres vivos. Los virus son de tamaño ultramicroscópico, están compuestos por ácidos nucleicos y proteínas, y son parásitos metabólicos. ¿En qué nivel de organización de la materia viva los podemos ubicar?",
		A: "Subcelular",
		B: "Celular",
		C: "Individual",
		D: "Molecular",
		E: "Atómico",
		Correct: "A"
	},
	{
		name: "2016iiCE98",
		subject: "Science",
		sub_subject: "Biology",
		prompt: false,
		image: false,
		question: "Como medida profiláctica para evitar las caries dentales, nos cepillamos los dientes por lo menos tres veces al día; sin embargo, debemos acudir al odontólogo cada cierto tiempo para eliminar las placas bacterianas. ¿Qué estructura de las bacterias permite la permanencia de estos organismos a pesar del cepillado diario?",
		A: "El mesosoma",
		B: "Las fimbrias",
		C: "La cápsula",
		D: "La pared",
		E: "Los flagelos",
		Correct: "B"
	},
	{
		name: "2016iiCE99",
		subject: "Science",
		sub_subject: "Biology",
		prompt: false,
		image: false,
		question: "Taenia solium es un parásito de los humanos que comúnmente se denomina solitaria, por ser el único individuo que habita el intestino delgado. Este parásito absorbe los nutrientes a través de su cutícula y, por consiguiente, debilita al hospedero. Además, es capaz de liberar proglótidos cargados de huevos producidos por",
		A: "partenogénesis.",
		B: "fecundación cruzada.",
		C: "fecundación externa.",
		D: "reproducción asexual.",
		E: "autofecundación.",
		Correct: "E"
	},
	{
		name: "2016iiCE100",
		subject: "Science",
		sub_subject: "Biology",
		prompt: false,
		image: false,
		question: "Durante la fotosíntesis, las plantas benefician al planeta consumiendo el \\(\\mathrm{CO_2}\\) y produciendo \\(\\mathrm{O_2}\\). Para realizarla es necesario que el agua, disponible en el suelo y alrededor de los pelos absorbentes de la raíz, llegue hasta las hojas, que son los órganos responsables del proceso. El tejido encargado de conducir el agua y las sales minerales desde las células de la raíz hasta las hojas se denomina",
		A: "xilema.",
		B: "floema.",
		C: "endodermis.",
		D: "epidermis.",
		E: "peridennis",
		Correct: "A"
	}/*,
	{
		name: "2016iiCE101",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE102",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE103",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE104",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE105",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE106",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE107",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE108",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE109",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE110",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE111",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE112",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE113",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE114",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE115",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE116",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE117",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE118",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE119",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE120",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE121",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE122",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE123",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE124",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE125",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE126",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE127",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE128",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE129",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "2016iiCE130",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	}*/
]