// questions array (below) is numbered 0-end
// but exam questions are numbered 1 - (end - 1)        
function checkAnswer() {
    
    var numOfQs = 0;
    
    var choices = [];
    var chosen = [];
    
    for (var i = 0; i < pos; i++ ) {
        numOfQs += qNum[i];
    }
    
    firstQ = numOfQs - qNum[pos - 1];
    //document.write(questions[pos].Correct);
    for (var j = firstQ; j < numOfQs; j++) {
    choices.push(document.getElementsByName("choices" + j));
    for (var i=0; i < choices[j -firstQ].length; i++) {
        if (choices[j - firstQ][i].checked) {
            chosen.push(choices[j - firstQ][i].value);
            //document.write("if");
        }
    }
    }
        
    //document.write(questions[pos].Correct);
    //document.write(choices.length);
    //document.write("Holass");
    for (var i=0; i < chosen.length; i++) {

        if (chosen[i] == questions[pos].Correct) {
            score++;
        }
    }
    
    //document.write("Hola");
    if (pos == test.length) {
        document.write("<h1>Te sacaste " + score + " de " + numOfQs + " preguntas</h1><br>");
        document.write(qNum);
    } else {
    renderQuestion();
    }
}


// will create array of htmls that make up
// ONE/SINGLE test
function testIntegrator() {
    var len = questions.length;
    var num = 0;
    var test = [];
    while (num < len) {
        
        var text = '<html lang="en">\
        <head></head>\
        <body>';
        if (questions[num].name.includes("-")) {
            var index = questions[num].name.indexOf("-");
            var z = parseInt(questions[num].name.substring(index+1));
            qNum.push(parseInt(z - num));
            for (; num < z; num++) {
                text += display(num+1);
            }
            text += '</body>\
            </html>'
            test.push(text);
        } else {
            text += '</body>\
            </html>'
            test.push(display(num+1));
            qNum.push(1);
            num++;
        }
    }
    
    return test;
}

// Like distill but w/ a test
function testtill(num) {
    num = num - 1;
    if (questions[num].name.includes("-")) {
        var i = questions[num].name.indexOf("-");
        document.write(i);
        var a = parseInt(questions[num].name[i-1]);
        document.write("<br>" +a);
        var z = parseInt(questions[num].name.substring(i+1));
        var text = "";
        for (j = a; j <= z; j++) {
            text += display(j);
        }
        return text;
    }
    else {
        return display(num + 1);
    }
}

//displays individual question (from array object below)
// display INPUT: # of Question
function display(num) {
    num = num - 1;
    choices = "'choices" + num + "'";
    var text = "";
    if (questions[num].prompt && questions[num].prompt.includes(" ")) {
        text += "<p>" + questions[num].prompt + "</p>";
    }
    text += "<p>" + questions[num].question +"</p>";
    text += "<input type='radio' name=" + choices + " value='A'> " + questions[num].A + "<br>";
    text += "<input type='radio' name=" + choices + " value='B'> " + questions[num].B + "<br>";
    text += "<input type='radio' name=" + choices + " value='C'> " + questions[num].C + "<br>";
    text += "<input type='radio' name=" + choices + " value='D'> " + questions[num].D + "<br>";
    text += "<input type='radio' name=" + choices + " value='E'> " + questions[num].E + "<br>";
    /*
    text += "<input type='radio' name='choices1' value='A'>" + questions[num].A + "<br>";
    text += "<input type='radio' name='choices' value='B'>" + questions[num].B + "<br>";
    text += "<input type='radio' name='choices' value='C'>" + questions[num].C + "<br>";
    text += "<input type='radio' name='choices' value='D'>" + questions[num].D + "<br>";
    text += "<input type='radio' name='choices' value='E'>" + questions[num].E + "<br>";
    */
    return text;  
}

var questions = [
	{
		name: "SM2016iiADF1-2",
		subject: "VA",
		sub_subject: "Series",
		prompt: "Después de identificar y analizar la relación semántica de la serie de cada ítem, seleccione la respuesta más adecuada",
		image: false,
		question: "Suceder, ocurrir, acontecer,",
		A: "generar",
		B: "acaecer",
		C: "causar",
		D: "iniciar",
		E: "pender",
		Correct: "B"
	},
	{
		name: "SM2016iiADF2",
		subject: "VA",
		sub_subject: "Series",
		prompt: "SM2016iiADF1-2",
		image: false,
		question: "Atisbar, divisar; descubrir, revelar;",
		A: "segregar, emerger",
		B: "contemplar, extasiar",
		C: "menguar, espaciar",
		D: "incautar, inquirir",
		E: "destellar, refulgir",
		Correct: "E"
	},
	{
		name: "SM2016iiADF3-5",
		subject: "VA",
		sub_subject: "Sentence Elimination",
		prompt: "Lea atentamente cada conjunto oracional y determine el enunciado que debe eliminarse por no corresponder al tema o por ser de índole tangencial.",
		image: false,
		question: "(I) La homeopatía, medicina alternativa creada en 1796 por Samuel Hahnemann, se basa en la doctrina de que lo similar cura lo similar, es decir, una sustancia que cause los síntomas de una enfermedad en personas sanas curará algo parecido en personas enfermas. (II) La homeopatía es considerada una pseudociencia, dado que se ha descubierto que sus remedios no son más efectivos que los placebos, razón por la cual los científicos dudan de su eficacia y la consideran como una pseudoexplicación. (III) Hahnemann creía que las causas subyacentes de las enfermedades eran fenómenos que llamó miasmas y que los remedios homeopáticos actuaban sobre ellas. (IV) Según la doctrina homeopática de Hahnemann, se debe considerar la totalidad de los síntomas de los pacientes, rasgos de personalidad, estado físico e historia de vida. (V) Originalmente, el creador de la homeopatía postuló solo tres miasmas, de las cuales la más importante era la psora (“picazón” en griego), descrita como relacionada a cualquier enfermedad picante de la piel.",
		A: "V",
		B: "I",
		C: "II",
		D: "III",
		E: "IV",
		Correct: "II"
	},
	{
		name: "SM2016iiADF4",
		subject: "VA",
		sub_subject: "Sentence Elimination",
		prompt: "SM2016iiADF3-5",
		image: false,
		question: "(I) La máscara es una figura que representa un rostro humano, de animal o puramente imaginario. (II) La máscara le permite a la persona tomar el aspecto de otra o practicar ciertas actividades escénicas o rituales. (III) Desde los tiempos más remotos, el uso de máscaras ha estado vinculado a la religión y todavía está presente en los ritos mágicos de muchos pueblos. (IV) Por medio de las máscaras, se intentaba controlar a los espíritus y demonios, asustar a los enemigos o tener suerte en la caza. (V) La máscara empleada para protegerse de gases tóxicos consiste en una careta para protegerse contra determinados agentes agresivos mediante filtrado del aire que se respira.",
		A: "V",
		B: "II",
		C: "I",
		D: "IV",
		E: "III",
		Correct: "A"
	},
	{
		name: "SM2016iiADF5",
		subject: "VA",
		sub_subject: "Sentence Elimination",
		prompt: "SM2016iiADF3-5",
		image: false,
		question: "(I) Desde un punto de vista tradicional, la falacia se define como un razonamiento incorrecto, pero que, dadas ciertas condiciones, puede tener un gran efecto persuasivo. (II) Definida de esa manera, se puede entender que las falacias sean empleadas en las contiendas políticas, en las discusiones de los foros judiciales y hasta en los asuntos cotidianos. (III) En efecto, en la vida diaria, en los ámbitos de la ciencia y en los círculos del pensamiento político siempre se recurre a los razonamientos con el fin de convencer o de persuadir. (IV) Asimismo, en los contextos especializados de la polémica, se usan falacias en ciencia y en filosofía; por ejemplo, cuando se recurre al argumento de la autoridad para zanjar una cuestión intrincada. (V) Las falacias también se aplican, con rédito, en el utilitario mundo de la publicidad al momento de persuadir recurriendo a factores emocionales o a imágenes impactantes.",
		A: "V",
		B: "II",
		C: "I",
		D: "IV",
		E: "III",
		Correct: "E"
	},
	{
		name: "SM2016iiADF6-10",
		subject: "",
		sub_subject: "",
		prompt: 'El objetivo de entender el estrés no es evitarlo a toda costa. Una emoción de intensidad y duración adecuadas (un recorrido en la montaña rusa, ver una película de horror, enfrentar a un aguerrido oponente de ajedrez) libera dopamina en las vías cerebrales del placer. Esta sensación agradable o buen estrés es lo que conocemos como estimulación y hasta pagamos por experimentarla.<br>Sin embargo, hay otra forma de estrés: el llamado estrés crónico. Las formas de contrarrestar sus efectos adversos son los fármacos en el nivel biológico y, en el personal, con técnicas de control, como meditación, oración, ejercicio, psicoterapia, pasatiempos y reuniones sociales. Algunas de estas estrategias suprimen directamente la respuesta del cuerpo a este tipo de estrés; por ejemplo, la respiración pausada y profunda de la meditación reduce la liberación de hormonas del estrés, mientras que el ejercicio regular disminuye los niveles de dichas hormonas en estado de reposo. Otras actividades contribuyen elevando el sentimiento de control y previsibilidad, como sucede con numerosas prácticas religiosas que proporcionan respuestas a lo absolutamente inexplicable. Y el ámbito social también puede aportar muchos beneficios, incluido el caso muy particular de sentirnos necesarios cuando ayudamos a otros.<br>Otra buena noticia contra el estrés crónico tiene que ver con la distancia que podemos asumir acerca de nuestras condiciones y hábitos de vida. No solo es improbable que los lectores de este texto sufran de disentería, sino que también es poco probable que pierdan sus viviendas, padezcan hambruna o se vean amenazados por leones. Mientras lidiamos con embotellamientos, fechas de entrega, hipotecas e inversiones fallidas, vale la pena recordar que todo es parte del mundo que hemos construido; son agentes estresantes incomprensibles para cualquier venado o incluso para algunos humanos. Así como somos lo bastante inteligentes para inventar preocupaciones, ambiciones y celos —y lo suficientemente tontos para caer en sus trampas—, todos tenemos el potencial de ser lo bastante sabios para darles la perspectiva correcta.<br><font size="2">Adaptado de Sapolsky, Robert. “Bajo estrés”. National Geographic en español. Enero de 2010.</font>',
		image: false,
		question: "El texto trata, principalmente,",
		A: "de los peligros que hoy enfrenta el hombre.",
		B: "de las estrategias para combatir todo estrés.",
		C: "de la utilidad de la meditación y el ejercicio.",
		D: "del estrés crónico y de cómo contrarrestarlo.",
		E: "de la necesidad de promover el buen estrés.",
		Correct: "D"
	},
	{
		name: "SM2016iiADF7",
		subject: "VA",
		sub_subject: "Reading Comprehension",
		prompt: "SM2016iiADF6-10",
		image: false,
		question: "En el texto, el término AGUERRIDO adquiere el significado de",
		A: "agresivo.",
		B: "avieso.",
		C: "difícil.",
		D: "temerario.",
		E: "cruel.",
		Correct: "C"
	},
	{
		name: "SM2016iiADF8",
		subject: "VA",
		sub_subject: "Reading Comprehension",
		prompt: "SM2016iiADF6-10",
		image: false,
		question: "Del texto se puede inferir que lo que actualmente nos provoca estrés crónico",
		A: "es la amenaza de ser devorados por depredadores.",
		B: "resulta comprensible para los animales domésticos.",
		C: "está asociado con el mundo que hemos creado.",
		D: "es la imprevisibilidad de las sociedades tradicionales.",
		E: "es la búsqueda de emociones intensas y duraderas.",
		Correct: "C"
	},
	{
		name: "SM2016iiADF9",
		subject: "VA",
		sub_subject: "Reading Comprehension",
		prompt: "SM2016iiADF6-10",
		image: false,
		question: "Un enunciado incompatible con el texto es afirmar que el buen estrés",
		A: "se obtiene al subir a un emocionante juego mecánico.",
		B: "consiste en una sensación agradable de experimentar.",
		C: "libera dopamina en las vías cerebrales del placer.",
		D: "constituye un requisito necesario para el estrés crónico.",
		E: "se genera por una emoción de intensidad adecuada.",
		Correct: "D"
	},
	{
		name: "SM2016iiADF10",
		subject: "VA",
		sub_subject: "Reading Comprehension",
		prompt: "SM2016iiADF6-10",
		image: false,
		question: "Si pudiéramos ser capaces de dar la valoración adecuada a los agentes estresantes, entonces.",
		A: "lograríamos evitar las enfermedades.",
		B: "podríamos controlar el estrés crónico.",
		C: "crecería la imprevisibilidad del mundo.",
		D: "experimentaríamos el buen estrés.",
		E: "sucumbiríamos ante el estrés crónico.",
		Correct: "B"
	},
	{
		name: "SM2016iiADF11-15",
		subject: "VA",
		sub_subject: "Reading Comprehension",
		prompt: false,
		image: false,
		question:'En los resultados obtenidos por los alumnos de nuestro pais en la prueba PISA (2000-2012), se ven ciertos avances: partiendo de niveles muy bajos, se mejoró 73 puntos en matemáticas, 57 en lectura y 40 en ciencias. Si bien esto es positivo, los resultados también evidencian que el Perú aún se mantiene muy rezagado en educación en comparación con el resto de los paises de la región.<br>De acuerdo con un informe de Axel Rivas referido a la aplicación de la prueba PISA en cinco paises de América Latina, los niveles educativos de esta región han mejorado gracias al gran crecimiento económico que trajo consigo que más de 50 millones de personas dejaran de ser pobres entre el 2000 y el 2010, lo que tuvo un efecto directo en la educación.<br>El estudio destaca al Perú por sus avances en la cobertura escolar, acceso a la educación y la mejora sustancial de la calidad educativa. El informe establece que el crecimiento económico de nuestro país permitió invertir más recursos en educación y tener así pisos sistémicos más sólidos. Por ejemplo, destaca la recuperación de la infraestructura, la incorporación de más docentes y el aumento de libros de texto. Esto posibilitó desarrollar condiciones educativas más <b>atractivas</b>, lo que abrió las puertas a que más alumnos vayan a estudiar en vez de trabajar.<br>Por otro lado, el nivel de inversión pública del Estado peruano en educación, en relación con el PBI, todavía está muy por debajo del resto de América Latina. El documento señala que si bien el presupuesto para la educación creció significativamente, lo hizo junto al PBI, por lo que no existió un mayor esfuerzo presupuestario a favor del sector, como sí ocurrió en los otros países (hay que tomar en cuenta que el informe no considera el aumento del porcentaje del PBI destinado a educación aprobado en este gobierno a 3,5% ni la propuesta de elevarlo al 3,85% en el 2016).<br>Sobre el destino de los recursos adicionales para el sector, Rivas sostiene que: “Hay que invertir en el círculo de la docencia. Es decir, invertir en política de mayores salarios pero que incluya mayor capacitación y mayores exigencias a los profesores. Se debe prestigiar la formación y prestigiar socialmente al docente”.',
		A: "desigualdad.",
		B: "jerarquía.",
		C: "reconocimiento.",
		D: "oportunidad.",
		E: "valor.",
		Correct: "D"
	},
	{
		name: "SM2016iiADF12",
		subject: "VA",
		sub_subject: "Reading Comprehension",
		prompt: "SM2016iiADF11-15",
		image: false,
		question: "Los cuadros y el texto registran datos relativos a los resultados de pruebas educativas aplicadas a estudiantes de cinco países latinoamericanos y lo invertido por sus gobiernos en educación en el período 2000-2012. En lo concerniente al Perú, se puede afirmar que",
		A: "el nivel de los estudiantes ha mejorado en mayor proporción que el de los otros países.",
		B: "si los gobernantes invirtieran más en educación, sus estudiantes superarían a los demás.",
		C: "os estudiantes elevaron su rendimiento del mismo modo que el Estado elevó sus presupuestos.",
		D: "si bien sus recursos no están a la par que los de otros países, sus estudiantes si lo están.",
		E: "sus estudiantes han rendido por debajo de los otros países, pero en 2012 cerraron esta brecha.",
		Correct: "A"
	},
	{
		name: "SM2016iiADF13",
		subject: "VA",
		sub_subject: "Reading Comprehension",
		prompt: "SM2016iiADF11-15",
		image: false,
		question: "Las líneas referidas al Perú en ambos cuadros y el análisis de Axel Rivas permiten inferir que, con el paso de los años,",
		A: "el rendimiento se ha independizado de la inversión educativa.",
		B: "se ha logrado un empleo más efectivo de los recursos.",
		C: "el gasto en educación no llega a tener relevancia social.",
		D: "se registra un gran aumento en la inversión educativa.",
		E: "se alcanzará por fin el nivel educativo de los demás países.",
		Correct: "B"
	},
	{
		name: "SM2016iiADF14",
		subject: "VA",
		sub_subject: "Reading Comprehension",
		prompt: "SM2016iiADF11-15",
		image: false,
		question: "Del gasto en educación realizado en Uruguay y sus resultados obtenidos en las prueba PISA, se puede señalar que",
		A: "la relación entre la inversión y los resultados educativos es directamente proporcional.",
		B: "el gobierno de dicho país está poco preocupado por el futuro inmediato de sus estudiantes.",
		C: "dicho país ha decidido transformar sus pobres resultados obtenidos en la prueba internacional.",
		D: "a mayor inversión pública, se observa una mejora ostensible en los resultados de los educandos.",
		E: "La inversión en educación no se manifiesta de forma automática en el desempeño estudiantil.",
		Correct: "E"
	},
	{
		name: "SM2016iiADF15",
		subject: "",
		sub_subject: "",
		prompt: "SM2016iiADF11-15",
		image: false,
		question: "Si se cumplieran las propuestas de elevar la inversión pública en educación en el Perú siguiendo las consecuencias del estudio referido,",
		A: "en la próxima prueba PISA, el Perú obtendría el mayor puntaje de la región.",
		B: "el desempeño de los estudiantes peruanos sería superior al de los uruguayos.",
		C: "la infraestructura educativa en el Perú concentraría la ejecución de la inversión.",
		D: "los sueldos de los profesores se verían significativamente incrementados.",
		E: "el ministro de Educación lograría un alto índice de aprobación por su gestión.",
		Correct: "D"
	},
	{
		name: "SM2016iiADF16-20",
		subject: "VA",
		sub_subject: "Reading Comprehension",
		prompt: '<b>TEXTO A</b><br>La propiedad es un derecho prominente: articula a la sociedad civil y a los gobiernos, por esto su defensa absoluta garantiza el orden social. El gran Aristóteles estableció que el esclavo es una propiedad con alma, una posesión animada. Finalmente, no ha habido sociedad civil que no haya reconocido como propiedad la que tiene el amo en el siervo. (...) El esclavo no es un hombre pleno, capaz de gozar de todos sus derechos; requiere de una larga capacitación civil y moral para ingresar a la sociedad con calidad de ciudadano. La libertad y la igualdad en estas circunstancias serían peligrosas para el esclavo y para toda la sociedad, como lo demuestran las experiencias históricas (Santo Domingo, Colombia y Guatemala). La abolición solo causaría desórdenes por la naturaleza licenciosa de la gente de color: el departamento de Lima se convertiría en un desierto atravesado por hordas de beduinos errantes y feroces.<br><font size="2">Adaptación de Reclamación sobre los vulnerados derechos de los hacendados de las provincias litorales del departamento de Lima en 1833, de José María de Pando. Lima: Imp. Rep. de J.M. Concha, 1833</font><br><b>TEXTO B</b><br>Nuestras “piezas de ébano” sufrieron por siglos un feroz tratamiento; hoy solo podemos rechazar el comercio infame de carne humana. Los esclavócratas requerían de la esclavitud para conservar su poder económico y social: el bárbaro no era el esclavo, sino el amo esclavista. El siglo XIX llegaba a la mitad de su vida, y en todas las repúblicas de la América española, donde aún existía la ignominia de la esclavatura, se hacía sentir la reacción, que protestaba contra todo lo que, como la esclavitud del hombre por el hombre, simbolizara despotismo y barbarie. El decreto de abolición de Huancayo de 1854 fue un arma de guerra, pues favoreció la insurrección de Castilla contra Echenique y, simultáneamente, fue expresión de sentimientos humanitarios ya que la razón cristiana no podía aceptar la degradación de la condición humana.<br><font size="2">Adaptación de “Manumisión” (1888) de Ricardo Palma en Tradiciones peruanas. Madrid: Aguilar, 1964.</font>',
		image: false,
		question: "El texto de José María de Pando pretende demostrar, principalmente, que",
		A: "la liberación de los esclavos constituye una medida ilegal por las cualidades humanas inherentes al esclavo.",
		B: "las rebeliones de esclavos en Colombia o Guatemala muestran la urgencia de la abolición de la esclavitud.",
		C: "la esclavitud es parte de la realidad social, por lo que su abolición acarrearía consecuencias nefastas.",
		D: "la propiedad esclavista es legal, pero colisiona con el derecho a la igualdad que tiene todo ser humano.",
		E: "los principios de libertad e igualdad son inaplicables a la institución de la esclavitud en la costa del Perú.",
		Correct: "C"
	},
	{
		name: "SM2016iiADF17",
		subject: "VA",
		sub_subject: "Reading Comprehension",
		prompt: "SM2016iiADF16-20",
		image: false,
		question: "En el texto de Palma, el vocablo ESCLAVÓCRATAS se refiere a",
		A: "un grupo social, cuyo poder deriva de la esclavitud.",
		B: "una élite social conformada por amos abolicionistas.",
		C: "los esclavos rebeldes que jaqueaban el gobierno.",
		D: 'los esclavos más oprimidos, denominados “beduinos”.',
		E: "los dueños de esclavos con principios cristianos.",
		Correct: "A"
	},
	{
		name: "SM2016iiADF18",
		subject: "VA",
		sub_subject: "Reading Comprehension",
		prompt: "SM2016iiADF16-20",
		image: false,
		question: "¿Qué tipos de argumentos o razones sustentan las perspectivas de Pando y Palma?",
		A: "José María de Pando se apoya en razones legales y sociales; Ricardo Palma, en razones económicas y morales.",
		B: "El primero emplea argumentos jurídicos e histórico-sociales; el segundo, argumentos libertarios y cristianos.",
		C: "El defensor de la esclavitud apela a razones económicas; el abolicionista, a razones epistemológicas.",
		D: "Ricardo Palma emplea razones jurídicas, románticas y literarias; José María de Pando, sociales y morales.",
		E: "El defensor de la esclavitud emplea argumentos jurídicos; el abolicionista, argumentos económicos.",
		Correct: "B"
	},
	{
		name: "SM2016iiADF19",
		subject: "VA",
		sub_subject: "Reading Comprehension",
		prompt: "SM2016iiADF16-20",
		image: false,
		question: "Respecto de las argumentaciones de Pando y Palma, ¿cuál de los siguientes enunciados es correcto?",
		A: "Para ambos escritores, la visión cristiana del hombre se opone a la esclavitud porque los amos ejercen una violencia bárbara.",
		B: "El primero realiza la apología del principio abstracto, mientras que el segundo defiende la propiedad particular esclavista.",
		C: "Palma asigna a la condición humana menor valor que al derecho de propiedad; Pando sostiene lo contrario.",
		D: "Para Palma, el esclavo posee cualidades morales humanas; para Pando, la dimensión moral del esclavo es deficiente.",
		E: "Palma y Pando ratifican la naturaleza humana del esclavo, pero desprenden conclusiones divergentes de este principio.",
		Correct: "D"
	},
	{
		name: "SM2016iiADF20",
		subject: "VA",
		sub_subject: "Reading Comprehension",
		prompt: "SM2016iiADF16-20",
		image: false,
		question: "De lo leído, se puede inferir válidamente que",
		A: "Palma interpreta unívocamente el acto de la abolición de la esclavitud en el Perú.",
		B: "Pando y Palma concuerdan en lo esencial, pero discrepan en aspectos menores.",
		C: "Pando descarta la variable de la conducta social de los exesclavos en libertad.",
		D: "Pando cita a Aristóteles con el afán de refutar sus planteamientos filosóficos.",
		E: "Pando acepta la vigencia de la libertad e igualdad para los no-esclavos.",
		Correct: "E"
	},
	{
		name: "SM2016iiADF21",
		subject: "MA",
		sub_subject: "Arithmetic",
		prompt: false,
		image: false,
		question: "Se sabe que, en relación con el puntaje, X es menor que Y, W es mayor que V, Y es menor que W y Z es mayor que W. ¿Cuál de estos fue el puntaje más alto?",
		A: "X",
		B: "Y",
		C: "Z",
		D: "V",
		E: "W",
		Correct: "Z"
	},
	{
		name: "SM2016iiADF22",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Juan desea comprar una camioneta y decidirá entre los colores gris, negro, azul y guinda. Sin embargo, no quiere comprar ni una camioneta azul ni guinda, pues coincide con el color de los autos de sus amigos, Luis y Pedro. Tampoco quiere elegir entre las posibilidades del color del auto que elegirá su padre: negro o marrón. Entonces, se puede afirmar con seguridad que",
		A: "Luis tiene un auto de color azul.",
		B: "Pedro tiene un auto de color guinda.",
		C: "El padre de Juan tiene un auto de color marrón.",
		D: "Juan se decide por el color negro.",
		E: "Juan se decide por el color gris",
		Correct: "E"
	},
	{
		name: "SM2016iiADF23",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si se sabe que Juan tiene menos dinero que Luis, que Luis tiene más dinero que Rodolfo, pero menos que Miguel, elija la alternativa que contenga enunciados verdaderos.<br>I. Juan tiene menos dinero que cada uno de los otros.<br>II. La mitad del dinero de Juan y Rodolfo juntos no supera al de Luis.<br>III. Miguel tiene más dinero que la mitad de Juan y Rodolfo juntos.<br>IV. La mitad del dinero de Luis y Rodolfo juntos supera lo que tiene Miguel.",
		A: "II y III",
		B: "I y II",
		C: "III y IV",
		D: "Solo IV",
		E: "I y IV",
		Correct: "A"
	},
	{
		name: "SM2016iiADF24",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Halle el valor numérico de x en la siguiente secuencia de figuras:",
		A: "7",
		B: "8",
		C: "6",
		D: "9",
		E: "10",
		Correct: "D"
	},
	{
		name: "SM2016iiADF25",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la sucesión \\(a_1 = -1, a_2 = 0, a_3 = 5, a_4 = 14, a_5 = 27,...\\) halla \\(a_{21}\\)",
		A: "780",
		B: "779",
		C: "679",
		D: "660",
		E: "656",
		Correct: "B"
	},
	{
		name: "SM2016iiADF26",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si la suma de 1/3 de un número impar y 4/3 del número impar consecutivo es 61, ¿cuál es el número par entre estos dos números impares?",
		A: "32",
		B: "34",
		C: "46",
		D: "38",
		E: "36",
		Correct: "E"
	},
	{
		name: "SM2016iiADF27",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "La gráfica representa la cantidad de alumnos inscritos en las actividades realizadas por una institución educativa durante el ciclo de verano 2015.<br>Si cada alumno se inscribe en una sola actividad, ¿cuántos alumnos se inscribieron en total?",
		A: "42",
		B: "58",
		C: "50",
		D: "46",
		E: "44",
		Correct: "C"
	},
	{
		name: "SM2016iiADF28",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si el producto de tres dígitos <b>a, b</b> y <b>c</b> es el número de dos dígitos \\(\\mathrm{\\overline{bc}}\\), el producto de los dígitos <b>b</b> y <b>c</b> es c, y c = 5, halle el valor de <b>a</b>.",
		A: "2",
		B: "1",
		C: "4",
		D: "3",
		E: "5",
		Correct: "D"
	},
	{
		name: "SM2016iiADF29",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Sea<br>\\(\\mathrm{S =} \\textrm{ } \\frac{1}{1 \\times 6} + \\frac{1}{6 \\times 9} + \\frac{1}{9 \\times 12} + ... + \\frac{1}{300 \\times 303}\\)<br>halle el valor de S.",
		A: "\\(\\frac{1}{101}\\)",
		B: "\\(\\frac{4}{303}\\)",
		C: "\\(\\frac{50}{909}\\)",
		D: "\\(\\frac{10}{909}\\)",
		E: "\\(\\frac{100}{909}\\)",
		Correct: "E"
	},
	{
		name: "SM2016iiADF30",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Un hombre y una mujer pueden hacer un trabajo en 12 días. Después de haber trabajado juntos durante 6 días, la mujer se retira y el hombre termina lo que falta del trabajo en 10 días. ¿En cuántos días la mujer sola puede realizar todo el trabajo?",
		A: "32",
		B: "34",
		C: "29",
		D: "30",
		E: "28",
		Correct: "D"
	},
	{
		name: "SM2016iiADF31",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "La diferencia positiva de los valores de x que satisfacen la ecuación (\\(\\mathrm{x^2}\\) - 5x + 12)! = 720 es",
		A: "1",
		B: "2",
		C: "3",
		D: "5",
		E: "6",
		Correct: "A"
	},
	{
		name: "SM2016iiADF32",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Dado el sistema<br>\\(\\begin{cases} 3x + 2y = m + 2\\\\ 2x - 3y = 2m - 1\\end{cases}\\)<br>¿qué valor debe tomar m para que el valor de x sea el doble del valor de y en el sistema?",
		A: "3/2",
		B: "2/5",
		C: "2/3",
		D: "5/3",
		E: "4/3",
		Correct: "C"
	},
	{
		name: "SM2016iiADF33",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Halle todos los valores k \\(\\in\\Re\\), tales que para todo número real x se cumpla \\(\\mathrm{x^2}\\) + 4x + k > ",
		A: "k < 4",
		B: "k > 4",
		C: "k \\(\\in\\) [-1.1]",
		D: "k \\(\\in\\) <-4,4>",
		E: "k > 0",
		Correct: "B"
	},
	{
		name: "SM2016iiADF34",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si \\(\\mathrm{x^y}\\) = 1, x > 0, x ≠ 1, e y + x = 4,<br>halle \\(\\mathrm{\\sqrt{\\frac{y^x + x^2 + y ^2}{2x}}}\\)",
		A: "2",
		B: "1",
		C: "0",
		D: "4",
		E: "\\(\\sqrt{2}\\)",
		Correct: "E"
	},
	{
		name: "SM2016iiADF35",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si {\\(a\\) - 1, \\(a\\)} es el conjunto solución de la ecuación \\(\\mathrm{2x^2}\\) - (P + 3) x - P + \\(\\frac{5}{4}\\) = 0, halle el producto de todos los posibles valores de P.",
		A: "9",
		B: "-8",
		C: "-5",
		D: "14",
		E: "-10",
		Correct: "C"
	},
	{
		name: "SM2016iiADF36",
		subject: "MA",
		sub_subject: "",
		prompt: "En la figura, ABCD es un cuadrado inscrito en la circunferencia de centro O. Halle la razón entre el área sombreada y el área del círculo.",
		image: false,
		question: "",
		A: "\\(\\frac{3}{8}\\)",
		B: "\\(\\frac{3}{4}\\)",
		C: "\\(\\frac{3}{10}\\)",
		D: "\\(\\frac{3}{5}\\)",
		E: "\\(\\frac{3}{7}\\)",
		Correct: "A"
	},
	{
		name: "SM2016iiADF37",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En una circunferencia de radio igual a 4 cm se inscribe un cuadrado y sobre los lados de este y hacia el exterior se construyen triángulos equiláteros. Halle el área de la estrella formada.",
		A: "32(2 + \\(\\sqrt(3)\\)) \\(\\mathrm{cm^2}\\)",
		B: "32(1 + \\(\\sqrt(3)\\)) \\(\\mathrm{cm^2}\\)",
		C: "32\\(\\sqrt(3)\\) \\(\\mathrm{cm^2}\\)",
		D: "30(1 + \\(\\sqrt(3)\\)) \\(\\mathrm{cm^2}\\)",
		E: "16(1 + \\(\\sqrt(3)\\)) \\(\\mathrm{cm^2}\\)",
		Correct: "B"
	},
	{
		name: "SM2016iiADF38",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura, M y N son puntos medios de \\(\\mathrm{\\overline{PR}}\\) y \\(\\mathrm{\\overline{LS}}\\), respectivamente, y PO = RS. Halle la medida del ángulo \\(a\\).",
		A: "20°",
		B: "23°",
		C: "21°",
		D: "24°",
		E: "22°",
		Correct: "E"
	},
	{
		name: "SM2016iiADF39",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En el plano cartesiano de la figura, los segmentos \\(\\mathrm{\\overline{OB}}\\) y \\(\\mathrm{\\overline{OA}}\\) miden cada uno 3\\(\\sqrt{10}\\) u, donde los puntos A y B están en la parábola de ecuación y = \\(\\mathrm{x^2}\\). ¿Cuál es el área de la región triangular AOB?",
		A: "21 \\(\\mathrm{u^2}\\)",
		B: "24 \\(\\mathrm{u^2}\\)",
		C: "27 \\(\\mathrm{u^2}\\)",
		D: "18 \\(\\mathrm{u^2}\\)",
		E: "30 \\(\\mathrm{u^2}\\)",
		Correct: "C"
	},
	{
		name: "SM2016iiADF40",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura, cada sector circular tiene la mitad de la medida del ángulo y la mitad del radio del sector circular izquierdo adyacente. Halle la suma de las áreas de todos los sectores circulares formados si van en una sucesión infinita.",
		A: "\\(\\frac{8}{7}\\) θ\\(\\mathrm{R^2m^2}\\)",
		B: "\\(\\frac{5}{17}\\) θ\\(\\mathrm{R^2m^2}\\)",
		C: "\\(\\frac{5}{7}\\) θ\\(\\mathrm{R^2m^2}\\)",
		D: "\\(\\frac{4}{7}\\) θ\\(\\mathrm{R^2m^2}\\)",
		E: "\\(\\mathrm{\\frac{θR^2}{2}}\\) \\(\\mathrm{m^2}\\)",
		Correct: "D"
	},
	{
		name: "SM2016iiADF41",
		subject: "MK",
		sub_subject: "Algebra",
		prompt: false,
		image: false,
		question: "Un fabricante de bombillas gana 0,3 soles por cada bombilla buena que sale de la fábrica, pero pierde 0,4 soles por cada una que salga defec- tuosa. Un día en el que fabricó 2100 bombillas obtuvo un beneficio de 484,4 soles. Halle la di- ferencia entre el número de bombillas buenas y el número de bombillas defectuosas que fabricó ese día.",
		A: "1864 bombillas",
		B: "1684 bombillas",
		C: "1468 bombillas",
		D: "1662 bombillas",
		E: "1478 bombillas",
		Correct: "B"
	},
	{
		name: "SM2016iiADF42",
		subject: "MK",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En una carrera de 200 m planos, Alberto le da a José una ventaja de 40 m para llegar simultá- neamente a la meta, y en una carrera de 100 m planos, José le da a Luis una ventaja de 10 m. Sabiendo que las velocidades de los 3 es cons- tante en todas las carreras, ¿cuántos metros de ventaja debe darle Alberto a Luis en una carrera de 400 m planos para llegar simultáneamente a la meta?",
		A: "110 m",
		B: "288 m",
		C: "122 m",
		D: "112 m",
		E: "108 m",
		Correct: "D"
	},
	{
		name: "SM2016iiADF43",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Reduzca la expresión [(p\(\\Rightarrow\\sim\\)q)\\(\\land\)(q\\(\\Rightarrow\\sim\\)p)]\\(\\Rightarrow\\sim\\)(\\(\\sim\\)p\\(\\lor\\)\\(\\sim\\)q) y elija la forma equivalente",
		A: "p \\(\\lor\\) q",
		B: "\\(\\sim\\)(p \\(\\land\\)q)",
		C: "p \\(\\land\\) q",
		D: "\\(\\sim\\)(p \\(\\lor\\)q)",
		E: "\\(\\sim\\)p \\(\\land\\)q",
		Correct: "C"
	},
	{
		name: "SM2016iiADF44",
		subject: "MK",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Un equipo de investigación conformado por los profesores A, B y C obtuvo 100 datos numéricos:<br>\\(x_1,x_2,x_3,x_4,...,x_100<br>El profesor A obtuvo 10 como promedio de todos estos datos. El profesor B observó que su colega no había tomado en cuenta el dato \\(X_{10}\\) en la suma, calcula nuevamente el promedio y obtiene 12 como resultado. El profesor C notó que su colega B olvidó sumar el dato \\(X_{50}\\) al calcular el promedio. Sabiendo que \\(X_{10}+X_{50}\\) = 20, encuentre el promedio correcto.",
		A: "11,1",
		B: "22,2",
		C: "10,0",
		D: "11,0",
		E: "11,2",
		Correct: "A"
	},
	{
		name: "SM2016iiADF45",
		subject: "MK",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Las raíces de la ecuación \\(\\mathrm{2x^2}\\)–bx+c=0 suman 6 y el producto de las raíces de la ecuación \\(\\mathrm{bx^2}\\)−3cx+\\(\\mathrm{\\frac{bc}{4}}\\)=0 es 4. Halle la suma de las 4 raíces de ambas ecuaciones si se sabe que b≠0 y c≠0.",
		A: "-10",
		B: "-2",
		C: "2",
		D: "8",
		E: "10",
		Correct: "E"
	},
	{
		name: "SM2016iiADF46",
		subject: "MK",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Halle la suma de las soluciones de la ecuación 1+logx+log(x-1)=log60.",
		A: "1",
		B: "3",
		C: "2",
		D: "5",
		E: "4",
		Correct: "B"
	},
	{
		name: "SM2016iiADF47",
		subject: "MK",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Halle D = \\(\\begin{vmatrix}\\alpha & \\beta & \\gamma \\\\ \\beta & \\gamma & \\alpha \\\\ \\gamma & \\alpha & \\beta \\end{vmatrix}\\textrm{, si } \\alpha\\textrm{, } \\beta\\textrm{ y } \\gamma\\) son las raíces de la ecuación cúbica \\(\\mathrm{x^3}\\)–5x+6=0.",
		A: "1",
		B: "2",
		C: "-1",
		D: "3",
		E: "0",
		Correct: "E"
	},
	{
		name: "SM2016iiADF48",
		subject: "MK",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Dados los polinomios con coeficientes reales<br>P(x)=\\(\\mathrm{x^14}\\)–2\\(\\mathrm{x^13}\\)+a\\(\\mathrm{x^2}\\)+bx–6<br>Q(x)=2\\(\\mathrm{x^3}\\)–9\\(\\mathrm{x^2}\\)+13x–6<br>Se sabe que MCD (P(x), Q(x))=(x–\\(\\mathrm{r_1}\\))(x–\\(\\mathrm{r_2}\\)), donde \\(\\mathrm{r_1}\\) y \\(\\mathrm{r_2}\\) son números enteros. Halle (b–a)",
		A: "-15",
		B: "15",
		C: "7",
		D: "12",
		E: "-7",
		Correct: "B"
	},
	{
		name: "SM2016iiADF49",
		subject: "MK",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura, la sombra del edificio más grande mide PQ = 12 m, mientras que el edificio pequeño tiene una sombra de AB = 4 m y una altura de BC = 10 m. Halle la altura del edificio más grande.",
		A: "35 m",
		B: "40 m",
		C: "30 m",
		D: "50 m",
		E: "45 m",
		Correct: "C"
	},
	{
		name: "SM2016iiADF50",
		subject: "MK",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "¿Cuál es el precio de un cajón de madera con tapa superior en forma de un paralelepípedo, cuyas dimensiones son 60 cm x 40 cm x 50 cm, si el metro cuadrado de madera cuesta 18 euros?",
		A: "26,64 euros",
		B: "25,53 euros",
		C: "27,75 euros",
		D: "26,33 euros",
		E: "27,42 euros",
		Correct: "A"
	},
	{
		name: "SM2016iiADF51",
		subject: "MK",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El chocolate sobrante de una chocolatada infantil es la mitad de la capacidad de una olla cilíndrica de 50 cm de diámetro por 48 cm de altura. Una integrante del comité organizador coloca el chocolate sobrante en otra olla cilíndrica de 40 cm de diámetro. ¿Cuál es la diferencia de los niveles de altura que alcanzó el chocolate sobrante en ambas ollas?",
		A: "37,5 cm",
		B: "6\\(\\mathrm{\\sqrt{2}}\\) cm",
		C: "12,5 cm",
		D: "13,5 cm",
		E: "5\\(\\mathrm{\\sqrt{2}}\\) cm",
		Correct: "D"
	},
	{
		name: "SM2016iiADF52",
		subject: "MK",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En un recipiente cónico, lleno de agua, el radio de la base mide 2 cm y la altura mide 3 cm. Si se vierte el contenido en otro recipiente cilíndrico y vacío, cuya base y altura son las mismas que la del cono, determine la altura alcanzada por el líquido en el recipiente cilíndrico.",
		A: "2 cm",
		B: "\\(\\frac{2}{3}\\) cm",
		C: "π cm",
		D: "\\(\\mathrm{\\frac{π}{3}}\\)",
		E: "1 cm",
		Correct: "E"
	},
	{
		name: "SM2016iiADF53",
		subject: "MK",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El piloto de un avión en vuelo observa la cima de la torre de control del aeropuerto a 5 km de distancia con un ángulo de depresión de 30°. Si la torre de control tiene una altura de 50 m, ¿a qué altura se encuentra el avión en ese instante?",
		A: "2550 m",
		B: "2550 km",
		C: "30 m",
		D: "30 km",
		E: "2250 m",
		Correct: "A"
	},
    {
		name: "SM2016iiADF54",
		subject: "MK",
		sub_subject: "Trigonometry",
		prompt: false,
		image: false,
		question: "La figura muestra un rectángulo ABCD dividido en tres cuadrados iguales y los ángulos \\(α = m\\widehat{BAC}\\) y \\(β= m\\widehat{BAE}\\). Halle el valor exacto de tg(α+β)",
		A: "2",
		B: "1",
		C: "\\(\\frac{-3}{2}\\)",
		D: "\\(\\frac{3}{4}\\)",
		E: "\\(\\frac{4}{3}\\)",
		Correct: "B"
	},
	{
		name: "SM2016iiADF55",
		subject: "MK",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "De la figura, calcule \\(\\mathrm{M = \\frac{\\cos{α}}{\\cos{β}} + b\\times\\cot{α}\\times\\sec{β} + 1 }\\)",
		A: "\\(\\mathrm{\\sqrt{a^2 + b^2}}\\)",
		B: "\\(\\mathrm{\\sqrt{a^2 + 2b^2}}\\)",
		C: "\\(\\mathrm{-\\sqrt{a^2 + b^2}}\\)",
		D: "\\(\\mathrm{\\sqrt{a^2 + \\frac{b^2}{2}}}\\)",
		E: "\\(\\mathrm{2\\sqrt{a^2 + b^2}}\\)",
		Correct: "C"
	},
	{
		name: "SM2016iiADF56",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "¿Cuál de las siguientes alternativas presenta tres palabras con tildación adecuada?",
		A: "Día, derruído, odorífero",
		B: "Resúmen, páramo, hincapié",
		C: "Túnel, bíceps, kión",
		D: "Bonsái, criptón, cúidate",
		E: "Cráter, plexiglás, preínca",
		Correct: "E"
	},
	{
		name: "SM2016iiADF57",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Durante el reciente proceso electoral, un candidato dijo que tenía plata como cancha. La expresión destacada en el enunciado anterior posee un sentido",
		A: "literal.",
		B: "peyorativo.",
		C: "connotativo.",
		D: "ameliorativo.",
		E: "etimológico.",
		Correct: "C"
	},
	{
		name: "SM2016iiADF58",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Elija el par de palabras que complete adecuadamente el sentido del enunciado. El acusado _______________ de sus ideas científicas debido a las fuertes presiones de las autoridades. Sin embargo, esa _______________ no reflejaba su real convicción.",
		A: "desertó — omisión",
		B: "abjuró — renuncia",
		C: "dimitió — expresión",
		D: "abdicó — abstención",
		E: "perjuró — deserción",
		Correct: "B"
	},
	{
		name: "SM2016iiADF59",
		subject: "Lenguage",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Elija la secuencia que muestra el emparejamiento correcto entre la palabra destacada y el cambio morfológico que experimenta.<br>I. Compraron un portapapeles.<br>II. Recibió un trato inhumano.<br>III. Celebraron su quinceañero.<br>IV. Iremos al cine el sábado.<br>a. Derivación<br>b. Composición<br>c. Acortamiento<br>d. Parasintesis",
		A: "Ib,IIa,IIId,IVc",
		B: "Ia,IIb,IIIc,IVd",
		C: "Id,IIc,IIIb,IVa",
		D: "Ib,IIc,IIId,IVa",
		E: "Ic,IIb,IIIa,IVd",
		Correct: "A"
	},
	{
		name: "SM2016iiADF60",
		subject: "Lenguage",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "¿Cuál de los siguientes enunciados muestra un empleo correcto de letras mayúsculas?",
		A: "Ernesto es Tauro y Rubén, Capricornio.",
		B: "Martín Adán escribió La Casa de Cartón.",
		C: "Celebró el Año Nuevo en Los Ángeles.",
		D: "Chincha se encuentra al Sur de Lima.",
		E: "Había adquirido la Enfermedad de Alzheimer",
		Correct: "C"
	},
	{
		name: "SM2016iiADF61",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Evalúe detenidamente las oraciones que aparecen a continuación; luego, seleccione la opción que contiene proposiciones subordinadas sustantivas.<br>1. Ayer en la oficina atendí hasta muy tarde a quienes me lo pidieron.<br>2. Aquellos árboles que se reflejan en el lago son demasiado frondosos.<br>3. Josefina, entre lágrimas, me dijo palabras tan bellas que nunca olvidaré.<br>4. Aquel futbolista se ha fracturado el tobillo; por tanto, no podrá jugar.<br>5. No importa que ellos se vayan a las ciudades más lejanas del mundo.",
		A: "1 y 2",
		B: "3 y 4",
		C: "4 y 5",
		D: "2 y 3",
		E: "1 y 5",
		Correct: "E"
	},
	{
		name: "SM2016iiADF62",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Elija la alternativa donde el enunciado puntuado muestre un conector con valor ilativo.",
		A: "Hablando del cumpleañero, a propósi- to, hoy no vino a trabajar.",
		B: "Pisó el acelerador en una zona colegial; por ende, fue multado.",
		C: "Por cierto, Antonio, no olvides apagar las luces antes de salir.",
		D: "En cualquier caso, paga en el banco y muéstranos tu recibo.",
		E: "Me ha dicho que debo ser justo; ahora, ¿él es justo conmigo?",
		Correct: "B"
	},
	{
		name: "SM2016iiADF63",
		subject: "Literature",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En los siguientes versos de Gustavo Adolfo Bécquer, ¿qué figura literaria predomina?<br><i>Del salón en el ángulo oscuro de su dueño tal vez olvidada silenciosa y cubierta de polvo veíase el arpa.</i>",
		A: "Anáfora",
		B: "Hipérbole",
		C: "Hipérbaton",
		D: "Epíteto",
		E: "Metáfora",
		Correct: "C"
	},
	{
		name: "SM2016iiADF64",
		subject: "Literature",
		sub_subject: "",
		prompt: false,
		image: false,
		question: 'La denominada “novela de la tierra” constituyó identidades locales y representó el habla particu- lar de los hombres rurales. Esta expresión literaria se inscribe en el código del',
		A: "simbolismo",
		B: "indianismo",
		C: "vanguardismo",
		D: "modernismo",
		E: "regionalismo",
		Correct: "E"
	},
	{
		name: "SM2016iiADF65",
		subject: "Literature",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "¿Cuáles de las siguientes características son propias de los yaravíes de Mariano Melgar?<br>I. Amor hacia lo autóctono<br>II. Formas literarias modernistas<br>III. Libre expresión del sentimiento<br>IV. Ruptura del orden gramatical",
		A: "II y IV",
		B: "III y IV",
		C: "I y II",
		D: "I y III",
		E: "I y IV",
		Correct: "D"
	},
	{
		name: "SM2016iiADF66",
		subject: "Psychology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Todo ser humano inicia su proceso de socialización adquiriendo informaciones de índole emocional y cultural que, con el transcurrir del tiempo, constituirán la base de la formación de su personalidad. Estas informaciones básicas iniciales son brindadas por la",
		A: "familia.",
		B: "sociedad.",
		C: "escuela.",
		D: "comunidad.",
		E: "vecindad.",
		Correct: "A"
	},
	{
		name: "SM2016iiADF67",
		subject: "Psychology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El proceso de lectura que usted viene realizando se inició con el reconocimiento de las letras que se encuentran grabadas en esta hoja de papel blanco. Este reconocimiento se produjo gracias al principio perceptual denominado",
		A: "superposición",
		B: "input - output.",
		C: "buena forma.",
		D: "parte - todo.",
		E: "figura - fondo.",
		Correct: "E"
	},
	{
		name: "SM2016iiADF68",
		subject: "Psychology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Cuando se hace sonar un timbre y se toca casi inmediatamente la mejilla derecha de un infante, este, por reflejo, voltea la cabeza en dirección a la caricia. Después de repetir varias veces dichas acciones, el infante voltea su cabeza hacia la derecha tan pronto como escucha el sonido del timbre. En este caso, el estímulo condicionado es",
		A: "el voltear de la cabeza.",
		B: "el sonido del timbre.",
		C: "la presencia del timbre.",
		D: "el movimiento de los ojos.",
		E: "la acción de acariciar.",
		Correct: "B"
	},
	{
		name: "SM2016iiADF69",
		subject: "Civic Education",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Cuatro sospechosos de realizar robos en horas de la madrugada en un vecindario del Cono Norte de Lima son perseguidos y cercados por los vecinos en el interior de una gran fábrica de productos metalmecánicos. Como los sospechosos ofrecen resistencia, interviene el personal de seguridad privada que custodia la factoría a fin de reducirlos. Posteriormente comparece en el lugar el serenazgo municipal con un gran número de efectivos. ¿Quiénes estarían legitimados para realizar el arresto de los presuntos autores de los robos?",
		A: "El Ministerio Público",
		B: "La policía particular",
		C: "La Policía Nacional",
		D: "El serenazgo municipal",
		E: "La junta de vecinos",
		Correct: "E"
	},
	{
		name: "SM2016iiADF70",
		subject: "Civic Education",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Algunos pensadores sostienen que el fundamento de los derechos humanos se encuentra en nuestra capacidad de pensar, hablar y comunicarnos. Esto significa que las personas estamos dotadas de racionalidad, que somos seres que argumentamos, intercambiamos puntos de vista, trabajamos en equipo, etc. Por ello, los derechos humanos cobran vigencia cuando consideramos que",
		A: "toda persona es un interlocutor válido capaz de expresar su punto de vista sobre el bien y la justicia.",
		B: "todos los seres humanos somos parte de una misma especie y tenemos las mismas necesidades.",
		C: "algunas personas carecen de la habilidad suficiente para ser tomadas en cuenta en un debate.",
		D: "la dignidad de los seres humanos está justificada por la idea de haber sido creados a imagen de Dios.",
		E: "está prohibida cualquier ofensa contra nuestros semejantes, pues toda persona es nuestro prójimo.",
		Correct: "A"
	},
	{
		name: "SM2016iiADF71",
		subject: "Peruvian History",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Al culminar el Pleistoceno en el área andina, aproximadamente hace unos 6000 años a. C., algunos grupos humanos, como Guitarrero y Chilca, desarrollaron la horticultura. Como consecuencia de lo anterior, en este periodo de la historia andina se",
		A: "erigieron las primeras llactas.",
		B: "establecieron las primeras aldeas.",
		C: "consolidaron las primeras civilizaciones.",
		D: "construyeron andenes y camellones.",
		E: "domesticaron plantas y animales.",
		Correct: "B"
	},
	{
		name: "SM2016iiADF72",
		subject: "Peruvian History",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Para mantener el monopolio comercial con sus colonias en América, España estableció una flota de galeones con el fin de",
		A: "evitar el contrabando de los ingleses.",
		B: "mejorar la producción de oro y plata.",
		C: "agilizar la exportación e importación.",
		D: "defenderse de piratas y corsarios.",
		E: "generar mayores ingresos para la Corona.",
		Correct: "D"
	},
	{
		name: "SM2016iiADF73",
		subject: "Universal History",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "La domesticación de plantas y animales, así como el perfeccionamiento de los instrumentos de trabajo hechos de piedra durante el Neolítico trajeron como consecuencia",
		A: "el surgimiento de las ciudades.",
		B: "la aparición de la escritura alfabética.",
		C: "la organización social en bandas.",
		D: "el inicio del nomadismo intensivo.",
		E: "el surgimiento de la propiedad privada.",
		Correct: "E"
	},
	{
		name: "SM2016iiADF74",
		subject: "Universal History",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Las culturas de Egipto y Mesopotamia, al inventar la escritura y alcanzar un alto grado de desarrollo en el manejo hidráulico, pudieron desarrollar una",
		A: "sociedad de pobladores técnicos formalmente iguales entre sí.",
		B: "débil burocracia que solamente administraba aspectos religiosos.",
		C: "sociedad comercial que se fundaba en los principios del libre mercado.",
		D: "agricultura de excedentes que posibilitó grandes obras arquitectónicas.",
		E: "fuerte casta religiosa que desafiaba a los reyes por su gran despotismo.",
		Correct: "D"
	},
	{
		name: "SM2016iiADF75",
		subject: "Geography",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Al realizar un trabajo en equipo sobre la atmósfera terrestre, descubrimos que su distribución no es uniforme y que cada capa presenta características propias. ¿Cómo se denomina el estrato de la atmósfera donde ocurren la mayoría de los fenómenos del tiempo y clima?",
		A: "Troposfera",
		B: "Estratósfera",
		C: "Mesosfera",
		D: "Termósfera",
		E: "Exósfera",
		Correct: "A"
	},
	{
		name: "SM2016iiADF76",
		subject: "Geography",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En el Perú se han elaborado diversas clasificaciones regionales según las variables físicas, climáticas, altitudinales, biológicas, hidrográficas, entre otras. Teniendo en cuenta la clasificación de Antonio Brack, ¿cuál es la ecorregión donde predominan las cactáceas, el mito, el huanarpo, el huarango y los pajonales",
		A: "Sabana de palmeras",
		B: "Serranía esteparia",
		C: "Costa desértica",
		D: "Bosque seco",
		E: "Bosque tropical",
		Correct: "B"
	},
	{
		name: "SM2016iiADF77",
		subject: "Economy",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Durante la temporada de verano, la Carretera Central que une las regiones Lima y Junín está afectada varios días por los huaicos. Así, los productos alimenticios naturales que llegan a Lima desde Junín quedan apilados en los camiones estacionados, en algún tramo de la carretera, a la espera de que se reanude el tránsito. La secuencia económica que se originará en los centros mayoristas de Lima por los productos en la carretera afectada es la siguiente:",
		A: "Escasez → Incremento del precio",
		B: "Incremento del precio → Escasez",
		C: "Escasez → Decremento del precio",
		D: "Decremento del precio → Escasez",
		E: "Abundancia → Incremento del precio",
		Correct: "A"
	},
	{
		name: "SM2016iiADF78",
		subject: "Geography",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Durante el siglo XX, el crecimiento económico del Perú estuvo afectado por un conjunto de acontecimientos externos e internos: Crac del 29, crisis financieras, subida del precio de las materias primas, descubrimientos tecnológicos, guerras mundiales, cambios internos de política económica, terremotos, entre otros. Todo lo anterior es sintetizado, anualmente, en un indicador económico global denominado",
		A: "balanza comercial.",
		B: "inversión extranjera.",
		C: "ingreso nacional.",
		D: "inversión bruta.",
		E: "producto bruto interno.",
		Correct: "E"
	},
	{
		name: "SM2016iiADF79-80",
		subject: "Philosophy",
		sub_subject: "",
		prompt: 'Lea el texto y, a continuación, responda las preguntas 79 y 80.<br>La habilidad escéptica es poner en oposición las cosas que aparecen y se piensan de cualquier manera posible, una habilidad a partir de la cual, debido a la igual fuerza de las cosas y los argumentos que están en oposición, llegamos primeramente a una suspensión del juicio y luego a estar libres de preocupaciones.<br><font size="2"<Sexto Empírico, <i>Esbozos pirrónicos</i>, 1.8.</font>',
		image: false,
		question: "Del texto se infiere que los escépticos",
		A: "se preocupan más por la teorización y la especulación.",
		B: "nunca estuvieron interesados en la aplicación de su filosofía.",
		C: "suspenden el juicio por medio de la equipolencia.",
		D: "nunca podrían liberarse de todas sus preocupaciones.",
		E: "buscaban demostrar la falsedad de todas las creencias.",
		Correct: "C"
	},
	{
		name: "SM2016iiADF80",
		subject: "Philosophy",
		sub_subject: "",
		prompt: "SM2016iiADF79-80",
		image: false,
		question: "A partir de la lectura, se infiere que el escepticismo",
		A: "se caracteriza más como una destreza que como una doctrina.",
		B: "estaba fundamentado en argumentos racionales irrefutables.",
		C: "exigía un entrenamiento conceptual semejante a un ejercicio espiritual.",
		D: "constituía un sistema orientado a la justificación de las creencias.",
		E: "concebía a la filosofía como una actividad carente de sentido.",
		Correct: "A"
	},
	{
		name: "SM2016iiADF81",
		subject: "Physics",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Oír y hablar son cosas extremadamente importantes para los seres humanos. Debido a esto, podemos detectar, emitir e interpretar ondas sonoras con diferentes propiedades físicas. Por ejemplo, podemos escuchar sonidos a una frecuencia de 1000 Hz con una intensidad a partir de \\(10^{-12}\\) W/\\(\\mathrm{m^2}\\), mientras que hablar nos permite, en un tono de conversación normal, emitir una potencia sonora de \\(10^{-3}\\) W. En este contexto, ¿cuál es la afirmación correcta?",
		A: "Las ondas sonoras son ondas mecánicas transversales.",
		B: "Los seres humanos pueden emitir sonidos de 20 Hz a 20 000 Hz.",
		C: "Los seres humanos pueden escuchar sonidos de cualquier frecuencia.",
		D: "La unidad bel (B) no mide la intensidad del nivel de sonido.",
		E: "Los sonidos mayores a 1,0 W/\\(\\mathrm{m^2}\\) causan dolor en el oído humano.",
		Correct: "E"
	},
	{
		name: "SM2016iiADF82",
		subject: "Physics",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "La emisión de fotoelectrones por la iluminación con luz de una determinada frecuencia es conocidas como el efecto fotoeléctrico. Sin embargo, para observar el efecto existe un umbral de radiación electromagnética llamado función trabajo. Entonces, si la función trabajo de una placa de tungsteno es 4,55 eV, ¿cuál es la energía cinética máxima de los fotoelectrones expulsados cuando se aplica una radiación con energía de 4,96 eV?",
		A: "0,82 eV",
		B: "0,41 eV",
		C: "0,21 eV",
		D: "0,53 eV",
		E: "0,64 eV",
		Correct: "B"
	},
	{
		name: "SM2016iiADF83",
		subject: "Physics",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Cuando se practica el buceo, hay que distinguir dos tipos de presión: la atmosférica (el peso del aire sobre la superficie del agua) y la hidrostática (el peso del agua sobre el buzo). La suma de las dos presiones parciales da como resultado la presión absoluta, que es la que nos afecta. Entonces, si un buzo se sumergiera a 20,0 m de profundidad en el mar, ¿cuál sería su presión absoluta?<br>Use: \\(\\rho_{agua} = 1,18\\times10^3 \\mathrm{kg/m^3}\\); \\(\\mathrm{P_{atm}}\\) 101 kPa; g = 10 m/\\(\\mathrm{s^2}\\)",
		A: "338 kPa",
		B: "339 kPa",
		C: "335 kPA",
		D: "337 kPa",
		E: "336 kPa",
		Correct: "D"
	},
	{
		name: "SM2016iiADF84",
		subject: "Physics",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Un gráfico es la representación de datos numéricos que permiten analizar el comportamiento de cierto proceso o efecto, facilitando la obtención de conclusiones a profesionales de diversas áreas. De este modo, si el siguiente gráfico nos muestra la deformación de un resorte por una fuerza externa, ¿cuál será el trabajo necesario para deformarlo desde 1,0 cm hasta 6,0 cm?",
		A: "2,0 J",
		B: "3,0 J",
		C: "1,0 J",
		D: "4,0 J",
		E: "5,0 J",
		Correct: "C"
	},
	{
		name: "SM2016iiADF85",
		subject: "Physics",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Aunque va directamente en contra de lo que nos sugiere la intuición, la distancia de frenado de un cuerpo no depende de su masa, sino fundamentalmente de su rapidez y del coeficiente de rozamiento entre el cuerpo y la superficie sobre la que se mueve. En este contexto, encuentre el coeficiente de fricción de un cuerpo de 2,0 kg que se mueve a 25,0 m/s sobre una superficie rugosa y que se detiene después de desplazarse 60,0 m. (Use: g=10 m/\\(\\mathrm{s^2}\\)).",
		A: "0,62",
		B: "0,52",
		C: "0,42",
		D: "0,72",
		E: "0,32",
		Correct: "B"
	},
	{
		name: "SM2016iiADF86",
		subject: "Chemistry",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "La atmósfera es la capa gaseosa que envuelve a un planeta. En la Tierra está compuesta por una mezcla de gases llamada aire, cuya composición en dióxido de carbono (C\\(\\mathrm{O_2}\\)) es el 0,03% en volumen. El C\\(\\mathrm{O_2}\\) es importante para producir materia orgánica mediante la fotosíntesis y es el responsable del efecto invernadero. Calcule el volumen de C\\(\\mathrm{O_2}\\), en litros, que hay en un ambiente cerrado de 60 \\(\\mathrm{m^3}\\).",
		A: "\\(18,0 \times 10^{-4}\\)",
		B: "\\(20,0 \times 10^{4}\\)",
		C: "\\(20,0 \times 10^{1}\\)",
		D: "\\(18,0 \times 10^{0}\\)",
		E: "\\(18,0 \times 10^{-3}\\)",
		Correct: "D"
	},
	{
		name: "SM2016iiADF87",
		subject: "Chemistry",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Para representar un elemento se utiliza un símbolo y dos números: número de masa (A) y número atómico (Z). Si se sabe que en un elemento neutro, el número atómico es igual al número de electrones, la distribución electrónica del Mg (Z=12) y del Ar (Z=18) en el último nivel de energía, respectivamente, presenta",
		A: "2 y 8 electrones.",
		B: "2 y 2 electrones.",
		C: "1 y 8 electrones.",
		D: "2 y 6 electrones.",
		E: "3 y 3 electrones.",
		Correct: "A"
	},
	{
		name: "SM2016iiADF88",
		subject: "Chemistry",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El hidróxido de sodio (NaOH), también conocido como soda cáustica, se emplea en los hogares para desatorar cañerías y limpiar la grasa de hornos y ollas.<br>Determine qué cambios ocurren en la reacción \\(\\mathrm{2Na_{(s)} + H_2O_{(l)} \\rightarrow 2NaOH_{(ac)} + H_{2(g)}}\\)<br>I. Oxidación<br>II. Sustitución<br>III. Descomposición<br>IV. Neutralización<br>V. Reducción",
		A: "II, III y V",
		B: "I, II y IV",
		C: "I, II y V",
		D: "I, III y V",
		E: "I, IV y V",
		Correct: "C"
	},
	{
		name: "SM2016iiADF89",
		subject: "Chemistry",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El metanal, también conocido como formaldehído (HCHO), en solución acuosa al 40%, se conoce como formol. Este es utilizado como antiséptico y conservante de tejidos animales. Calcule el peso, en gramos, del metanal obtenido al hacer reaccionar 1,5 mol de metanol con suficiente cantidad de oxígeno según: <br>&emsp;\\(\\ce{2CH3OH + O2 \\rightarrow 2HCHO + 2H2O}\\)<br>Dato: \\(\\ce{PF_{CH_3OH} : 32, PF_{HCHO} : 30}\\)",
		A: "30",
		B: "1,5",
		C: "15",
		D: "45",
		E: "60",
		Correct: "D"
	},
	{
		name: "SM2016iiADF90",
		subject: "Chemistry",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Todas las reacciones tienen una determinada velocidad y mecanismo. Estas logran el equilibrio entre reactivos y productos cuando",
		A: "las velocidades de reacción directa e inversa se igualan.",
		B: "el número de moles de reactivos y productos son iguales.",
		C: "la masa total de las sustancias involucradas no cambia.",
		D: "en la mezcla ya no se produce ninguna reacción química.",
		E: "la temperatura y la presión del sistema permanecen inalteradas.",
		Correct: "A"
	},
	{
		name: "SM2016iiADF91",
		subject: "Biology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Los virus que infectan bacterias se denominan bacteriófagos. En un laboratorio de microbiología se están modificando genéticamente algunas bacterias, haciendo uso de la transferencia de información genética entre ellas a través de bacteriófagos. Este proceso se conoce como",
		A: "transformación.",
		B: "conjugación.",
		C: "fecundación.",
		D: "transducción.",
		E: "transcripción.",
		Correct: "D"
	},
	{
		name: "SM2016iiADF92",
		subject: "Biology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Los gangliósidos son lípidos que se degradan en una organela de las neuronas para ser reciclados para la célula durante el desarrollo temprano del ser humano. En la enfermedad de Tay-Sachs, estos lípidos se almacenan al no poder ser digeridos por una enzima específica, la cual lleva rápidamente a la degeneración y a la muerte neuronal, y el individuo puede morir antes de alcanzar los 5 años de edad. De acuerdo con lo enunciado, esta patología se debe al mal funcionamiento de las enzimas presentes en",
		A: "los ribosomas.",
		B: "los lisosomas.",
		C: "las mitocondrias.",
		D: "los peroxisomas.",
		E: "el aparato de Golgi.",
		Correct: "B"
	},
	{
		name: "SM2016iiADF93",
		subject: "Biology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Las enzimas presentes en el retículo endoplasmático liso han sido bloqueadas por acción de un fármaco en experimentación. Uno de los primeros efectos negativos se refleja en la estructura molecular de la membrana citoplasmática, debido a que ha disminuido la síntesis de",
		A: "proteínas integrales.",
		B: "carbohidratos.",
		C: "proteínas periféricas.",
		D: "fosfolípidos.",
		E: "glucoproteínas.",
		Correct: "D"
	},
	{
		name: "SM2016iiADF94",
		subject: "Biology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Dentro de los tilacoides de los cloroplastos encontramos los fotosistemas I y II. El fotosistema II está constituido por la clorofila P680 que es excitada por la luz, capta la energía del fotón y emite 2\\(\\mathrm{e^-}\\) que pasarán a través de una cadena de moléculas proteínicas denominadas transportadoras. Al moverse de un transportador a otro, los electrones liberan energía, lo que permite la síntesis de",
		A: "CTP.",
		B: "NADP\\(\\mathrm{H_2}\\).",
		C: "ATP.",
		D: "\\(\\mathrm{NADH + H^+}\\).",
		E: "GTP.",
		Correct: "C"
	},
	{
		name: "SM2016iiADF95",
		subject: "Biology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En los seres humanos, los eritrocitos o glóbulos rojos son células pequeñas de 7 a 8 micras y son muy flexibles. Cumplen la función principal de transportar el \\(\\mathrm{O_2}\\) a todas las células del organismo e intercambiarlo con el anhídrido carbónico producto de la respiración celular. ¿Qué estructura celular le permite la flexibilidad necesaria para circular por los capilares más delgados del cuerpo?",
		A: "Los microtubulos",
		B: "El citoesqueleto",
		C: "El glucocálix",
		D: "El exoesqueleto",
		E: "La elastina",
		Correct: "B"
	},
	{
		name: "SM2016iiADF96",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si en la raza canina poodle se detecta una malformación congénita de las venas pulmonares, podríamos afirmar que puede producirse una falla en el",
		A: "intercambio gaseoso en la mayoría de alveolos pulmonares.",
		B: "transporte de sangre venosa del corazón a los pulmones.",
		C: "transporte de sangre no oxigenada al músculo cardíaco.",
		D: "transporte de sangre venosa de los pulmones al corazón.",
		E: "transporte de sangre oxigenada de los pulmones al corazón.",
		Correct: "E"
	},
	{
		name: "SM2016iiADF97",
		subject: "Biology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Las enfermedades pueden clasificarse usando distintos criterios: por la rapidez con la que aparecen, por su duración, por la frecuencia y extensión en la población que afecta, y por su origen. Si quisiéramos clasificar la enfermedad producida por el virus del zika (transmitida por el mosquito Aedes aegypti) por la duración y rapidez con la que aparece, sostendríamos que es una enfermedad",
		A: "aguda.",
		B: "degenerativa.",
		C: "esporádica.",
		D: "endémica.",
		E: "crónica.",
		Correct: "A"
	},
	{
		name: "SM2016iiADF98",
		subject: "Biology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Las características más relevantes de los organismos autótrofos y heterótrofos se encuentran consignados en el siguiente cuadro:<br>Si en un medio de cultivo con grandes cantidades de glucosa colocáramos una planta y un hongo, se esperaría que",
		A: "se incremente la tasa de respiración aerobia y/o anaerobia en los dos organismos.",
		B: "en el hongo aumente el proceso de absorción y en la planta disminuya el de fotosíntesis.",
		C: "la glucosa del medio solo sea utilizada como nutriente energético por el hongo.",
		D: "tanto la planta como el hongo utilicen la glucosa del medio para obtener energía.",
		E: "la planta sea capaz de realizar fotosínte- sis como respiración celular anaeróbica.",
		Correct: "C"
	},
	{
		name: "SM2016iiADF99",
		subject: "Biology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la naturaleza, las poblaciones pueden crecer de manera exponencial hasta alcanzar su máxima capacidad de carga (corno lo hacen las especies de vida corta y con muchas crías) o de forma sigmoidea (como lo hacen los animales de vida larga y con pocas crías). De acuerdo con lo expuesto, ¿cuál es el organismo que tiene crecimiento exponencial?",
		A: "Los gorriones",
		B: "Los ratones",
		C: "Las tortugas",
		D: "Las moscas",
		E: "Los elefantes",
		Correct: "D"
	},
	{
		name: "SM2016iiADF100",
		subject: "Biology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "A una niña y sus padres se les realiza un estudio citogenético. La niña presenta una trisomía del par 21 y los padres presentan un cariotipo normal. ¿Cuál sería la explicación de este resultado?",
		A: "En la gametogénesis de uno de los padres ocurrió una duplicación del par 21.",
		B: "Hubo una distribución inadecuada de los cromosomas de la niña.",
		C: "La niña presenta la trisomía 21 porque uno de los padres es portador.",
		D: "Durante la gametogénesis de la niña, ocurrió la no disyunción del par 21.",
		E: "Hubo no disyunción en el par 21 en uno de los gametos de los padres.",
		Correct: "E"
	}/*,
	{
		name: "SM2016iiADF101",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF102",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF103",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF104",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF105",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF106",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF107",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF108",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF109",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF110",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF111",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF112",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF113",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF114",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF115",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF116",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF117",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF118",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF119",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF120",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF121",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF122",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF123",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF124",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF125",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF126",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF127",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF128",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF129",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2016iiADF130",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	}*/
]