// questions array (below) is numbered 0-end
// but exam questions are numbered 1 - (end - 1)        
function checkAnswer() {
    
    var numOfQs = 0;
    
    var choices = [];
    var chosen = [];
    
    for (var i = 0; i < pos; i++ ) {
        numOfQs += qNum[i];
    }
    
    firstQ = numOfQs - qNum[pos - 1];
    //document.write(questions[pos].Correct);
    for (var j = firstQ; j < numOfQs; j++) {
    choices.push(document.getElementsByName("choices" + j));
    for (var i=0; i < choices[j -firstQ].length; i++) {
        if (choices[j - firstQ][i].checked) {
            chosen.push(choices[j - firstQ][i].value);
            //document.write("if");
        }
    }
    }
        
    //document.write(questions[pos].Correct);
    //document.write(choices.length);
    //document.write("Holass");
    for (var i=0; i < chosen.length; i++) {

        if (chosen[i] == questions[pos].Correct) {
            score++;
        }
    }
    
    //document.write("Hola");
    if (pos == test.length) {
        document.write("<h1>Te sacaste " + score + " de " + numOfQs + " preguntas</h1><br>");
        document.write(qNum);
    } else {
    renderQuestion();
    }
}


// will create array of htmls that make up
// ONE/SINGLE test
function testIntegrator() {
    var len = questions.length;
    var num = 0;
    var test = [];
    while (num < len) {
        
        var text = '<html lang="en">\
        <head></head>\
        <body>';
        if (questions[num].name.includes("-")) {
            var index = questions[num].name.indexOf("-");
            var z = parseInt(questions[num].name.substring(index+1));
            qNum.push(parseInt(z - num));
            for (; num < z; num++) {
                text += display(num+1);
            }
            text += '</body>\
            </html>'
            test.push(text);
        } else {
            text += '</body>\
            </html>'
            test.push(display(num+1));
            qNum.push(1);
            num++;
        }
    }
    
    return test;
}

// Like distill but w/ a test
function testtill(num) {
    num = num - 1;
    if (questions[num].name.includes("-")) {
        var i = questions[num].name.indexOf("-");
        document.write(i);
        var a = parseInt(questions[num].name[i-1]);
        document.write("<br>" +a);
        var z = parseInt(questions[num].name.substring(i+1));
        var text = "";
        for (j = a; j <= z; j++) {
            text += display(j);
        }
        return text;
    }
    else {
        return display(num + 1);
    }
}

//displays individual question (from array object below)
// display INPUT: # of Question
function display(num) {
    num = num - 1;
    choices = "'choices" + num + "'";
    var text = "";
    if (questions[num].prompt && questions[num].prompt.includes(" ")) {
        text += "<p>" + questions[num].prompt + "</p>";
    }
    text += "<p>" + questions[num].question +"</p>";
    text += "<input type='radio' name=" + choices + " value='A'> " + questions[num].A + "<br>";
    text += "<input type='radio' name=" + choices + " value='B'> " + questions[num].B + "<br>";
    text += "<input type='radio' name=" + choices + " value='C'> " + questions[num].C + "<br>";
    text += "<input type='radio' name=" + choices + " value='D'> " + questions[num].D + "<br>";
    text += "<input type='radio' name=" + choices + " value='E'> " + questions[num].E + "<br>";
    /*
    text += "<input type='radio' name='choices1' value='A'>" + questions[num].A + "<br>";
    text += "<input type='radio' name='choices' value='B'>" + questions[num].B + "<br>";
    text += "<input type='radio' name='choices' value='C'>" + questions[num].C + "<br>";
    text += "<input type='radio' name='choices' value='D'>" + questions[num].D + "<br>";
    text += "<input type='radio' name='choices' value='E'>" + questions[num].E + "<br>";
    */
    return text;  
}

var questions = [
	{
		name: "SM2015iADE1-2",
		subject: "VA",
		sub_subject: "",
		prompt: "Después de identificar y analizar la relación semántica de la serie de cada ítem, seleccione la respuesta más adecuada",
		image: false,
		question: "Rumbo, vía, camino,",
		A: "meta",
		B: "precepto",
		C: "borde",
		D: "senda",
		E: "trazo",
		Correct: "D"
	},
	{
		name: "SM2015iADE2",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iADE1-2",
		image: false,
		question: "Confirmar, corroborar, revalidar,",
		A: "valorar",
		B: "resolver",
		C: "ratificar",
		D: "prescindir",
		E: "recrear",
		Correct: "C"
	},
	{
		name: "SM2015iADE3-5",
		subject: "VA",
		sub_subject: "",
		prompt: "Sentence Elimination",
		prompt: "Lea atentamente cada conjunto oracional y determine el enunciado que debe eliminarse por no corresponder al tema o por ser de índole tangencial.",
		image: false,
		question: "(I) Los ejercicios espirituales de San Ignacio pre­ tenden ayudar al cristiano a descubrir la voluntad de Dios en su propia vida. (II) Los ejercicios consisten en un retiro de treinta días durante el cual el ejercitante centra su atención en los temas fundamentales del cristianismo. (III) El objetivo principal de los ejercicios espirituales es descubrir la voluntad de Dios, o bien, sentirse confirmado en el camino que uno haya escogido. (IV) San Ignacio intuía que existe una voluntad general de Dios para todos los cristianos, y que Dios tenía un llamado especial para cada persona. (V) Un ele­ mento clave en los ejercicios espirituales consiste en encontrar a Dios en todas las cosas, así como la contemplación para alcanzar el amor.",
		A: "III",
		B: "II",
		C: "I",
		D: "V",
		E: "IV",
		Correct: "E"
	},
	{
		name: "SM2015iADE4",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iADE3-5",
		image: false,
		question: "(I) Las pandillas juveniles se originan por la nece­ sidad de los adolescentes de enfrentar problemas comunes de manera colectiva. (II) Los adoles­ centes suelen ver en su entorno inmediato ciertos problemas que pueden conducirlos a la rebeldía. (III) Según la OMS, la edad promedio de los miembros de una pandilla juvenil oscila entre los 7 y 35 años. (IV) Por lo general, los miembros de las pandillas juveniles son varones, aunque cada vez hay más integrantes de sexo femenino. (V) Las pandillas juveniles se diferencian unas de otras a partir de la utilización de tatuajes, símbolos, forma de vestir y diferentes jergas.",
		A: "I",
		B: "III",
		C: "V",
		D: "II",
		E: "IV",
		Correct: "II"
	},
	{
		name: "SM2015iADE5",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iADE3-5",
		image: false,
		question: "(I) Las extremidades están formadas básicamen­ te por unos huesos largos articulados entre sí y vinculados por diversos músculos para que poda­ mos realizar amplios movimientos. (II) Aunque los miembros superiores y los inferiores comparten su estructura elemental y guardan una gran analogía, lo cierto es que sus funciones están claramente diferenciadas. (III) Los miembros superiores, de manera simplificada, tienen como función princi­ pal la prensión, lo cual nos permite tocar, palpar, reconocer las características, agarrar y mover todo tipo de cosas. (IV) Los miembros inferiores, en cambio, cumplen su función principal cuando adoptamos la posición bípeda que constituye la base de sustentación del cuerpo, y nos permiten desplazarnos. (V) En el proceso de hominización, la posición bípeda fue determinante para la evo­ lución posterior del cerebro humano.",
		A: "I",
		B: "V",
		C: "III",
		D: "II",
		E: "IV",
		Correct: "B"
	},
	{
		name: "SM2015iADE6-10",
		subject: "VA",
		sub_subject: "",
		prompt: "Que nosotros sepamos, los humanos somos los únicos animales conscientes de que la muerte nos aguarda y capaces de articular lingüísticamente dicha conciencia. De todos modos, es muy posible que otros animales también tengan conciencia de la muerte, aunque no la expresen lingüísticamente. Los elefantes reconocen la muerte de sus congéne­ res. Ante el cadáver de uno de ellos, toda la familia de elefantes se detiene y se pone tensa. Primero acercan sus trompas para olerlo, luego palpan y mueven con cuidado los huesos, sobre todo los del cráneo, como si trataran de identificar al difunto. Otras veces, reconocen al muerto y arrojan tierra y hojas sobre sus restos.<br>Cuando un elefante muere, toda la manada se preocupa. Si se trata de una cría, su madre permanece junto al cadáver varios días e incluso trata de transportarla con ayuda de su trompa y sus colmillos. El resto de la manada permanece a su lado o reduce el paso. Cuando se muere un adulto, los otros elefantes tratan de levantarlo y no se separan de él hasta que sus restos entran en putrefacción. A veces velan el cadáver, ahuyentando a los carroñeros, e incluso lo entierran a medias con hojarasca. La muerte de la matriarca de la familia causa una general consternación y puede conducir a la disgregación del grupo. Todas estas costumbres de los elefantes facilitan la carnicería de los cazadores <b>furtivos</b>. Si matan a un individuo de la manada, pueden matar a todos, pues los demás, lejos de huir, tratarán de acompañar al difunto.<br>Todas las poblaciones humanas parecen haber tenido algún tipo de conciencia de la muerte. Con frecuencia, la vida se identificaba con el aliento.Por ello, el criterio para decidir si alguien todavía vivía o ya estaba muerto consistía en comprobar si aún tenía aliento, colocándosele en caso de duda un espejo en la boca, a ver si se empañaba. La muerte es un proceso que no puede fijarse en un instante único y determinado. Actualmente se tiende a hacer coincidir la muerte legal con la muerte cerebral.",
		image: false,
		question: "En el texto, el término FURTIVO equivale a",
		A: "furioso.",
		B: "impedido.",
		C: "proscrito.",
		D: "ilegal.",
		E: "protegido.",
		Correct: "D"
	},
	{
		name: "SM2015iADE7",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iADE6-10",
		image: false,
		question: "¿Cuál es el tema central del texto?",
		A: "La precaria condición en que viven los elefantes.",
		B: "La coincidencia de la muerte cerebral y la muerte legal.",
		C: "La universalidad del sentimiento religioso de la muerte.",
		D: "Las costumbres de los elefantes en los funerales.",
		E: "La conciencia de la muerte y sus diversas expresiones.",
		Correct: "E"
	},
	{
		name: "SM2015iADE8",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iADE6-10",
		image: false,
		question: "¿Cuál de las siguientes alternativas no es compatible con el sentido del texto?",
		A: "Las costumbres de los elefantes facilitan la labor de los cazadores furtivos.",
		B: "Entre los elefantes, la muerte de la matriarca causa consternación general.",
		C: "La muerte es un proceso que no puede fijarse en un instante único.",
		D: "Los seres humanos somos los únicos animales conscientes de la muerte.",
		E: "Para saber si alguien estaba vivo se comprobaba si aún tenía aliento.",
		Correct: "D"
	},
	{
		name: "SM2015iADE9",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iADE6-10",
		image: false,
		question: "Cabe inferir que, para el autor, el aliento humano",
		A: " se asocia naturalmente como expresión vital.",
		B: "hoy no es suficiente como signo de vida.",
		C: "ha servido para saber si alguien ha muerto.",
		D: "puede ser verificado solo con espejos.",
		E: "basta para saber si alguien está vivo o no.",
		Correct: "B"
	},
	{
		name: "SM2015iADE10",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iADE6-10",
		image: false,
		question: "Si los elefantes fueran capaces de usar un lenguaje articulado, entonces, probablemente,",
		A: "perderían la arraigada costumbre de acompañar a sus difuntos.",
		B: "se enfrentarían a las especies carroñeras con mejores medios.",
		C: "experimentarían un nuevo y maravilloso sentimiento religioso.",
		D: "podrían expresar simbólicamente su conciencia de la muerte.",
		E: "tendrían un cerebro muy superior al de los seres humanos.",
		Correct: "D"
	},
	{
		name: "SM2015iADE11-15",
		subject: "VA",
		sub_subject: "",
		prompt: 'Una de las controversias más prolongadas y acaloradas acerca de la evolución humana gira en torno a la relación genética entre los neandertales y sus sucesores europeos: los seres humanos modernos que empezaron a desplazarse desde África hace unos 60 000 años ¿sustituyeron por completo a los neandertales o se aparearon con ellos? En 1997, el genetista Svante Pääbo –adscrito en esa época a la Universidad de Múnich– asestó un duro golpe a la segunda hipótesis, al estudiar un hueso del brazo de un neandertal original.<br>Pääbo y sus colegas lograron extraer un diminuto fragmento de 378 letras químicas de ADN mitocondrial (una especie de breve apéndice al texto genético principal de cada célula) del <b>espécimen</b> de 40 000 años de antigüedad. Cuando interpretaron el código, hallaron que el ADN del <b>espécimen</b> difería en tal grado del de los seres humanos vivientes, que sugería que los linajes de los neandertales y de los hombres modernos habían comenzado a divergir mucho antes de la emigración de los humanos modernos desde África, de suerte que los dos linajes representan ramas geográficas y evolutivas distintas que se derivan de un ancestro común. “Al norte del Mediterráneo, este linaje se convirtió en el hombre de Neandertal –afirma Chris Stringer, director de investigación sobre los orígenes del hombre del Museo de Historia Natural de Londres–, y al sur del Mediterráneo, en nosotros”. Si hubo alguna cruza cuando se encontraron posteriormente, fue demasiado esporádica como para dejar rastro de ADN mitocondrial neandertal en las células del ser humano actual.<br>La bomba genética de Pääbo pareció confirmar que los neandertales eran una especie distinta, pero no contribuyó a resolver el enigma de por qué ellos se extinguieron y nosotros sobrevivimos.',
		image: false,
		question: "Principalmente, el autor intenta",
		A: "problematizar la relación genética entre los neandertales y los antecesores de los seres humanos actuales.",
		B: "describir los resultados de las investigaciones de Svante Pääbo sobre la extinción de los neandertales.",
		C: "presentar y defender la tesis de Chris Stringer de por qué se extinguieron los hombres de Neandertal.",
		D: "describir cómo se llegó a descifrar el código genético de un espécimen de 40 000 años de antigüedad.",
		E: "explicar genéticamente una posible cruza entre el linaje de los neandertales y el de los humanos modernos.",
		Correct: "A"
	},
	{
		name: "SM2015iADE12",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iADE11-15",
		image: false,
		question: "El término ESPÉCIMEN, en el segundo párrafo, puede ser reemplazado por",
		A: "género",
		B: "conjunto.",
		C: "entidad.",
		D: "grupo.",
		E: "ejemplar.",
		Correct: "E"
	},
	{
		name: "SM2015iADE13",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iADE11-15",
		image: false,
		question: "Resulta incompatible con lo referido en el texto afirmar que",
		A: "los neandertales y los seres humanos modernos coexistieron en el continente europeo.",
		B: "las investigaciones de Svante Pääbo lograron explicar la extinción de los neandertales.",
		C: "los hombres de Neandertal habitaron el continente europeo hace unos 40 000 años atrás.",
		D: " tanto los neandertales como los seres humanos actuales derivan de un ancestro común.",
		E: "los seres humanos modernos, al parecer, sustituyeron por completo a los neandertales.",
		Correct: "B"
	},
	{
		name: "SM2015iADE14",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iADE11-15",
		image: false,
		question: "Del texto se puede deducir que los antepasados de los seres humanos actuales",
		A: "se cruzaron sistemáticamente con los neandertales.",
		B: "llegaron a Europa mucho antes que los neandertales.",
		C: "se desplazaron desde África hacia otros continentes.",
		D: "emigraron de África hace más de 200 000 años.",
		E: "tienen un ADN mitocondrial idéntico al de los neandertales.",
		Correct: "C"
	},
	{
		name: "SM2015iADE15",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iADE11-15",
		image: false,
		question: "Si el ADN mitocondrial neandertal guardase mayor semejanza con el de los seres humanos modernos, entonces",
		A: "se confirmaría la hipótesis de que ambas especies se aparearon al encontrarse en Europa.",
		B: "las investigaciones de Pääbo sobre el origen de los neandertales perderían relevancia.",
		C: "se debería a una cruza esporádica entre algunos especímenes de las dos especies.",
		D: "la hipótesis de la sustitución de los neandertales por los seres humanos se confirmaría.",
		E: "se refutaría que los neandertales y los humanos modernos tuvieron un ancestro común.",
		Correct: "A"
	},
	{
		name: "SM2015iADE16-20",
		subject: "VA",
		sub_subject: "",
		prompt: 'Platón hizo inscribir en el dintel de la puerta de la Academia: “No entre aquí quien no sepa geometría”. Pero ¿a qué geometría se refiere, si en los diálogos en los que habla sobre la justicia, la política, el amor, el alma, el conocimiento, y tantos otros aspectos de la vida humana, nunca aparece la geometría? El filósofo es consciente de ello, y no ha querido tocar mucho este tema porque su ambición más secreta es el origen del mundo. ¿De qué le viene interesarse por este tema, y creer que las matemáticas estén vinculadas al origen del mundo y a la esencia de la realidad? Platón cree, como Parménides, que lo esencial del mundo es lo inmutable, lo que no cambia con el tiempo y que unifica la realidad tras los rápidos cambios de la misma.<br>Pero ¿qué es lo que permanece? Una representación del ser permanente tras el mundo material es el orden matemático que Pitágoras atribuyó al universo. Para él, los números son la esencia de la realidad y la geometría enseña a ver las formas más auténticas que la realidad deforma y simula. En su juventud, Platón quedó fascinado por esta idea: lo permanente tras la realidad no es algo material, palpable, sino una forma, una idea. Quizá lo más profundo de la realidad no se encuentra en la materia sino en las formas.<br>Sin embargo, era necesario ir más allá de Pitágoras, que se limitó a las ideas matemáticas, y buscar la permanencia no tan solo en la idea de las formas geométricas, sino también en muchas otras, como por ejemplo la idea de perro y la de caballo, la de casa y la de barca, la de cuerpo y la de alma. Las ideas numéricas de Pitágoras se pueden ampliar en las ideas perennes de la realidad más pura. Así como los triángulos son materializaciones de una idea matemática, podría ser que todo, en el mundo, fuera <b>reflejo</b> de algunas ideas generales y eternas regidas por una lógica bella y buena. Más aun, estas ideas podrían representar la realidad más auténticas, esto es, el mundo de arquetipos que componen la verdadera realidad.',
		image: false,
		question: "Hacia el final del texto, el sentido de la palabra REFLEJO es",
		A: "efecto.",
		B: "destello.",
		C: "base.",
		D: "forma.",
		E: "copia.",
		Correct: "E"
	},
	{
		name: "SM2015iADE17",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iADE16-20",
		image: false,
		question: "El autor se refiere, principalmente, a la",
		A: "invención de una nueva aplicación y sentido de la geometría platónica.",
		B: "búsqueda platónica de lo permanente como arquetipos de la realidad.",
		C: "falsedad de la inscripción colocada en la puerta de la Academia de Platón.",
		D: "exigencia del saber geométrico como condición de ingreso a la Academia.",
		E: "concepción pitagórica de la permanencia de las puras formas geométricas.",
		Correct: "B"
	},
	{
		name: "SM2015iADE18",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iADE16-20",
		image: false,
		question: "¿Cuál de los siguientes enunciados es incompatible con lo aseverado en el texto?",
		A: "Para Platón, la geometría estaba unida al origen del mundo y a la esencia de la realidad.",
		B: "Pitágoras consideró que los números constituían la esencia de la realidad per­ manente.",
		C: "La creencia en formas permanentes de trás del mundo material fascinó al joven Platón.",
		D: "Según el pensamiento de Platón,lomás auténtico de la realidad tiene carácter material.",
		E: "Platón asumió la creencia de Parménides acerca de una esencia inmutable del mundo.",
		Correct: "D"
	},
	{
		name: "SM2015iADE19",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iADE16-20",
		image: false,
		question: "Se infiere que, para Platón, el cambio era",
		A: "una mera aparencia.",
		B: "el objectivo de la realidad.",
		C: "el principio de la geometría.",
		D: "un arquetipo fundamental.",
		E: "la esencia de lo real.",
		Correct: "A"
	},
	{
		name: "SM2015iADE20",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iADE16-20",
		image: false,
		question: "Si la fascinación del joven Platón por la filosofía pitagórica hubiera desembocado en una admiración dogmática, entonces, probablemente, habría",
		A: "asumido que el mundo material es relativo.",
		B: "creído innecesario ir más allá de Pitágoras.",
		C: "cuestionado los límites del filosofar pitagórico.",
		D: "reinterpretado el pitagorismo en clave geométrica.",
		E: "abandonado el interés en estudiar geometría.",
		Correct: "B"
	},
	{
		name: "SM2015iADE21",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En una caja, se tiene 200 canicas de color verde, 200 de color rojo, 200 de color azul, 200 de color negro y 250 de color amarillo. ¿Cuál es el menor número de canicas que se debe extraer al azar para tener, con certeza, al menos 100 canicas del mismo color?",
		A: "497",
		B: "498",
		C: "495",
		D: "496",
		E: "494",
		Correct: "D"
	},
	{
		name: "SM2015iADE22",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Álvaro, Benito, César y Darío poseen, cada uno, un celular del mismo tamaño y forma, pero de diferentes colores: negro, verde, azul y rojo. Al apagarse las luces, cada uno cogió un celular que no era el suyo. Después de esto, se determinó que<br>- Darío se quedó con el celular azul porque su celular lo tomó César.<br>- Álvaro dice: “Si me prestan el celular azul, devuelvo su celular verde a César”.<br>- Benito se quedó con el celular rojo porque su verdadero dueño no devolvió el celular verde a su propietario.<br>¿Quiénes son los dueños de los celulares negro y rojo respectivamente?",
		A: "Darío y Benito",
		B: "César y Álvaro",
		C: "Benito y Álvaro",
		D: "Darío y César",
		E: "Darío y Álvaro",
		Correct: "E"
	},
	{
		name: "SM2015iADE23",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Miguel colocó 4 dados normales sobre una mesa no transparente como muestra la figura. ¿Cuántos puntos en total no son visibles para Miguel?",
		A: "23",
		B: "22",
		C: "24",
		D: "21",
		E: "25",
		Correct: "C"
	},
	{
		name: "SM2015iADE24",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Tania, Norma, Pedro, Fredy, Darío y Rocío se ubican simétricamente en seis asientos alrededor de una mesa circular. Tania no está al lado de Norma ni de Pedro. Fredy no está al lado de Rocío ni de Pedro. Darío está junto y a la derecha de Norma, pero Norma no está al lado de Rocío ni de Fredy. ¿Quién está ubicado junto y a la izquierda de Fredy?",
		A: "Darío",
		B: "Rocío",
		C: "Norma",
		D: "Pedro",
		E: "Tania",
		Correct: "A"
	},
	{
		name: "SM2015iADE25",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Amílcar empaqueta un regalo para cada una de sus cuatro hermanas, tomando en cuenta el color de preferencia de cada una de ellas, en cuatro cajas idénticas. En una de ellas coloca una cartera de color blanco; en otra, una de color rojo, y en cada una de las otras dos, una de color marrón. Luego, las cierra y, al etiquetarlas con el color de las carteras que contiene cada caja, se equivoca en todas. Para etiquetarlas correctamente, ¿cuántas cajas se debe abrir como mínimo y cuál o cuáles de ellas?",
		A: '1 y la caja etiquetada con “cartera de color rojo”.',
		B: '1 y la caja etiquetada con “cartera de color marrón”.',
		C: '2 y las cajas etiquetadas con “cartera de color marrón”.',
		D: '1 y la caja etiquetada con “cartera de color blanco”.',
		E: '2 y la caja etiquetada con “cartera de color marrón” y la “de color rojo”.',
		Correct: "B"
	},
	{
		name: "SM2015iADE26",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la lista de precios de una librería, se observa:<br>- Un plumón más un lapicero cuesta lo mismo que seis cuadernos.<br>- Dos plumones cuestan, lo mismo que un cuaderno más un corrector.<br>- Dos cuadernos cuestan, igual que un corrector.<br>Por el precio de dos lapiceros, ¿cuántos cuadernos se podrá comprar?",
		A: "8",
		B: "7",
		C: "9",
		D: "6",
		E: "10",
		Correct: "C"
	},
	{
		name: "SM2015iADE27",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En un centro de investigación trabajan 67 personas. De estas, 47 hablan inglés; 35 hablan francés y 23 hablan ambos idiomas. ¿Cuántas personas no hablan inglés ni francés en el centro de investigación?",
		A: "8",
		B: "9",
		C: "7",
		D: "6",
		E: "10",
		Correct: "A"
	},
	{
		name: "SM2015iADE28",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la Facultad de Ciencias Sociales de la UNMSM, se realizará un campeonato de fulbito con seis equipos. Si jugaran todos contra todos, ¿cuántos partidos deberán programarse como mínimo?",
		A: "12",
		B: "10",
		C: "14",
		D: "8",
		E: "15",
		Correct: "E"
	},
	{
		name: "SM2015iADE29",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Halle la suma de las cifras del resultado de R. R = \\((\\underbrace{6\\cdot 6\\cdot 6\\cdots 66}_{9\\text{ cifras}})^2 + \\underbrace{2\\cdot 2\\cdot 2\\cdots 22}_{9\\text{ cifras}}\\)",
		A: "101",
		B: "100",
		C: "99",
		D: "98",
		E: "102",
		Correct: "C"
	},
	{
		name: "SM2015iADE30",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si se empieza a escribir uno a continuación de otro la secuencia de los números naturales pares hasta el 38, como se muestra a continuación: 2468...343638, ¿cuál será el residuo al dividir entre 9 el número así formado?",
		A: "4",
		B: "2",
		C: "5",
		D: "3",
		E: "7",
		Correct: "B"
	},
	{
		name: "SM2015iADE31",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si los primeros términos de una secuencia son log4, log9, log25, log49, ..., log\\(\\mathrm{a^2}\\), ..., log361, log\\(\\mathrm{b^2}\\), log841; donde 11 < a < 17, halle log(b – a).",
		A: "1",
		B: "3",
		C: "2",
		D: "5",
		E: "10",
		Correct: "A"
	},
	{
		name: "SM2015iADE32",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si \\(\\mathrm{x^{x^5}} = \\frac{1}{\\sqrt[75]{125}}\\), halle el valor de x",
		A: "\\(\\frac{1}{\\sqrt[5]{75}}\\)",
		B: "\\(\\frac{1}{\\sqrt[5]{5}}\\)",
		C: "\\(\\frac{1}{\\sqrt[5]{25}}\\)",
		D: "\\(\\frac{1}{\\sqrt[3]{5}}\\)",
		E: "\\(\\frac{1}{\\sqrt[3]{25}}\\)",
		Correct: "B"
	},
	{
		name: "SM2015iADE33",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si f (\\(\\sqrt{2}\\)) = 1 y f(x+y)=f(x)+f(y), para todo x, y ∈ R+, halle f (3\\(\\sqrt{2}\\)).",
		A: "3\\(\\sqrt{2}\\)",
		B: "2",
		C: "\\(\\sqrt{2}\\)",
		D: "3",
		E: "\\(\\frac{3}{2}\\sqrt{2}\\)",
		Correct: "D"
	},
	{
		name: "SM2015iADE34",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si x–y = 1, donde x ≠ 0, y ≠ 0, halle el valor de \\(\\frac{\\mathrm{x^3} - \\mathrm{y^3} - 1}{\\mathrm{x^2} + \\mathrm{y^2} - 1} - \\frac{1}{2}\\)",
		A: "\\(\\frac{1}{2}\\)",
		B: "\\(\\frac{2}{3}\\)",
		C: "1",
		D: "\\(\\frac{3}{2}\\)",
		E: "2",
		Correct: "C"
	},
	{
		name: "SM2015iADE35",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "La suma de lo que gana y gasta diariamente una persona es S/.300, y la relación de lo que gasta y gana diariamente es \\(\\frac{1}{2}\\). ¿En cuánto tiene que disminuir su gasto diario para que la relación de lo que gaste y gane sea \\(\\frac{2}{5}\\)?",
		A: "S/.30",
		B: "S/.25",
		C: "S/.15",
		D: "S/.35",
		E: "S/.20",
		Correct: "E"
	},
	{
		name: "SM2015iADE36",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura, el cuadrado ABCD está subdividido en 100 cuadraditos congruentes. ¿Qué fracción del área del cuadrado ABCD representa la región sombreada?",
		A: "\\(\\frac{1}{2}\\)",
		B: "\\(\\frac{2}{5}\\)",
		C: "\\(\\frac{1}{3}\\)",
		D: "\\(\\frac{3}{5}\\)",
		E: "\\(\\frac{2}{3}\\)",
		Correct: "B"
	},
	{
		name: "SM2015iADE37",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura, BAC es un triángulo rectángulo recto en A y DEFG es un cuadrado inscrito en el triángulo. Si BF=16 m y GC=9 m, halle el área del cuadrado.",
		A: "145 \\(\\mathrm{m^2}\\)",
		B: "143 \\(\\mathrm{m^2}\\)",
		C: "142 \\(\\mathrm{m^2}\\)",
		D: "146 \\(\\mathrm{m^2}\\)",
		E: "144 \\(\\mathrm{m^2}\\)",
		Correct: "E"
	},
	{
		name: "SM2015iADE38",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura, OA=6 cm y la circunferencia está inscrita en el sector circular AOB. Si P, T y Q son puntos de tangencia, halle el perímetro de la región sombreada",
		A: "4(2+π) cm",
		B: "(2+4π) cm",
		C: "6(2+π) cm",
		D: "(3+2π) cm",
		E: "8(1+π) cm",
		Correct: "C"
	},
	{
		name: "SM2015iADE39",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura, si BF = 3 cm y ED = 4 cm, halle CF.",
		A: "4,5 cm",
		B: "5 cm",
		C: "5,5 cm",
		D: "6 cm",
		E: "6,5 cm",
		Correct: "B"
	},
	{
		name: "SM2015iADE40",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura, M y N son puntos medios de \\(\\mathrm{\\overline{AD}}\\) y \\(\\mathrm{\\overline{CD}}\\) respectivamente y el área de la región cuadrada ABCD es 30 \\(\\mathrm{cm^2}\\). Halle el área de la región sombreada",
		A: "1 c\\(\\mathrm{m^2}\\)",
		B: "2 c\\(\\mathrm{m^2}\\)",
		C: "0,5 c\\(\\mathrm{m^2}\\)",
		D: "1,5 c\\(\\mathrm{m^2}\\)",
		E: "3 c\\(\\mathrm{m^2}\\)",
		Correct: "A"
	},
	{
		name: "SM2015iADE41",
		subject: "Arithmetic",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Se ha mezclado 100 d\\(\\mathrm{m^3}\\) de cemento con 0,4 \\(\\mathrm{m^3}\\) de arena. ¿Qué cantidad de arena debe añadirse para que el cemento sea \\(\\frac{1}{7}\\) de la mezcla resultante?",
		A: "0,3 \\(\\mathrm{m^3}\\)",
		B: "0,6 \\(\\mathrm{m^3}\\)",
		C: "0,2 \\(\\mathrm{m^3}\\)",
		D: "0,4 \\(\\mathrm{m^3}\\)",
		E: "0,5 \\(\\mathrm{m^3}\\)",
		Correct: "C"
	},
	{
		name: "SM2015iADE42",
		subject: "Arithmetic",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "¿Cuántas fracciones propias de términos positivos, impares y consecutivos menores de 0,90 existen?",
		A: "9",
		B: "8",
		C: "7",
		D: "6",
		E: "10",
		Correct: "A"
	},
	{
		name: "SM2015iADE43",
		subject: "Arithmetic",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Se tiene el conjunto A = {1; 2; 3; 4}. Halle la cantidad total de números diferentes que pueden formarse con los elementos, sin repetición, de dicho conjunto.",
		A: "60",
		B: "62",
		C: "58",
		D: "64",
		E: "68",
		Correct: "64"
	},
	{
		name: "SM2015iADE44",
		subject: "Arithmetic",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El producto del máximo común divisor y el mínimo común múltiplo de los números enteros positivos P y Q es 864, y el de los números P y R es 720; halle \\(\\frac{\\mathrm{Q}}{\\mathrm{R}}\\).",
		A: "\\(\\frac{1}{5}\\)",
		B: "\\(\\frac{1}{4}\\)",
		C: "\\(\\frac{5}{6}\\)",
		D: "1",
		E: "\\(\\frac{6}{5}\\)",
		Correct: "E"
	},
	{
		name: "SM2015iADE45",
		subject: "Algebra",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si a y b son las raíces de \\(\\mathrm{x^2}\\)+14x–1=0; c y d son las raíces de \\(\\mathrm{x^2}\\)+17x+2=0, halle el valor de abc+bcd+cda+dab.",
		A: "17",
		B: "-45",
		C: "-11",
		D: "-28",
		E: "31",
		Correct: "C"
	},
	{
		name: "SM2015iADE46",
		subject: "Algebra",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Calcule el valor de k si la división \\(\\frac{\\mathrm{x^4 - x^3 + k}}{\\mathrm{x-2}}\\) tiene como resto 10",
		A: "2",
		B: "8",
		C: "3",
		D: "6",
		E: "4",
		Correct: "E"
	},
	{
		name: "SM2015iADE47",
		subject: "Algebra",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Dado el sistema de ecuaciones, determine el valor de x. ",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE48",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE49",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE50",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE51",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE52",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE53",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE54",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE55",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE56",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Las secuencias vocálicas de las palabras “buitre”, “oído” y “Paraguay” constituyen, respectivamente,",
		A: "diptongo, hiato y triptongo.",
		B: "diptongo, hiato y diptongo.",
		C: "hiato, diptongo y triptongo.",
		D: "diptongo, diptongo y triptongo.",
		E: "diptongo, hiato y hiato.",
		Correct: "A"
	},
	{
		name: "SM2015iADE57",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE58",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE59",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE60",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE61",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE62",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE63",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE64",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE65",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE66",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE67",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE68",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE69",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE70",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE71",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE72",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE73",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE74",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE75",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE76",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE77",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE78",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE79",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE80",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE81",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE82",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE83",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE84",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE85",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE86",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE87",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE88",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE89",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE90",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE91",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE92",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE93",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE94",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE95",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE96",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE97",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE98",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE99",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE100",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE101",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE102",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE103",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE104",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE105",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE106",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE107",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE108",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE109",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE110",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE111",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE112",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE113",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE114",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE115",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE116",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE117",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE118",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE119",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE120",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE121",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE122",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE123",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE124",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE125",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE126",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE127",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE128",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE129",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iADE130",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	}
]