// questions array (below) is numbered 0-end
// but exam questions are numbered 1 - (end - 1)        
function checkAnswer() {
    
    var numOfQs = 0;
    
    var choices = [];
    var chosen = [];
    
    for (var i = 0; i < pos; i++ ) {
        numOfQs += qNum[i];
    }
    
    firstQ = numOfQs - qNum[pos - 1];
    //document.write(questions[pos].Correct);
    for (var j = firstQ; j < numOfQs; j++) {
    choices.push(document.getElementsByName("choices" + j));
    for (var i=0; i < choices[j -firstQ].length; i++) {
        if (choices[j - firstQ][i].checked) {
            chosen.push(choices[j - firstQ][i].value);
            //document.write("if");
        }
    }
    }
        
    //document.write(questions[pos].Correct);
    //document.write(choices.length);
    //document.write("Holass");
    for (var i=0; i < chosen.length; i++) {

        if (chosen[i] == questions[pos].Correct) {
            score++;
        }
    }
    
    //document.write("Hola");
    if (pos == test.length) {
        document.write("<h1>Te sacaste " + score + " de " + numOfQs + " preguntas</h1><br>");
        document.write(qNum);
    } else {
    renderQuestion();
    }
}


// will create array of htmls that make up
// ONE/SINGLE test
function testIntegrator() {
    var len = questions.length;
    var num = 0;
    var test = [];
    while (num < len) {
        
        var text = '<html lang="en">\
        <head></head>\
        <body>';
        if (questions[num].name.includes("-")) {
            var index = questions[num].name.indexOf("-");
            var z = parseInt(questions[num].name.substring(index+1));
            qNum.push(parseInt(z - num));
            for (; num < z; num++) {
                text += display(num+1);
            }
            text += '</body>\
            </html>'
            test.push(text);
        } else {
            text += '</body>\
            </html>'
            test.push(display(num+1));
            qNum.push(1);
            num++;
        }
    }
    
    return test;
}

// Like distill but w/ a test
function testtill(num) {
    num = num - 1;
    if (questions[num].name.includes("-")) {
        var i = questions[num].name.indexOf("-");
        document.write(i);
        var a = parseInt(questions[num].name[i-1]);
        document.write("<br>" +a);
        var z = parseInt(questions[num].name.substring(i+1));
        var text = "";
        for (j = a; j <= z; j++) {
            text += display(j);
        }
        return text;
    }
    else {
        return display(num + 1);
    }
}

//displays individual question (from array object below)
// display INPUT: # of Question
function display(num) {
    num = num - 1;
    choices = "'choices" + num + "'";
    var text = "";
    if (questions[num].prompt && questions[num].prompt.includes(" ")) {
        text += "<p>" + questions[num].prompt + "</p>";
    }
    text += "<p>" + questions[num].question +"</p>";
    text += "<input type='radio' name=" + choices + " value='A'> " + questions[num].A + "<br>";
    text += "<input type='radio' name=" + choices + " value='B'> " + questions[num].B + "<br>";
    text += "<input type='radio' name=" + choices + " value='C'> " + questions[num].C + "<br>";
    text += "<input type='radio' name=" + choices + " value='D'> " + questions[num].D + "<br>";
    text += "<input type='radio' name=" + choices + " value='E'> " + questions[num].E + "<br>";
    /*
    text += "<input type='radio' name='choices1' value='A'>" + questions[num].A + "<br>";
    text += "<input type='radio' name='choices' value='B'>" + questions[num].B + "<br>";
    text += "<input type='radio' name='choices' value='C'>" + questions[num].C + "<br>";
    text += "<input type='radio' name='choices' value='D'>" + questions[num].D + "<br>";
    text += "<input type='radio' name='choices' value='E'>" + questions[num].E + "<br>";
    */
    return text;  
}

var questions = [
	{
		name: "SM2015iBCF1-2",
		subject: "VA",
		sub_subject: "",
		prompt: "Después de identificar y analizar la relación semántica de la serie de cada ítem, seleccione la respuesta más adecuada",
		image: false,
		question: "Escamotear, ocultar, esconder,",
		A: "prohibir",
		B: "enmendar",
		C: "olvidar",
		D: "desaparecer",
		E: "aplacar",
		Correct: "D"
	},
	{
		name: "SM2015iBCF2",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iBCF1-2",
		image: false,
		question: "Cautivante, agradable, atractivo,",
		A: "generoso",
		B: "cortés",
		C: "diligente",
		D: "dadivoso",
		E: "encantador",
		Correct: "E"
	},
	{
		name: "SM2015iBCF3-5",
		subject: "VA",
		sub_subject: "",
		prompt: "Sentence Elimination",
		prompt: "Lea atentamente cada conjunto oracional y determine el enunciado que debe eliminarse por no corresponder al tema o por ser de índole tangencial.",
		image: false,
		question: "(I) El kiwi sirve como un potente laxante, pues su contenido de magnesio y fibra soluble e in- soluble le confiere fuertes propiedades laxantes. (II) Debido a que contiene ácido fólico, el kiwi colabora en la producción de glóbulos rojos y en el fortalecimiento del sistema inmunológico. (III) El kiwi sirve para reducir el colesterol y también permite el buen control de glucemia en las personas que tienen diabetes. (IV) Por su abundancia de potasio y bajo aporte de sodio, el kiwi resulta muy recomendable para aquellas personas que sufren de hipertensión arterial. (V) Según los expertos, el kiwi debe conservarse en la refrigeradora para mantenerlo en condiciones adecuadas antes de su consumo.",
		A: "IV",
		B: "III",
		C: "V",
		D: "II",
		E: "I",
		Correct: "C"
	},
	{
		name: "SM2015iBCF4",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iBCF3-5",
		image: false,
		question: "(I) Las áreas verdes contribuyen con el ornato de las ciudades y convierten a estas en lugares pla- centeros para vivir. (II) Las áreas verdes definen los espacios públicos y otorgan características estéticas a cada ciudad. (III) Las áreas verdes aportan al mejoramiento del medio ambiente y al bienestar de nuestro sistema sensorial. (IV) Las áreas verdes que quedan abandonadas y descuidadas fomentan la inseguridad ciudadana, la delincuencia y el mal vivir. (V) Dentro de las ciudades, la disposición de áreas verdes promueve la práctica de deportes al aire libre.",
		A: "IV",
		B: "I",
		C: "III",
		D: "V",
		E: "II",
		Correct: "A"
	},
	{
		name: "SM2015iBCF5",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iBCF3-5",
		image: false,
		question: "(I) Francisco de Ávila, cura de Huarochiri, que se había formado con los jesuitas, pidió ayuda a sus antiguos mentores y al arzobispo Bartolo- mé Lobo Guerrero para combatir las idolatrías. (II) Los arzobispos y los virreyes que apoyaron esta guerra contra las idolatrías consideraron a los jesuitas como los más indicados para conducirla debido a su amplio conocimiento de las lenguas y culturas indígenas. (III) El virrey Francisco de Borja confiaba especialmente en los jesuitas y, frecuentemente, los nombraba jueces-visitadores con la misión de extirpar las idolatrías. (IV) Los jesuitas cumplían la labor encomendada en las campañas de extirpación, por ello realizaron in- numerables visitas a los pueblos de indios en todo el Perú. (V) Después de un entusiasmo inicial, los jesuitas cuestionaron su participación y perdieron interés en la misión, puesto que la mentalidad que dio origen a las campañas contra las idolatrías se oponía a la espiritualidad de su doctrina.",
		A: "III",
		B: "V",
		C: "I",
		D: "II",
		E: "IV",
		Correct: "B"
	},
	{
		name: "SM2015iBCF6-10",
		subject: "VA",
		sub_subject: "",
		prompt: "Cada dos días desaparece una lengua en algún lugar del mundo. Por eso, al menos 3000 lenguas de las cerca de 6800 que se hablan en el planeta están en peligro de desaparecer, en mayor o menor grado, debido al aumento de las situaciones de conflicto entre idiomas, según la Organización de las Naciones Unidas para la Educación, la Ciencia y la Cultura (UNESCO). Al celebrar el Día Internacional de la Lengua Materna y presentar en París la segunda edición del Atlas de las lenguas en peligro en el mundo, la Unesco advierte que el desplazamiento forzado de la comunidad, el contacto con una cultura más agresiva o acciones destructivas de los miembros de una cultura do- minante atentan contra el patrimonio lingüístico de la humanidad.<br>Cada idioma refleja una visión única del mundo y muestra la forma en la que una comunidad ha resuelto sus problemas con el entorno; por tal razón, la Unesco afirma que con la muerte y desaparición de una lengua se pierde una parte insustituible de nuestro conocimiento, del pensamiento y de la visión del mundo. La lengua de una comunidad está en peligro cuando un 30% de sus niños no la aprende. Y la situación es más crítica cuando solo cuenta con hablantes de mediana edad o ancia- nos. Los autores del Atlas señalan que la invasión azteca y la conquista española tuvieron un efecto catastrófico sobre las lenguas de México, donde se han contabilizado unos 110 idiomas extinguidos, dos de ellos –el chiapaneco y el cuilateco– en la segunda mitad del siglo xx.<br>Respecto de la situación actual, indican que al menos 14 idiomas hablados por minorías están en peligro o moribundos en ese país y cuatro o cinco más con un número “sustancial” de hablantes corren riesgo de desaparición. El paisaje es similar en América Central y del Sur, donde los gobiernos y las sociedades fueron indiferentes u <b>hostiles</b> hacia las lenguas indígenas en sus países hasta los años 70, según el Atlas.<br>En total, el número de lenguas identificadas que sobreviven en Sudamérica es de 375, muchas de las cuales están en peligro y una buena proporción está en condición de lengua moribunda.",
		image: false,
		question: "En el texto, la palabra HOSTILES connota, sobre todo,",
		A: "indolencia.",
		B: "impaciencia.",
		C: "agresión.",
		D: "crítica.",
		E: "incomprensión.",
		Correct: "C"
	},
	{
		name: "SM2015iBCF7",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iBCF6-10",
		image: false,
		question: "¿Cuál es el tema principal que desarrolla el texto?",
		A: "La naturaleza de las lenguas nativas",
		B: "Las lenguas indígenas del planeta",
		C: "El Atlas de las lenguas en extinción",
		D: "El problema de la extinción de lenguas",
		E: "Las lenguas aborígenes de América",
		Correct: "D"
	},
	{
		name: "SM2015iBCF8",
		subject: "VA",
		sub_subject: "SM2015iBCF6-10",
		prompt: false,
		image: false,
		question: "Se infiere del texto que, para prolongar la vida de una lengua,",
		A: "los hablantes nativos deben usarla solamente entre ellos.",
		B: "los pocos que la hablan deben desplazarse a zonas aisladas.",
		C: "es necesario confeccionar una nueva edición del Atlas.",
		D: "esprecisoqueaparezcaunanuevacultura dominante.",
		E: "se debe contar con alto porcentaje de hablantes jóvenes.",
		Correct: "E"
	},
	{
		name: "SM2015iBCF9",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iBCF6-10",
		image: false,
		question: "El autor rechazaría la pretensión de que",
		A: "casilamitaddelaslenguaspuedellegara desaparecer del planeta.",
		B: "las comunidades lingüísticas minoritarias se ven hoy muy afectadas.",
		C: "las lenguas aborígenes siempre recibieron el apoyo de los gobernantes.",
		D: "el chiapaneco es una lengua que se extin- guió hace menos de un siglo.",
		E: "las lenguas pueden llegar a extinguirse por el enfrentamiento intercultural.",
		Correct: "C"
	},
	{
		name: "SM2015iBCF10",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iBCF6-10",
		image: false,
		question: "Si todas las lenguas estuvieran en relación de igualdad, entonces",
		A: "en México sobrevivirían menos lenguas que las actuales.",
		B: "las lenguas indígenas del planeta se conservarían.",
		C: "las lenguas maternas no reflejarían la visión del mundo.",
		D: "se incrementaría el número de lenguas moribundas.",
		E: "desaparecerían los idiomas de las culturas dominantes.",
		Correct: "B"
	},
	{
		name: "SM2015iBCF11-15",
		subject: "VA",
		sub_subject: "",
		prompt: "Los especialistas en derechos humanos piensan que la representación de las personas en la publicidad es injusta y discriminatoria. En el caso de hombres y mujeres, existe una fuerte tendencia a presentar a los primeros como los protectores, los fuertes, mientras que a las segundas las vemos básicamente en roles secundarios. Sin embargo, las escenas discriminatorias no se circunscriben a esos ámbitos, ya que al mostrar a un tipo de personas en las que predomina la piel blanca y los cabellos claros, dejan de lado la diversidad racial que existe en nuestro país (andinos, mestizos, afrodescendientes, etc.).<br>Mariela Jara señala que los mensajes publi- citarios también discriminan cuando exponen situaciones en las que <br>priman<br> momentos de realización, felicidad y prosperidad económica en un país en el que la mayoría de la población (54,8 %) vive en la pobreza. Para sus defensores, la publicidad es el espejo de la cultura que hemos adquirido a lo largo de los años.<br>David Solari Martín explica que el individuo presta a los anuncios comerciales ideales de belleza y comportamiento. La sociedad acepta un modelo y la publicidad lo acoge. Es seguro que el color de tinte que más vende en el Perú es el rubio y acá las mujeres no son rubias. Entonces, estos mensajes nos alienan o tenemos parámetros de belleza que no corresponden a nuestra realidad, pero los aceptamos. Además, algunos spots publicitarios son androcéntricos (comerciales de cerveza), sexistas (productos de limpieza) o se centran en una determinada raza (productos de belleza). Por ejemplo, si vendemos mototaxis no vamos a uti- lizar modelos de ojos azules, porque ese no es el público consumidor. Por otro lado, las marcas de algunas instituciones bancarias y bebidas gaseosas tienen promociones en las que aparecen modelos con rasgos andinos. Lo que sucede es que hay un problema de identidad que provoca una falta de unidad entre los criterios y los mensajes que se emplean para elaborar los avisos publicitarios.",
		image: false,
		question: "¿Cuál es el tema principal que desarrolla el texto?",
		A: "Los contenidos discriminatorios en la publicidad peruana",
		B: "La aceptación de los roles tradicionales en la población",
		C: "Los valores tradicionales de los medios de comunicación",
		D: "Los problemas de identidad en las promociones de venta",
		E: "La crítica a los actuales anuncios comerciales regionales",
		Correct: "A"
	},
	{
		name: "SM2015iBCF12",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iBCF11-15",
		image: false,
		question: "En el segundo párrafo del texto, el verbo PRIMAR significa",
		A: "mostrar",
		B: "destacar",
		C: "iniciar",
		D: "originar",
		E: "cristalizar",
		Correct: "B"
	},
	{
		name: "SM2015iBCF13",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iBCF11-15",
		image: false,
		question: "Es incompatible con el texto afirmar que",
		A: "algunas bebidas gaseosas emplean modelos con rasgos andinos.",
		B: "estamos acostumbrados a reproducir patrones culturales alienantes.",
		C: "los avisos publicitarios difunden hábitos racistas, sexistas y androcéntricos.",
		D: "en la publicidad peruana nunca se utilizan modelos con rasgos andinos.",
		E: "a los peruanos les falta compartir ciertos valores, códigos y conductas.",
		Correct: "D"
	},
	{
		name: "SM2015iBCF14",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iBCF11-15",
		image: false,
		question: "Se infiere del texto que los anunciantes de bienes de consuma masivo",
		A: "promueven la equidad de género premian- do el mejor aviso.",
		B: "deben sancionar a las empresas que dis- criminan al comprador.",
		C: "carecen de una pauta común en sus cam- pañas publicitarias.",
		D: "evitan convertirse en transmisores de una cultura excluyente.",
		E: "deben conectarse a varias fuentes de in- formación electrónica.",
		Correct: "C"
	},
	{
		name: "SM2015iBCF15",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iBCF11-15",
		image: false,
		question: "Si se realizara un comercial de productos cosmé- ticos para la televisión, probablemente",
		A: "tomaría en cuenta la diversidad racial de los habitantes de la capital.",
		B: "ofertaría tintes de color castaño claro entre otra variedad de tonos.",
		C: "disminuiría los ingresos de la industria de la belleza a nivel regional.",
		D: "crearía un modelo de vida acorde con el estatus de vida foráneo.",
		E: "contaría con la participación de una hermosa fémina de tez blanca.",
		Correct: "E"
	},
	{
		name: "SM2015iBCF16-20",
		subject: "VA",
		sub_subject: "",
		prompt: "Todas las culturas, además de una concepción propia de lo bello, han tenido siempre una idea propia de lo feo, aunque a partir de los hallazgos arqueológicos normalmente es difícil establecer si lo que está representado realmente era con- siderado bello o feo: a los ojos de un occidental contemporáneo ciertos fetiches o ciertas máscaras de otras civilizaciones parecen representar seres horribles y deformes, mientras que para los nativos pueden o podían ser representaciones de lo bello.<br>Según distintas teorías estéticas, desde la Antigüedad hasta la Edad Media, lo feo es una <b>antítesis</b> de lo bello, una carencia de armonía que viola las reglas de la proporción en las que se basa la belleza, tanto física como moral, o una carencia que sustrae al ser lo que por naturaleza debería tener. Por eso, Platón, en sus Diálogos, discute en varias ocasiones acerca de lo bello y de lo feo, pero ante la grandeza moral de Sócrates se ríe del aspecto deforme de este. En cualquier caso, se admite un principio que es respetado de manera casi uniforme: si bien existen seres y cosas feos, el arte tiene el poder de representarlos de manera hermosa, y la belleza (o, al menos, la fidelidad realista) de esta imitación hace aceptable lo feo. Abundan testimonios de esta concepción, desde Aristóteles hasta Kant.<br>De modo que si nos detenemos a reflexionar, la cuestión es sencilla: existe lo feo que nos repugna en la naturaleza, pero que se torna aceptable y hasta agradable en el arte que expresa y denuncia “bellamente” la fealdad de lo feo, tanto en sentido físico como moral. Pero ¿hasta qué punto una bella representación de lo feo (y de lo monstruoso) lo transforma en algo sublime? No es casual que, en la época clásica tardía y sobre todo en la era cristiana, la problemática de lo feo se vuelva más compleja. Lo expresa muy bien Hegel en una página donde advierte que, con la llegada de la sensibilidad cristiana y del arte que la expresa, adquieren una importancia central (especialmente en relación con la figura de Cristo, sus seguidores y aun sus perseguidores) el dolor, el sufrimiento, la muerte, la tortura y las deformaciones físicas que sufren tanto las víctimas como los verdugos.",
		image: false,
		question: "En el texto, el sentido de la palabra ANTÍTESIS es",
		A: "evocación",
		B: "negación",
		C: "hipérbole",
		D: "síntesis",
		E: "suma.",
		Correct: "B"
	},
	{
		name: "SM2015iBCF17",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iBCF16-20",
		image: false,
		question: "El autor se refiere, principalmente,",
		A: "a la evolución de las diversas teorías estéticas desde la lejana Antigüedad.",
		B: "a la historia de la discusión filosófica sobre el concepto cultural de belleza.",
		C: "al choque cultural entre Oriente y Occidente sobre la valoración de lo bello.",
		D: "al concepto de lo feo como una carencia absoluta de armonía de la belleza.",
		E: "al principio estético que explica la acepta- ción de lo feo por medio del arte.",
		Correct: "E"
	},
	{
		name: "SM2015iBCF18",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iBCF16-20",
		image: false,
		question: "Uno de los siguientes enunciados es incompatible con lo aseverado en el texto.",
		A: "Todas las culturas han tenido simultáneamente una concepción de lo bello y de lo feo.",
		B: "De Aristóteles a Kant, hay un principio sobre la representación de lo feo a través del arte.",
		C: "Lo feo era entendido como una antítesis de lo bello tanto a nivel físico como moral.",
		D: "El arte cristiano mantuvo una valoración totalmente negativa de la concepción de lo feo.",
		E: "En la Antigüedad, la fealdad se entendía como desproporción y carencia de simetría.",
		Correct: "D"
	},
	{
		name: "SM2015iBCF19",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iBCF16-20",
		image: false,
		question: "De acuerdo con los hallazgos arqueológicos, se infiere que las diferencias históricas y culturales establecen diferencias estéticas, porque",
		A: "es imposible establecer ideas que cons- truyan un puente histórico que permita la interpretación de otras culturas.",
		B: "las valoraciones de unoccidental contemporáneo diferirían de las de un miembro de una civilización antigua.",
		C: "ningún arte contemporáneo puede compararse con las obras artísticas de los maestros del Renacimiento.",
		D: "el arte de la era cristiana tuvo un fugaz auge durante el predominio de la sensibilidad mística en la humanidad.",
		E: "la concepción aristotélica de un arte imitativo fue seriamente cuestionada por los filósofos Kant y Hegel.",
		Correct: "B"
	},
	{
		name: "SM2015iBCF20",
		subject: "VA",
		sub_subject: "",
		prompt: "SM2015iBCF16-20",
		image: false,
		question: "Si el arte fuese incapaz de engrandecer la deformidad,",
		A: "lo feo no habría sido aceptado y seguiría siendo igual de desagradable.",
		B: "los artistas habrían tenido que inventar una nueva concepción de lo bello.",
		C: "el arte durante la era cristiana habríar evalorado la estética del arte clásico.",
		D: "el concepto de belleza física sería radicalmente opuesto al de belleza moral.",
		E: "la teorización estética exigiría una reinterpretación de lo bello y lo feo.",
		Correct: "A"
	},
	{
		name: "SM2015iBCF21",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Luego de un arduo trabajo, Gerardo, Abel y Rodolfo deciden tomar unas merecidas vacaciones y deciden visitar la ciudad de Arequipa para probar los platos típicos de la región. Un día, en el almuerzo, ordenan lo siguiente: rocoto relleno, cuy chactado y malaya dorada; y para beber: limonada, jugo de papaya y jugo de fresa, aunque no necesariamente en ese orden.<br>Se sabe:<br>- Quien come rocoto relleno toma jugo de fresa.<br>- Gerardo come malaya dorada.<br>- Abel no toma jugo de fresa.<br>Indique la(s) afirmación(es) siempre verdadera(s).<br>I. Gerardo toma limonada.<br>II. Rodolfo toma jugo de fresa.<br>III. Abel toma jugo de papaya.",
		A: "I y II",
		B: "solo III",
		C: "solo II",
		D: "I, II y III",
		E: "I y III",
		Correct: "C"
	},
	{
		name: "SM2015iBCF22",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El sólido mostrado está formado por 16 cubitos. Después de pintar toda la superficie del sólido mostrado, halle el número de cubitos que tiene solo dos caras pintadas.",
		A: "8",
		B: "6",
		C: "4",
		D: "10",
		E: "12",
		Correct: "A"
	},
	{
		name: "SM2015iBCF23",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En el teatro, cuatro amigos ocupan cuatro asientos consecutivos en una misma fila. Se observa lo siguiente:<br>I. Leopoldo no está sentado junto a Irma.<br>II. Perico no está sentado junto a Nicole.<br>III. Nicole no está sentado junto a Leopoldo. Entonces ¿quiénes no están sentados en los extremos?",
		A: "Leopoldo y Nicole",
		B: "Leopoldo y Perico",
		C: "Irma y Leopoldo",
		D: "Perico e Irma",
		E: "Perico y Nicole",
		Correct: "D"
	},
	{
		name: "SM2015iBCF24",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Cada una de las cajas de la figura contiene nueve canicas. ¿Cuál es el menor número de canicas que deben ser trasladadas de una caja a otra para que la relación entre X, Y, Z sea como 4:3:2?",
		A: "3",
		B: "6",
		C: "2",
		D: "5",
		E: "4",
		Correct: "A"
	},
	{
		name: "SM2015iBCF25",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "De las ciudades P, Q, R, S y T, se sabe lo siguiente:<br>• La ciudad P se encuentraa 40 km al sur de R, pero a 20 km al oeste de S.<br>• La ciudad Q está a 20 km a lo este de R y la ciudad T a 15 km al sur de P.<br>De acuerdo con los datos, ¿cuál es la afirmación verdadera?",
		A: "T está al noreste de Q.",
		B: "S está al sureste de Q.",
		C: "P está al noreste de Q.",
		D: "R está al noreste de Q.",
		E: "P está al noreste de T.",
		Correct: "B"
	},
	{
		name: "SM2015iBCF26",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Un negociante compra 120 floreros de cristal a S/.600 la docena. Si se rompen 35 floreros y quiere ganar S/.120, ¿a qué precio debe vender cada florero que le queda?",
		A: "S/.75",
		B: "S/.62",
		C: "S/.72",
		D: "S/.70",
		E: "S/.80",
		Correct: "C"
	},
	{
		name: "SM2015iBCF27",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Un comerciante llenó con 75 litros de vino 120 botellas de \\(\\frac{1}{2}\\) litro y 60 botellas de \\(\\frac{1}{4}\\) de litro y las vendió a S/.30 y S/.15, cada botella, respectivamente. Luego de vender todas las botellas, ¿cuánto recaudó?",
		A: "S/.4500",
		B: "S/.4800",
		C: "S/.5000",
		D: "S/.5500",
		E: "S/.5200",
		Correct: "A"
	},
	{
		name: "SM2015iBCF28",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Halle el valor de E=99 – 97+95 – 93+...+7 – 5+3 – 1",
		A: "52",
		B: "54",
		C: "48",
		D: "46",
		E: "50",
		Correct: "E"
	},
	{
		name: "SM2015iBCF29",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Complete el cuadrado de la figura escribiendo un número entero en las casillas sin número, de modo que la suma de los tres números que forman filas, columnas y diagonales sea la misma.<br>Halle x+y.",
		A: "20",
		B: "15",
		C: "10",
		D: "-5",
		E: "-10",
		Correct: "C"
	},
	{
		name: "SM2015iBCF30",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El promedio de 56 números es 39, siendo 50 y 55 dos de los números. Si se eliminan ambos números, el promedio de los restantes es",
		A: "36,5",
		B: "38,5",
		C: "36",
		D: "37,5",
		E: "38",
		Correct: "B"
	},
	{
		name: "SM2015iBCF31",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Juan le dice a su sobrino: “Mi edad es el triple de tu edad y, dentro de 10 años, mi edad será el doble de tu edad”. ¿Cuántos años tiene Juan?",
		A: "30",
		B: "20",
		C: "40",
		D: "25",
		E: "35",
		Correct: "A"
	},
	{
		name: "SM2015iBCF32",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si en el conjunto de los números reales el operador ∆ está definido como<br>\\(\\mathrm{a∆b}\\) = \\(\\begin{cases}\\mathrm{b(a-1)}; \\text{ si ab} \\lt 0\\\\\\mathrm{a(b-1)}; \\textrm{ si ab}\\ge0\end{cases}\\) halle el valor de \\(\\frac{(-3∆4)(-4∆-3)}{4∆3}\\)",
		A: "32",
		B: "-32",
		C: "8",
		D: "64",
		E: "-16",
		Correct: "B"
	},
	{
		name: "SM2015iBCF33",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si \\(\\mathrm{x^y=y^x})\\, \\(\\mathrm{y=x^2}\\), donde x > 1, halle x+y.",
		A: "8",
		B: "4",
		C: "10",
		D: "6",
		E: "7",
		Correct: "6"
	},
	{
		name: "SM2015iBCF34",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En un salón de clase de una institución educativa de primaria, se tomó examen a 60 alumnos de los cuales aprobaron 48. El número de niños es la mitad del número de aprobados y el número de niñas aprobadas es el cuádruple del número de niños desaprobados. ¿Cuántos niños aprobaron el examen?",
		A: "4",
		B: "12",
		C: "16",
		D: "14",
		E: "10",
		Correct: "C"
	},
	{
		name: "SM2015iBCF35",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Un hombre compró 10 latas de legumbres (entre arvejas y frejoles) por S/.96. Una lata de arvejas cuesta dos soles más que una lata de frejoles. Si cada lata de frejoles cuesta S/.8 y compró más latas de arvejas que de frejoles, ¿cuántas latas de arvejas compró?",
		A: "7",
		B: "6",
		C: "5",
		D: "4",
		E: "8",
		Correct: "E"
	},
	{
		name: "SM2015iBCF36",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura, \\(\\mathrm{\\overline{AB}}\\)//\\(\\mathrm{\\overline{DC}}\\), AB=10 cm, AO=6 cm, OD=9 cm y CD=15 cm. Halle OB+OC.",
		A: "14 cm",
		B: "15 cm",
		C: "16 cm",
		D: "13 cm",
		E: "17 cm",
		Correct: "B"
	},
	{
		name: "SM2015iBCF37",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura, MNPQ es un rectángulo formado por 20 cuadraditos congruentes. Si MN=4 cm y NP=5 cm, halle el área de la región sombreada.",
		A: "4 \\(\\mathrm{cm^2}\\)",
		B: "6 \\(\\mathrm{cm^2}\\)",
		C: "3 \\(\\mathrm{cm^2}\\)",
		D: "7 \\(\\mathrm{cm^2}\\)",
		E: "5 \\(\\mathrm{cm^2}\\)",
		Correct: "E"
	},
	{
		name: "SM2015iBCF38",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura, \\(\\mathrm{\\overline{BD}}\\)//\\(\\mathrm{\\overline{CE}}\\)y el lado del cuadrado ABCD mide 4 cm. Halle el perímetro del trapecio CODE.",
		A: "\\(4(1 + \\sqrt{2})\\)cm",
		B: "\\(4(2 + \\sqrt{2})\\)cm",
		C: "\\(4(1 + 2\\sqrt{2})\\)cm",
		D: "\\(4(2\\sqrt{2} - 1)\\)cm",
		E: "\\(4(2\\sqrt{2} - 2)\\)cm",
		Correct: "C"
	},
	{
		name: "SM2015iBCF39",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura, MP=PQ y PT=NP. Halle el valor de x.",
		A: "35°",
		B: "20°",
		C: "15°",
		D: "30°",
		E: "10°",
		Correct: "B"
	},
	{
		name: "SM2015iBCF40",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura, el triángulo equilátero ABC está inscrito en la circunferencia de centro O cuyo radio mide 3 cm. Halle el área de la región sombreada.",
		A: "3π \\(\\cm^2\\)",
		B: "4π \\(\\cm^2\\)",
		C: "2π \\(\\cm^2\\)",
		D: "5π \\(\\cm^2\\)",
		E: "6π \\(\\cm^2\\)",
		Correct: "A"
	},
	{
		name: "SM2015iBCF41",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Calcule el valor de M =\\((1,25555...)^2\\) −\\((1,04444...)^2\\)",
		A: "\\(\\frac{37}{90}\\)",
		B: "\\(\\frac{347}{900}\\)",
		C: "\\(\\frac{437}{900}\\)",
		D: "\\(\\frac{731}{900}\\)",
		E: "\\(\\frac{73}{90}\\)",
		Correct: "C"
	},
	{
		name: "SM2015iBCF42",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En una progresión aritmética, la razón y el número de términos son iguales y la suma de todos los términos es 120. Si la diferencia entre el último y el primer término es 30, halle la suma de estos.",
		A: "40",
		B: "35",
		C: "60",
		D: "45",
		E: "50",
		Correct: "A"
	},
	{
		name: "SM2015iBCF43",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Halle la expresión equivalente a E = \\(\\mathrm{\\dbinom{n}{n-1}! + \\dbinom{m^2}{m^2-1}! + \\dbinom{k^2}{k^2-1}!}\); m, n, k \\(\\in\\mathrm{I}\\!\\mathrm{N}\\)",
		A: "(n−1)!+(\\(m^2\\) −1)!+(\\(k^2\\) −1)!",
		B: "\\(n^2\\)!+(m+1)!+(k+1)!",
		C: "(n−1)!+\\(m^2\\)!+\\(k^2\\)!",
		D: "n!+\\(m^2\\)!+\\(k^2\\)!",
		E: "\\(n^2\\)!+ m!+ \\(k^2\\)!",
		Correct: "D"
	},
	{
		name: "SM2015iBCF44",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Un banco otorga a una empresa un préstamo de S/.750 000 para ser cancelado dentro de un año y tres meses, cobrando una tasa de interés simple del 18% anual. ¿Qué interés pagará la empresa al vencimiento del plazo?",
		A: "S/.140 620",
		B: "S/.140 625",
		C: "S/.157 500",
		D: "S/.168 570",
		E: "S/.168 750",
		Correct: "E"
	},
	{
		name: "SM2015iBCF45",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Dada la función f(x) = x3 + 5, x ∈R, halle la función inversa de f.",
		A: "\\(\\sqrt{x − 5}\\), x ≥ 5",
		B: "\\(\\sqrt[3]{x + 5}\\), x \\(\\in\\Re\\)",
		C: "\\(\\sqrt[3]{x - 5}\\), x \\(\\in\\Re\\)",
		D: "\\(\\sqrt{x + 5}\\), x \\(\\neq 5\\)",
		E: "\\(\\sqrt[3]{-x - 5}\\), x \\(\\in\\Re\\)",
		Correct: ""
	},
	{
		name: "SM2015iBCF46",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Para todo x en el conjunto solución de la inecuación |1–x|<1, indique el intervalo al que pertenece 1 – 2x.",
		A: "(0,2)",
		B: "(−4,0)",
		C: "(0,4)",
		D: "(−2,2)",
		E: "(−3,1)",
		Correct: "E"
	},
	{
		name: "SM2015iBCF47",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Con el valor de n obtenido de la igualdad \\(\\mathrm{3^{n+1}+3^{n+2}+3^{n+3}+3^{n+4} =120}\\), halle la suma de las raíces de la ecuación \\(\\mathrm{x^3 - (2^n + 1)x^2 -n = 0}\\).",
		A: "0",
		B: "2",
		C: "1",
		D: "3",
		E: "-2",
		Correct: "B"
	},
	{
		name: "SM2015iBCF48",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Las raíces de la ecuación A\\(x^2\\)+Bx+C=0, donde A≠0, son r y s. Halle el valor de P para que las raíces de la ecuación \\(\\mathrm{x^2}\\)+Px+Q=0 sean \\(\\mathrm{r^2}\\) y \\(\\mathrm{s^2}\\).",
		A: "\\(\\frac{B^2 - 4AC}{A^2}\\)",
		B: "\\(\\frac{B^2 - 2AC}{A^2}\\)",
		C: "\\(\\frac{B^2 - 2C}{A^2}\\)",
		D: "\\(\\frac{2AC - B^2}{A^2}\\)",
		E: "\\(\\frac{2C - B^2}{A^2}\\)",
		Correct: "D"
	},
	{
		name: "SM2015iBCF49",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si en la figura AC=BC, halle x.",
		A: "22°",
		B: "24°",
		C: "44°",
		D: "34°",
		E: "20°",
		Correct: "A"
	},
	{
		name: "SM2015iBCF50",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura, ABCD es un cuadrado. Si BE=a, EF=b y FD=c, halle la relación entre a, b y c.",
		A: "\\(\\mathrm{b^2=a^2+c^2}\\)",
		B: "\\(\\mathrm{a^2=b^2+c^2}\\)",
		C: "\\(\\mathrm{c^2=a^2+b^2}\\)",
		D: "\\(\\mathrm{a^2=2b^2-c^2}\\)",
		E: "\\(\\mathrm{b^2=2a^2-c^2}\\)",
		Correct: "B"
	},
	{
		name: "SM2015iBCF51",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En el espacio, se tiene un plano \\(\\mathbb{P}\\) y dos puntos M, N ubicados a uno y otro lado de \\(\\mathbb{P}\\) respectivamente. La proyección ortogonal de \\(\\mathrm{\\overline{MN}}\\) sobre \\(\\mathbb{P}\\) es \\(\\mathrm{\\overline{M‘N‘}}\\) y mide 12cm. Si MM‘=2cm y NN ‘=4 cm, halle MN.",
		A: "7\\(\\sqrt{5}\\) cm",
		B: "8\\(\\sqrt{5}\\) cm",
		C: "6\\(\\sqrt{3}\\) cm",
		D: "6\\(\\sqrt{5}\\) cm",
		E: "5\\(\\sqrt{3}\\) cm",
		Correct: "D"
	},
	{
		name: "SM2015iBCF52",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Dos cajas de cartón de forma cúbica tienen las medidas de sus aristas en la relación de 3 a 2 y la diferencia de sus áreas laterales es 500 \\(\\mathrm{cm^2}\\). Halle el volumen de la caja más pequeña.",
		A: "1000 \\(\\mathrm{cm^3}\\)",
		B: "3375 \\(\\mathrm{cm^3}\\)",
		C: "2000 \\(\\mathrm{cm^3}\\)",
		D: "1075 \\(\\mathrm{cm^3}\\)",
		E: "900 \\(\\mathrm{cm^3}\\)",
		Correct: "A"
	},
	{
		name: "SM2015iBCF53",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la figura, la rueda de radio R pasa de P a Q, dando cuatro vueltas completas. Si PQ=80p cm, halle el valor de R.",
		A: "10π cm",
		B: "8 cm",
		C: "8π cm",
		D: "9 cm",
		E: "10 cm",
		Correct: "E"
	},
	{
		name: "SM2015iBCF54",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Halle el valor de E = \\(\\sec^2{21°} - \\cot^2 69° + 1\\)",
		A: "1",
		B: "2",
		C: "-1",
		D: "\\(\\sqrt{2}\\)",
		E: "3",
		Correct: "B"
	},
	{
		name: "SM2015iBCF55",
		subject: "MA",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Indique la expresión equivalente a M = \\(\\frac{\\textrm{sen(α+β) - sen(α-β)} }{\\textrm{cos(θ-β) - cos(θ+β)}} - \\frac{\\textrm{cos α}}{\\textrm{sen θ}}\\); α, β, θ \\(\\in\\) [0, \\(\\frac{π}{2}\\)]",
		A: "1",
		B: "2",
		C: "0",
		D: "\\(\\frac{\\cos α}{\\textrm{sen θ}}\\)",
		E: "\\(\\frac{\\textrm{sen θ}}{\\cos α}\\)",
		Correct: "0"
	},
	{
		name: "SM2015iBCF56",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En el enunciado “las manzanas y las naranjas son frutas deliciosas”, las palabras subrayadas establecen entre sí una relación semántica de TOFO",
		A: "cohiponimia.",
		B: "sinonimia.",
		C: "antonimia.",
		D: "homonimia.",
		E: "polisemia.",
		Correct: "A"
	},
	{
		name: "SM2015iBCF57",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Marque la serie que contiene las tres palabras con consonantes bilabiales.",
		A: "Balde, mesa, fólder",
		B: "Pato, uva, casaca",
		C: "Auto, bota, peso",
		D: "Bala, lápiz, mano",
		E: "Libro, piso, gancho",
		Correct: "D"
	},
	{
		name: "SM2015iBCF58",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Señale la alternativa que presenta solo palabras esdrújulas.",
		A: "Político, bíceps, transeúnte",
		B: "Parásito, farándula, químico",
		C: "Cómpratelo, referéndum, roedor",
		D: "Héroe, robots, imágenes",
		E: "Romántico, veintiún, zoólogo",
		Correct: "B"
	},
	{
		name: "SM2015iBCF59",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "La lengua oficial de un país tiene el estatus de",
		A: "dialecto.",
		B: "habla.",
		C: "idioma.",
		D: "lenguaje.",
		E: "jerga.",
		Correct: "C"
	},
	{
		name: "SM2015iBCF60",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: 'En el enunciado “James anotó un magnífico gol”, destaca la función del lenguaje denominada',
		A: "representativa o denotativa.",
		B: "apelativa o conativa.",
		C: "estética o poética.",
		D: "metalingüística o metaverbal.",
		E: "expresiva o emotiva.",
		Correct: "E"
	},
	{
		name: "SM2015iBCF61",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: 'En el enunciado “Paco Yunque estuvo nervioso aquella mañana”, la palabra subrayada cumple la función de',
		A: "sujeto.",
		B: "atributo.",
		C: "objeto directo.",
		D: "objeto indirecto.",
		E: "complemento circunstancial.",
		Correct: "B"
	},
	{
		name: "SM2015iBCF62",
		subject: "Language",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El enunciado “saldremos de paseo aunque haga frío” es clasificado como oración compuesta por subordinación adverbial",
		A: "consecutiva.",
		B: "modal.",
		C: "de finalidad.",
		D: "concesiva.",
		E: "condicional.",
		Correct: "D"
	},
	{
		name: "SM2015iBCF63",
		subject: "Literature",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El poema narrativo extenso, de tema y personajes grandiosos y con frecuente intervención de lo maravilloso, se conoce como",
		A: "epopeya.",
		B: "harawi.",
		C: "romance.",
		D: "mito.",
		E: "fábula.",
		Correct: "A"
	},
	{
		name: "SM2015iBCF64",
		subject: "Literature",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Un rasgo importante de la actitud romántica fue",
		A: "la dimensión cultural.",
		B: "la defensa de la fraternidad.",
		C: "la confianza en la razón.",
		D: "el rechazo a la tradición.",
		E: "el culto al Yo.",
		Correct: "E"
	},
	{
		name: "SM2015iBCF65",
		subject: "Literature",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El general Ollanta, personaje del drama quechua Ollantay, fue tomado prisionero debido a un ardid preparado por",
		A: "Pachacútec.",
		B: "Piqui Chaqui.",
		C: "Rumi Ñahui.",
		D: "Cusi Coyllur.",
		E: "Ima Súmac.",
		Correct: "C"
	},
	{
		name: "SM2015iBCF66",
		subject: "Psychology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: 'Cuando Juan exclama en forma efusiva “¡Yo mismo soy!”, está evidenciando un indicador positivo de',
		A: "autoestima.",
		B: "narcisismo.",
		C: "autodominio.",
		D: "autopercepción.",
		E: "autocrítica.",
		Correct: "A"
	},
	{
		name: "SM2015iBCF67",
		subject: "Psychology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "José aprendió de niño a manejar bicicleta. Dicho aprendizaje se almacena en la memoria",
		A: "emocional.",
		B: "sensorial.",
		C: "episódica.",
		D: "procedimental.",
		E: "semántica.",
		Correct: "D"
	},
	{
		name: "SM2015iBCF68",
		subject: "Psychology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: '“La finalidad del ser humano es desarrollar todo su potencial” es una tesis del enfoque',
		A: "conductista.",
		B: "psicodinámico.",
		C: "cognitivista.",
		D: "sociocultural.",
		E: "humanista.",
		Correct: "E"
	},
	{
		name: "SM2015iBCF69",
		subject: "Civic Education",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Al afirmar que el Metropolitano es un sistema de transporte necesario en Lima, un pasajero ejerce su",
		A: "deber de defensa.",
		B: "derecho de protesta.",
		C: "derecho de bienestar.",
		D: "derecho de opinión.",
		E: "deber de seguridad personal.",
		Correct: "D"
	},
	{
		name: "SM2015iBCF70",
		subject: "Civic Education",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Los prejuicios raciales y la distorsionada cultura de élite que se dan en Lima muestran conductas",
		A: "pasivas.",
		B: "intolerantes.",
		C: "fatalistas.",
		D: "democráticas.",
		E: "proactivas.",
		Correct: ""
	},
	{
		name: "SM2015iBCF71",
		subject: "Peruvian History",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En las elecciones generales de 1980, el arquitecto Fernando Belaunde Terry fue elegido por segunda vez presidente de la República. La primera medida de su gobierno fue la",
		A: "privatización de todas las empresas estatales.",
		B: "eliminación del control de la economía.",
		C: "profundización de la reforma agraria.",
		D: "devolución de los medios de prensa expropiados.",
		E: "aprobación de una nueva constitución política.",
		Correct: "D"
	},
	{
		name: "SM2015iBCF72",
		subject: "Peruvian History",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "De acuerdo con las investigaciones de María Reiche, las líneas de Nasca",
		A: "representan un calendario astronómico.",
		B: "constituyen vestigios de tumbas.",
		C: "son completamente indescifrables.",
		D: "parecen canales de regadío.",
		E: "fueron un lugar dedicado a la élite.",
		Correct: "A"
	},
	{
		name: "SM2015iBCF73",
		subject: "PH",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Durante la dominación española, con la finalidad de mantener indiviso el patrimonio acumulado y evitar así dejar en la pobreza a los herederos, se introdujo una institución llamada",
		A: "audiencia.",
		B: "capitanía.",
		C: "cacicazgo.",
		D: "mayorazgo.",
		E: "reducción.",
		Correct: "D"
	},
	{
		name: "SM2015iBCF74",
		subject: "PH",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Durante el primer gobierno de Mariano Ignacio Prado (1867 - 1868), se anuló el Tratado Vivanco- Pareja, por el cual el Estado peruano",
		A: "declaraba la estatización del guano y el salitre.",
		B: "renegociaba la construcción de ferrocarriles.",
		C: "establecía la frontera con la Gran Colombia.",
		D: "decretaba la libertad de esclavos negros.",
		E: "reconocía derechos a España por la Independencia.",
		Correct: "E"
	},
	{
		name: "SM2015iBCF75",
		subject: "UH",
		sub_subject: "",
		prompt: false,
		image: false,
		question: 'Durante la Guerra Fría, la “Doctrina Truman”, que se hizo efectiva con el Plan Marshall y la OTAN, fue una estrategia de los Estados Unidos para',
		A: "impulsar el denominado Plan Molotov.",
		B: "dividirAlemaniaenOrientalyOccidental.",
		C: "limitar el expansionismo soviético.",
		D: "iniciar la conquista del espacio sideral.",
		E: "reorientar su mirada a Latinoamérica.",
		Correct: "C"
	},
	{
		name: "SM2015iBCF76",
		subject: "UH",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Las características de frente más amplia, dientes menores fuertes y una mayor capacidad craneana corresponden al Homo habilis, que apareció hace dos millones de años en",
		A: "la sabana africana.",
		B: "las cuevas mediterráneas.",
		C: "la estepa siberiana.",
		D: "las llanuras americanas.",
		E: "los páramos europeos.",
		Correct: "A"
	},
	{
		name: "SM2015iBCF77",
		subject: "UH",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Uno de los teólogos más importantes de la Edad Media fue el dominico Tomás de Aquino. Su obra más destacada, Suma teológica, buscaba",
		A: "defender la fe ante la razón.",
		B: "fijar las dimensiones de la razón.",
		C: "explicar el origen de la religión.",
		D: "conciliar la fe con la razón.",
		E: "presentar las bases de la teología.",
		Correct: "D"
	},
	{
		name: "SM2015iBCF78",
		subject: "UH",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En 1992, mediante el Tratado de Maastricht, un grupo de países europeos creó __________ para asumir compromisos económicos y políticos comunes.",
		A: "la Comunidad Económica Europea",
		B: "la Unión Europea",
		C: "el Fondo Monetario de Desarrollo Regional",
		D: "el Parlamento Europeo",
		E: "la Organización Mundial de Comercio",
		Correct: "B"
	},
	{
		name: "SM2015iBCF79",
		subject: "Geography",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El tratado de la Antártida (1959), ratificado y prorrogado desde 1991 por cincuenta años más, estipula que las actividades desarrolladas en el territorio antártico deben destinarse",
		A: "a la fortificación militar.",
		B: "a la pesca indiscriminada.",
		C: "al ensayo de nuevas armas.",
		D: "a la explotación de recursos.",
		E: "a la investigación científica.",
		Correct: "E"
	},
	{
		name: "SM2015iBCF80",
		subject: "Geography",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Los __________ y __________ son características topográficas propias de la región alto andina sur del Perú.",
		A: "cañones - tablazos",
		B: "acantilados - lagunas",
		C: "volcanes - mesetas",
		D: "manglares - llanuras",
		E: "valles - manglares",
		Correct: "C"
	},
	{
		name: "SM2015iBCF81",
		subject: "Geography",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "En la sierra peruana, las corrientes de lodo, que consisten en flujos de agua turbia que arrasan materiales a su paso, principalmente en épocas de lluvia, se denominan",
		A: "huaicos.",
		B: "derrumbes.",
		C: "tsunamis.",
		D: "aludes.",
		E: "desbordes.",
		Correct: "A"
	},
	{
		name: "SM2015iBCF82",
		subject: "Geography",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "La acción benéfica de los gases de efecto invernadero trae como consecuencia",
		A: "la ausencia de vida en la Tierra y temperatura anual promedio de –18°C.",
		B: "el aumento de las precipitaciones y descongelamiento de los glaciares.",
		C: "el incremento del nivel de los océanos e inundación de zonas costeras.",
		D: "el cambio en la circulación atmosférica y en las condiciones meteorológicas.",
		E: "la presencia de vida en la Tierra y temperatura promedio anual de +15°C.",
		Correct: "E"
	},
	{
		name: "SM2015iBCF83",
		subject: "Economy",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "John Maynard Keynes propuso que el Estado debía intervenir en la economía cuando hubiere necesidad de regulación. A esta tendencia se le conoce como intervencionismo económico, el cual cuestiona",
		A: "la política de subsidios.",
		B: "el control de precios.",
		C: "la libertad del mercado.",
		D: "la creación de empresas públicas.",
		E: "el establecimiento de impuestos.",
		Correct: "C"
	},
	{
		name: "SM2015iBCF84",
		subject: "Economy",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El intercambio comercial entre el Perú y otros países se debe a",
		A: "la cantidad de dinero que posee cada país.",
		B: "la distancia entre los países negociantes.",
		C: "las diferentes culturas que posee cada país.",
		D: "las diferencias entre sus posibilidades productivas.",
		E: "la cantidad de población de los países negociantes.",
		Correct: "D"
	},
	{
		name: "SM2015iBCF85",
		subject: "Economy",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El agente económico especializado en administrar el proceso de producción es conocido como",
		A: "empresa.",
		B: "banco.",
		C: "hacienda.",
		D: "fábrica.",
		E: "cooperativa.",
		Correct: "A"
	},
	{
		name: "SM2015iBCF86",
		subject: "Economy",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El oligopolio y la competencia perfecta son tipos de estructura de mercado determinados por la cantidad de productores: __________ y __________ respectivamente.",
		A: "uno - pocos",
		B: "muchos - pocos",
		C: "pocos - muchos",
		D: "uno - muchos",
		E: "uno - dos",
		Correct: "C"
	},
	{
		name: "SM2015iBCF87",
		subject: "Philosophy",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Según Aristóteles, la actitud con la que comenzó la filosofía fue",
		A: "la apatía.",
		B: "la suspicacia.",
		C: "la complacencia.",
		D: "el interés.",
		E: "el asombro.",
		Correct: "E"
	},
	{
		name: "SM2015iBCF88",
		subject: "Philosophy",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Un conocimiento es objetivo cuando su verdad se determina",
		A: "por criterios sociales.",
		B: "con independencia del sujeto.",
		C: "de manera utilitaria.",
		D: "por la intuición metafísica.",
		E: "con el menor grado de probabilidad.",
		Correct: "B"
	},
	{
		name: "SM2015iBCF89",
		subject: "Philosophy",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Después de aplicar rigurosamente la duda metó- dica, Renato Descartes llegó al siguiente principio:",
		A: "<i>Tan solo existe Dios.</i>",
		B: "<i>La ciencia es demostrable.</i>",
		C: "<i>El mundo es una máquina.</i>",
		D: "<i>Pienso, luego existo.</i>",
		E: "<i>La mente es extensa.</i>",
		Correct: "D"
	},
	{
		name: "SM2015iBCF90",
		subject: "Philosophy",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Un coleccionista visita una galería de arte y elige un cuadro. Esta elección se hace a partir de",
		A: "un juicio de valor.",
		B: "su sentido denotativo.",
		C: "su significado connotativo",
		D: "una experiencia mística.",
		E: "un interés práctico.",
		Correct: "A"
	},
	{
		name: "SM2015iBCF91",
		subject: "Physics",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Dos fuerzas, \\(\\mathrm{\\overrightarrow{F_1}}\\) y \\(\\mathrm{\\overrightarrow{F_2}}\\), cada una de 100 N de magnitud, actúan sobre un punto, como se muestra en la figura. Determine la magnitud de la fuerza que equilibra estas dos fuerzas.",
		A: "200 N",
		B: "50 N",
		C: "100\\(\\sqrt{3}\\) N",
		D: "100\\(\\sqrt{2}\\) N",
		E: "100 N",
		Correct: "E"
	},
	{
		name: "SM2015iBCF92",
		subject: "Physics",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Una fuerza de magnitud 20 N desplaza un cuerpo 6,0 m sobre una superficie horizontal sin fricción. Halle la potencia desarrollada si el desplazamiento se realizó en 40,0 s.",
		A: "3,25 W",
		B: "3,00 W",
		C: "2,80 W",
		D: "3,50 W",
		E: "2,90 W",
		Correct: "B"
	},
	{
		name: "SM2015iBCF93",
		subject: "Physics",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Si un cuerpo de 40 N de peso se encuentra en equilibrio, como se muestra en la figura, ¿cuál es la magnitud de la fuerza de rozamiento?",
		A: "20 N",
		B: "40 N",
		C: "40\\(\\sqrt{3}\\) N",
		D: "20\\(\\sqrt{3}\\) N",
		E: "30\\(\\sqrt{3}\\) N",
		Correct: "D"
	},
	{
		name: "SM2015iBCF94",
		subject: "Chemistry",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "La capa de ozono en la estratósfera opera como filtro de las radiaciones ultravioletas procedentes del Sol; su debilitamiento por la contaminación atmosférica se debe a los",
		A: "clorobromacarbonos.",
		B: "cloroiodocarbonos.",
		C: "clorofluorocarbonos.",
		D: "nitroclorocarbonos.",
		E: "hidrocarburos aromáticos.",
		Correct: "C"
	},
	{
		name: "SM2015iBCF95",
		subject: "Chemistry",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Marque la ecuación química correcta para la combustión completa del metano (\\(\\ce{CH4}\\)).",
		A: "\\(\\ce{CH4_{(g)} + calor -> C + 2H2_{(g)}}\\)",
		B: "\\(\\ce{CH4_{(g)} + O2_{(g)} -> CO2_{(g)} + 2H2_{(g)}}\\) ",
		C: "\\(\\ce{CH4_{(g)} + O2_{(g)} -> CO_{(g)} + H2O_{(g)}}\\)",
		D: "\\(\\ce{2CH4_{(g)} + O2_{(g)} -> 2CO_{(g)} + 2H2O_{(g)}}\\)",
		E: "\\(\\ce{CH4_{(g)} + 2O2_{(g)} -> CO2_{(g)} + 2H2O_{(g)}}\\)",
		Correct: "E"
	},
	{
		name: "SM2015iBCF96",
		subject: "Chemistry",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Al disolver 10 g de un soluto en 30 g de agua, la concentración de la solución en % peso es",
		A: "33",
		B: "75",
		C: "30",
		D: "25",
		E: "10",
		Correct: "D"
	},
	{
		name: "SM2015iBCF97",
		subject: "Biology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Con relación al tejido meristemático, ¿cuál de las siguientes proposiciones es incorrecta?",
		A: "Desaparece en las plantas adultas.",
		B: "Está presente en las plantas jóvenes.",
		C: "Está formado por células en división activa.",
		D: "Puede ser primario o secundario.",
		E: "Es responsable del crecimiento en grosor.",
		Correct: "A"
	},
	{
		name: "SM2015iBCF98",
		subject: "Biology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "El pelo moteado de un conejo es su __________ su condición heterocigota es el __________ el cual se representa como __________.",
		A: "genotipo - fenotipo - aA",
		B: "fenotipo - híbrido - AA",
		C: "fenotipo - genotipo - Aa",
		D: "híbrido - genotipo - aa",
		E: "raza pura - genotipo - AA",
		Correct: "C"
	},
	{
		name: "SM2015iBCF99",
		subject: "Biology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "La evolución es un proceso de cambio __________ que se va haciendo más __________ y __________ a lo largo del tiempo.",
		A: "constante - simple - único",
		B: "gradual - complejo - diverso",
		C: "permanente - simple - diverso",
		D: "permanente - complejo - único",
		E: "gradual - simple - diverso",
		Correct: "B"
	},
	{
		name: "SM2015iBCF100",
		subject: "Biology",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "Con respecto a la célula bacteriana, marque verdadero (V) o falso (F) según corresponda y seleccione la alternativa correcta.<br>( ) El flagelo posee una estructura 9+2<br>( ) La pared celular está constituida por peptido- glicano.<br>() La pared celular no le confiere rigidez a la célula.<br>( ) La membrana plasmática se localiza al interior de la pared celular.",
		A: "VFFV",
		B: "FFVV",
		C: "VVFV",
		D: "FVVV",
		E: "FVFV",
		Correct: "E"
	}/*,
	{
		name: "SM2015iBCF101",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF102",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF103",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF104",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF105",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF106",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF107",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF108",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF109",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF110",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF111",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF112",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF113",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF114",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF115",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF116",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF117",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF118",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF119",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF120",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF121",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF122",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF123",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF124",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF125",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF126",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF127",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF128",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF129",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	},
	{
		name: "SM2015iBCF130",
		subject: "",
		sub_subject: "",
		prompt: false,
		image: false,
		question: "",
		A: "",
		B: "",
		C: "",
		D: "",
		E: "",
		Correct: ""
	}*/
]